### ISSUE TITLE
[Bug] karmor summary showing container id instead of container name

### ISSUE THREAD

**Issue by yasin-cs-ko-ak** [kubearmor/KubeArmor#1002]
## Bug Report
In [kubearmor-client ](https://github.com/kubearmor/kubearmor-client) when we do `karmor summary` it shows container ID instead of container name.

**General Information**

- Environment description - k3s
- Kernel version - `Linux ubuntu 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- Orchestration system version in use 
```
➜  ~ k version     
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:26Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3+k3s1", GitCommit:"f2585c1671b31b4b34bddbb3bf4e7d69662b0821", GitTreeState:"clean", BuildDate:"2022-10-25T19:59:38Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64
```
- Link to relevant artifacts (policies, deployments scripts, ...)
`kubectl apply -f https://raw.githubusercontent.com/kubearmor/KubeArmor/main/examples/wordpress-mysql/wordpress-mysql-deployment.yaml`
- Target containers/pods
 1. wordpress
 2. mysql

**To Reproduce**

1. Instruction
- Deploy this `kubectl apply -f https://raw.githubusercontent.com/kubearmor/KubeArmor/main/examples/wordpress- 
  mysql/wordpress-mysql-deployment.yaml` deployment in k3s cluster.
- Run `karmor summary` using kubearmor-client

**Expected behavior**
When we do karmor summary container name should come instead of container ID.

**Screenshots**
![incorrect-container-name](https://user-images.githubusercontent.com/92008211/203761311-49ec12a5-3fc0-46b4-90e8-e02077fb065d.png)

**Comment by TheRealSibasishBehera** [comment]
Hi ...  I would like work on this bug , if nobody is working on this

**Comment by TheRealSibasishBehera** [comment]
I was not able to reproduce the error on k3s setup .` karmor summary `worked as expected 
```
  Pod Name        wordpress-765f89bf9f-jd4jx  
  Namespace Name  wordpress-mysql             
  Cluster Name    default                     
  Container Name  wordpress                   
  Labels          app=wordpress               

Process Data
+---------------+--------------------------+-------+------------------------------+--------+
|  SRC PROCESS  | DESTINATION PROCESS PATH | COUNT |      LAST UPDATED TIME       | STATUS |
+---------------+--------------------------+-------+------------------------------+--------+
| /bin/bash     | /bin/ls                  | 3     | Wed Jan 18 22:04:59 UTC 2023 | Allow  |
```
Is there anything specific to be done after deploying the wordpress- mysql application or anything before that

**Comment by yasin-cs-ko-ak** [comment]
> I was not able to reproduce the error on k3s setup .`karmor summary`worked as expected
> 
> ```
>   Pod Name        wordpress-765f89bf9f-jd4jx  
>   Namespace Name  wordpress-mysql             
>   Cluster Name    default                     
>   Container Name  wordpress                   
>   Labels          app=wordpress               
> 
> Process Data
> +---------------+--------------------------+-------+------------------------------+--------+
> |  SRC PROCESS  | DESTINATION PROCESS PATH | COUNT |      LAST UPDATED TIME       | STATUS |
> +---------------+--------------------------+-------+------------------------------+--------+
> | /bin/bash     | /bin/ls                  | 3     | Wed Jan 18 22:04:59 UTC 2023 | Allow  |
> ```
> 
> Is there anything specific to be done after deploying the wordpress- mysql application or anything before that

Hey @TheRealSibasishBehera 
Thank you for working on this issue. 
Try [this](https://github.com/cytopia/docker-dvwa/tree/master/k8s) app to reproduce this issue and let me know if you can reproduce it or not.

**Comment by TheRealSibasishBehera** [comment]
```
  Pod Name        dvwa-mysql-55f668456f-8v2vw  
  Namespace Name  default                      
  Cluster Name    default                      
  Container Name  mysql                        
  Labels          app=dvwa-mysql,tier=backend  

Process Data
+--------------------------+------------------------------+-------+------------------------------+--------+
|       SRC PROCESS        |   DESTINATION PROCESS PATH   | COUNT |      LAST UPDATED TIME       | STATUS |
+--------------------------+------------------------------+-------+------------------------------+--------+
| /bin/bash                | /bin/cat                     | 2     | Thu Jan 19 20:49:33 UTC 2023 | ESC[0;32mAllowESC[0m  |
| /bin/bash                | /bin/date                    | 11    | Thu Jan 19 20:49:35 UTC 2023 | ESC[0;32mAllowESC[0m  |

```
Its working as expected

**Comment by nyrahul** [comment]
This is an intermittent problem. May be the problem is more prominent with containerd runtime.

**Comment by TheRealSibasishBehera** [comment]
:+1: I will try it with containerd and check if the problem persists

**Comment by kanhaiya04** [comment]
Hey @nyrahul, I tried with containerd runtime but, didn't get this issue. It's working fine.
