### ISSUE TITLE
Block events generated even when there are no policies applied in DVWA app

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#1003]
## Bug Report

Network (ICMP) related audit events are generated when there are no policies enforced at all on [dvwa](https://github.com/cytopia/docker-dvwa)(Damn Vulnerable Web Application) workload.
This is observed with AppArmor based enforcer only. My assumption is that the default apparmor profile that is created by kubearmor has some rule that denies the ICMP events. But it not known why the same is not true when wordpress-mysql app is used.

**General Information**

- Environment description (GKE, VM-Kubeadm, vagrant-dev-env, minikube, microk8s, ...)
k8s - any env

- Kernel version (run `uname -a`)
Enforcer should be AppArmor. Check using `karmor probe`.

**To Reproduce**
1. Setup k8s cluster
2. Install dvwa app
   a. `git clone https://github.com/cytopia/docker-dvwa.git`
   b. `kubectl apply -f docker-dvwa/k8s/`
   c. You should now see two pods `dvwa-web-xxx` and `dvwa-mysql-xxx` running in `default` namespace.
4. Run `karmor log --json` in another terminal to observe logs.
5. `kubectl exec -it dvwa-web-xxx -- sh -c 'ping localhost'`

At this stage, you should see Block events reported in the `karmor log` screen.
<details>
  <summary>Block events</summary>

```json
{                                               
  "Timestamp": 1669380827,                      
  "UpdatedTime": "2022-11-25T12:53:47.102712Z", 
  "ClusterName": "default",                     
  "HostName": "aks-agentpool-41853272-vmss000000",
  "NamespaceName": "default",
  "PodName": "dvwa-web-68d58bc4b9-68ckw",
  "Labels": "app=dvwa-web,tier=frontend",
  "ContainerID": "e58ce6fae940212abe16dec80557f9f8849a5a9b27e744815baad5bf402aa296",
  "ContainerName": "dvwa",
  "ContainerImage": "docker.io/cytopia/dvwa:php-8.1@sha256:ae5ff249472f01a476a352eafd442b8c3687e7d3e2e5e55ee0140d9c5b871324",
  "HostPPID": 1001314,
  "HostPID": 1001320,
  "PPID": 102,
  "PID": 108,
  "ParentProcessName": "/bin/dash",
  "ProcessName": "/bin/ping",
  "PolicyName": "DefaultPosture",
  "Type": "MatchedPolicy",
  "Source": "/bin/ping localhost",
  "Operation": "Network",
  "Resource": "domain=AF_INET type=SOCK_DGRAM protocol=ICMP",
  "Data": "syscall=SYS_SOCKET",
  "Enforcer": "AppArmor",
  "Action": "Block",
  "Result": "Permission denied"
}
{
  "Timestamp": 1669380827,
  "UpdatedTime": "2022-11-25T12:53:47.102716Z",
  "ClusterName": "default",
  "HostName": "aks-agentpool-41853272-vmss000000",
  "NamespaceName": "default",
  "PodName": "dvwa-web-68d58bc4b9-68ckw",
  "Labels": "app=dvwa-web,tier=frontend",
  "ContainerID": "e58ce6fae940212abe16dec80557f9f8849a5a9b27e744815baad5bf402aa296",
  "ContainerName": "dvwa",
  "ContainerImage": "docker.io/cytopia/dvwa:php-8.1@sha256:ae5ff249472f01a476a352eafd442b8c3687e7d3e2e5e55ee0140d9c5b871324",
  "HostPPID": 1001314,
  "HostPID": 1001320,
  "PPID": 102,
  "PID": 108,
  "ParentProcessName": "/bin/dash",
  "ProcessName": "/bin/ping",
  "PolicyName": "DefaultPosture",
  "Type": "MatchedPolicy",
  "Source": "/bin/ping localhost",
  "Operation": "Network",
  "Resource": "domain=AF_INET6 type=SOCK_DGRAM protocol=ICMPv6",
  "Data": "syscall=SYS_SOCKET",
  "Enforcer": "AppArmor",
  "Action": "Block",
  "Result": "Permission denied"
}
```
</details>

**Expected behavior**
There should be no block/audit events.

**karmor sysdump**
[karmor-sysdump-Fri Nov 25 18_31_40 IST 2022.zip](https://github.com/kubearmor/KubeArmor/files/10092956/karmor-sysdump-Fri.Nov.25.18_31_40.IST.2022.zip)

**Comment by daemon1024** [comment]
I can reproduce this on GKE, but we don't have audit logs to probe into.

I am unable to reproduce it on my personal setup with RKE+Ubuntu22.04.

Can you share what you see in audit logs? Is it due the kubearmor profile?

To check audit logs,
`tail /var/log/audit/audit.log -f `
OR
`sudo journalctl --boot _TRANSPORT=audit -f`

**Comment by nyrahul** [comment]
Hey @achrefbensaad , can you have a look at this? Thanks

**Comment by achrefbensaad** [comment]
Sure

**Comment by achrefbensaad** [comment]
This is not caused by kubearmor.
when using a diffrent ping binary in the pod, no logs are generated. the error is shown because some implimentations fails to aquire the apropriate privs before creating the socket
