### ISSUE TITLE
Add build informations to KubeArmor

### ISSUE THREAD

**Issue by achrefbensaad** [kubearmor/KubeArmor#1013]
We want to include build informations (branch, sha sum) to KubeArmor build process.

We can inspire from Discovery-engine building process [here](https://github.com/kubearmor/discovery-engine/blob/dev/src/libs/common.go#L34-L37) and [here](https://github.com/kubearmor/discovery-engine/blob/dev/src/libs/common.go#L68-L74)

**Comment by Chinwendu20** [comment]
Hello please, could I work on this?

**Comment by achrefbensaad** [comment]
Hi @Chinwendu20 , of course.

**Comment by Chinwendu20** [comment]
Please could you give me more context about the build process that you are referring to?

**Comment by achrefbensaad** [comment]
In discovery engine, we include build informations into the compiled binary. We would like to have the same informations included in KubeArmor.
![image](https://user-images.githubusercontent.com/25206910/208349622-5f1108af-cd22-4a27-9ca9-dca7147dc71c.png)

**Comment by nyrahul** [comment]
Hey @Chinwendu20, here is the [specific code line](https://github.com/kubearmor/discovery-engine/blob/b7a92bc6d110b6338ef5913c29454350459dd1b9/src/libs/common.go#L75) in the discovery-engine that you can use.

**Comment by nyrahul** [comment]
Duplicate of #1055 . Closing this one.
