### ISSUE TITLE
Some logs not displaying Namespace and Podname detaills

### ISSUE THREAD

**Issue by PrimalPimmy** [kubearmor/KubeArmor#1014]
## Bug Report

**General Information**
- K3s
- Kubectl Client Version: v1.25.4
-  Karmor Logs are here: [test2.log](https://github.com/kubearmor/KubeArmor/files/10192755/test2.log)
- Most likely calico-system in this case

**To Reproduce**

1. run the `karmor log --logFilter all --json` command and dump it into the system
2. You'll find some logs dont have namespace and podname being logged. Example given below:
`{"Timestamp":1670571404,
"UpdatedTime":"2022-12-09T07:36:44.353564Z",
"ClusterName":"default",
"HostName":"aks-agentpool-71604899-vmss000001",
"Labels":"k8s-app=calico-typha","ContainerID":"116277e1516f927222eefc2c83fad346e211d080cf64165e9c1a523cffc06e8b",
"ContainerName":"calico-typha","ContainerImage":"mcr.microsoft.com/oss/calico/typha:v3.21.6sha256:3ed72779a50d89795f9d7718cd45b6db32bbe5f62fc44935ac939b0cc52d344a","ParentProcessName":"/sbin/tini","ProcessName":"/code/calico-typha","HostPPID":655691,"HostPID":655722,"PPID":1,"PID":7,"UID":999,"Type":"ContainerLog","Source":"/code/calico-typha","Operation":"Network","Resource":"remoteip=127.0.0.1 port=9098 protocol=TCP","Data":"kprobe=tcp_accept domain=AF_INET","Result":"Passed"}
`

**Expected behavior**

Each and every log should have namespace and podnames logged

**Screenshots**

![image](https://user-images.githubusercontent.com/23097199/206651494-9b56f2a4-83ba-4c6d-8368-b9e278a41595.png)

These two logs as shown above do not show namespace or podname.

![image (1)](https://user-images.githubusercontent.com/23097199/206651840-0b2f0924-f722-4231-b498-e47fd0879e7f.png)

Empty spaces in some of the processes. This also applies to File and Network Operations as well.

**Comment by seswarrajan** [comment]
Not seeing this issue with the latest version of kubearmor. Keeping it open and observing it.
