### ISSUE TITLE
fixing lint issues

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#1018]
## Bug Report

Fix all the lint issues and ensure that CI fails for future PRs creating new lint issues.

Check the lint issues in [this action run](https://github.com/kubearmor/KubeArmor/actions/runs/3691275515).

**General Information**

- Environment description (GKE, VM-Kubeadm, vagrant-dev-env, minikube, microk8s, ...)
all
- Kernel version (run `uname -a`)
all

Tasks:
- [ ] Fix existing lint issues
- [ ] Fail the CI if a new lint issue appears.

**To Reproduce**

1. Run `make golint`
2. After raising the PR, check for any lint issues reported in the action/

**Expected behavior**
1. No lint issues are reported.

**Screenshots**
![image](https://user-images.githubusercontent.com/9133227/207873846-c76d42ec-18ea-4dad-b650-d08b9d2bc9dc.png)

**Comment by vishal-chdhry** [comment]
@nyrahul when I ran `make golint` it only showed me 3 issues unlike the one in the screenshot

**Comment by nyrahul** [comment]
> @nyrahul when I ran `make golint` it only showed me 3 issues unlike the one in the screenshot

Looks like [the lint tool used in Makefile](https://github.com/kubearmor/KubeArmor/blob/fc8468ec6fdd2355709c926a208a72e9da05a5b6/KubeArmor/Makefile#L80) and in [GH action workflow](https://github.com/kubearmor/KubeArmor/blob/fc8468ec6fdd2355709c926a208a72e9da05a5b6/.github/workflows/ci-test-go.yml#L23) are different.

It is possible for you to make changes in Makefile to use revive in place of golint?

CC: @daemon1024

**Comment by daemon1024** [comment]
Yup! @Vishal-Chdhry I looked at #1024 and there are still pending lint issues which should be identified if you use revive locally as well. You can take a look at https://github.com/mgechev/revive to get to know about how to install and use it.
