### ISSUE TITLE
check support for ubuntu 16.04

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#1041]
There has been a request from a user to check whether kubearmor supports ubuntu 16.04.

Tasks:
- [ ] Create a k8s cluster using Ubuntu 16.04 (either using kubeadm or using k3s)
- [ ] Is enforcement supported? What is the LSM used?
- [ ] Is observability supported? Depends on whether eBPF is supported by the kernel
- [ ] Get output of `karmor probe`
- [ ] Update [kubearmor support matrix](https://github.com/kubearmor/KubeArmor/blob/main/getting-started/support_matrix.md)

**Comment by VedRatan** [comment]
HI! @nyrahul, I am new to this repo and would like to work on this issue.

**Comment by Ankurk99** [comment]
Hey @VedRatan, Welcome to the KubeArmor community! Glad that you want to contribute. Here are the resources, which might help you in solving the issue:
- K3s and KubeArmor setup: https://github.com/kubearmor/KubeArmor/blob/main/contribution/development_guide.md#2-self-managed-kubernetes
- To install karmor  - `curl -sfL http://get.kubearmor.io/ | sudo sh -s -- -b /usr/local/bin`
- `karmor install` will install KubeArmor once you have a k8s cluster ready (k3s or kubeadm)
- To get the supported enforcement and observability, please attach `karmor probe` output


For more help, feel free to ask here or ping us on slack.

**Comment by VedRatan** [comment]
Thanks a lot @Ankurk99  will surely look ask for help if needed.

**Comment by VedRatan** [comment]
hey @Ankurk99 can I test its working on minikube?

**Comment by nyrahul** [comment]
> hey @Ankurk99 can I test its working on minikube?

Minikube in vm-driver mode installs its own iso (own distribution) and hence won't work.

I would suggest using k3s. Following would be the steps:
1. Install Ubuntu 16.04 in a new VM. Subsequent steps should now be handled in the new VM.
1. Install k3s: `curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC='--disable traefik' sh -s - --write-kubeconfig-mode 644`
2. Copy kubeconfig: `mkdir -p ~/.kube && cp /etc/rancher/k3s/k3s.yaml ~/.kube/config`
3. Now you should see few (maybe 3) pods running when you use `kubectl get pods -A`.
4. Install karmor cli: `curl -sfL http://get.kubearmor.io/ | sudo sh -s -- -b /usr/local/bin`
5. Install kubearmor: `karmor install`
6. KubeArmor pods should go into Running state. If not, check the reason.
7. If KubeArmor is in Running state, check `karmor probe` and check if Active LSM is apparmor.

**Comment by VedRatan** [comment]
Hey, @nyrahul I think that KubeArmor is working fine on Ubuntu 16.04.
![image](https://user-images.githubusercontent.com/82467006/214772016-94d33255-8649-4fe2-b462-b9b2b9cabb87.png)

**Comment by nyrahul** [comment]
Thanks for verifying this @VedRatan. 

Can you update the [kubearmor support matrix](https://github.com/kubearmor/KubeArmor/blob/main/getting-started/support_matrix.md#supported-linux-distributions) to include 16.04?

Also is it possible for you to upload the output of following command here by running it on the ubuntu16.04 node?
`curl -s https://raw.githubusercontent.com/nyrahul/linux-kernel-configs/main/lk-config-get.sh | bash -s`

The above command will create a folder called "Ubuntu 16.04" (similar name) and it will contain default kernel/boot config and other system details.

Thanks

**Comment by Ankurk99** [comment]
Also can you please also check the observability aspect? Apply a security policy and check whether you are getting the subsequent alerts.

**Comment by VedRatan** [comment]
sure @nyrahul, I'll upload the ss of the output along with the PR
