### ISSUE TITLE
KubeArmor crashing if port 32767 already in use

### ISSUE THREAD

**Issue by Ankurk99** [kubearmor/KubeArmor#1051]
## Bug Report

**General Information**

- Environment description - k3s (locally)
- Kernel version - 5.15 

**To Reproduce**

1. Install KubeArmor `karmor install` 
2. Simultaneously run `karmor logs` before KubeArmor pod is started
 
**Expected behavior**

KubeArmor should be installed and run successfully.

**What's happening?**
ERROR	Failed to listen a port (:32767, listen tcp :32767: bind: address already in use)

**Why is it happening?**
`karmor` binds to port 32767 which is used by KubeArmor, if `karmor logs` command is run prior to KubeArmor installation, it fails.

**Any solution?** 
`karmor` should not bind to port 32767 and should instead start looking for ports after that.

**Comment by TheRealSibasishBehera** [comment]
Hey @Ankurk99 , I would like to work on this issue

**Comment by TheRealSibasishBehera** [comment]
I have done a PR regarding this issue, please kindly review. Thanks
