### ISSUE TITLE
Test KubeArmor on AWS Graviton 

### ISSUE THREAD

**Issue by Ankurk99** [kubearmor/KubeArmor#1063]
## Feature Request

**Short Description**
We already support KubeArmor on ARM based processors (tested on Raspberry Pi 4, M1). The aim of this issue is to test and confirm KubeArmor working on AWS ARM based processor - Graviton.
- [x] enforcement supported? What is the LSM used?
- [x] Audit/Observability supported
- [x] Paste the output of `karmor probe`

Ref: https://aws.amazon.com/ec2/graviton/

**Comment by HariVamsiK** [comment]
Hello @Ankurk99 I'll work on this issue. Please assign it to me.

**Comment by Ankurk99** [comment]
Hey @HariVamsiK, if you need any assistance in setting up the cluster or if you want access to AWS Graviton, feel free to ask.

**Comment by HariVamsiK** [comment]
Yeah sure. Thanks @Ankurk99

**Comment by Ankurk99** [comment]
Hey @HariVamsiK, were you able to setup the cluster?

**Comment by HariVamsiK** [comment]
Did it yesterday..My AWS account was having some issues. I'm yet to test it.

**Comment by HariVamsiK** [comment]
![1](https://user-images.githubusercontent.com/112711197/215957928-12bb4a64-cc29-4c70-9e6a-54197dbff3f8.png)

I have used Graviton instance(t4g.small) with Ubuntu 22.04 arm64 as the image. Deployed K3s and probed it.

**Comment by HariVamsiK** [comment]
@Ankurk99 Do I need to test it on any other platform(like microk8s or minikube)? If not I can update the support matrix and raise the PR.

**Comment by Ankurk99** [comment]
Hey @HariVamsiK it seems that KubeArmor is running fine. Can you please perform the items mentioned in the description checklist? For enforcement you can try applying any policies and see if the resources are being correctly blocked. Similarly we will be expecting logs for the corresponding enforcement. This should be verified with `karmor logs` showing the appropriate alerts based on the enforcement (with details like applied policy name, action, LSM used etc.)
This link might help you choosing the testing workload (wordpress-mysql) and the security policies which you can apply for testing: https://github.com/kubearmor/KubeArmor/wiki/KubeArmor-manual-tests-before-releases

Please let us know if you face any difficulty

**Comment by HariVamsiK** [comment]
Yeah sure.

**Comment by Ankurk99** [comment]
Hey @HariVamsiK, were you able to test the enforcement and observability?

**Comment by HariVamsiK** [comment]
I deployed wordpress-sql and enforced all the policies that are present. I'm unable to test whether a policy is working or not. I'll check it out today and will report you in the meeting that we have.

**Comment by HariVamsiK** [comment]
<details>
<summary>karmor probe and Pods</summary>
<br>
![4](https://user-images.githubusercontent.com/112711197/217780274-9264db84-9136-44ee-a04f-bba6e7183d63.png)
</details>
<details>
<summary>wordpress-sql deployment and policies applied, tested </summary>
<br>
![1](https://user-images.githubusercontent.com/112711197/217780507-55c3dc08-caf3-4485-acf5-d7d7dbed0e36.png)
</details>
<details>
<summary>karmor logs </summary>
<br>
![2](https://user-images.githubusercontent.com/112711197/217781051-5f442cb3-f1f5-4e8e-be5b-a8226377339c.png) 
<br>
![3](https://user-images.githubusercontent.com/112711197/217781086-a93433d8-57ea-43fa-b9c0-2ea12f9d0825.png)
</details>

**Comment by HariVamsiK** [comment]
<details>
<summary>karmor probe and pods </summary>
<br>
<img src="https://user-images.githubusercontent.com/112711197/217782633-37d9bb13-c86c-4818-b29c-4af190fc5269.png" width="1920">
</details>
<details>
<summary>wordpress-mysql deployed and tested</summary>
<br>
<img src="https://user-images.githubusercontent.com/112711197/217783740-7c64978b-74f8-4ad5-9e0a-463115b81575.png" width="1920">
</details>
<details>
<summary>karmor logs</summary>
<br>
<img src="https://user-images.githubusercontent.com/112711197/217784089-a26bc1b2-06d5-4e4a-8159-51c18ab6f1fa.png" width="1920">
<br>
<img src="https://user-images.githubusercontent.com/112711197/217784176-f2361869-4d3b-4dcf-ab69-ba4264184b88.png" width="1920">
</details>

**AppArmor is primarily used in enforcement and it is the Active LSM.
Audit/Observability Supported : Yes**

**Comment by nyrahul** [comment]
Lets verify with Amazon Linux 2 as well. We can update the support-matrix post that.

**Comment by HariVamsiK** [comment]
<details>
<summary>karmor probe and pods </summary>
<br>
<img src="https://user-images.githubusercontent.com/112711197/218294230-b4959d71-756e-441d-bea3-08358c26de07.png" width="1920">
<br>
<img src="https://user-images.githubusercontent.com/112711197/218294234-ef509f57-e896-4353-8936-3b6dc0309ebd.png" width="1920">
</details>
<details>
<summary>wordpress-mysql deployed and tested</summary>
<br>
<img src="https://user-images.githubusercontent.com/112711197/218294263-347ddea5-d066-4b78-80dc-eb00017b6768.png" width="1920">
</details>
<details>
<summary>karmor logs</summary>
<br>
<img src="https://user-images.githubusercontent.com/112711197/218294273-a373b24f-419a-4ae5-86c8-ee863b471f37.png" width="1920">
</details>

**There is no Active LSM, checking the karmor logs after testing security policies on wordpress-mysql the enforcer is eBPF Monitor.**
**Audit/Observability: Yes**

**Comment by Ankurk99** [comment]
@HariVamsiK Can you please update the support matrix with AWS Graviton support here: https://github.com/kubearmor/KubeArmor/blob/main/getting-started/support_matrix.md?
