### ISSUE TITLE
Addition of Deployment Name in KubeArmor Alerts/Telemetry And Summarized Observability

### ISSUE THREAD

**Issue by AbhinavCSY** [kubearmor/KubeArmor#1065]
## Feature Request

**Short Description**

In addition to other metadata like pod name, namespace, and cluster name, having the **Deployment Name** for Alerts and telemetry, and Summarised Observability will give more visibility. 

Tasks:
- [x] Handle deployments
- [x] Handle replicasets
- [x] Handle statefulsets
- [x] Handle daemonset
- [x] Check what other things needs to be handled
- [x] Add testcase for each

I suggest telemetry format which is like (note the nested json):
```
...
"owner": {
    "ref": "deployments/daemonsets/replicasets/statefulsets",
    "name": "ubunutu-1-deploy",
    "namespace: "default",
}
...
```

**Comment by TheRealSibasishBehera** [comment]
Hi ! If nobody is working on this issue , i would like to work on it 

I think we need to add a paramater to the `Log `Structure and change `message Alert` in `protobuf/kubearmor.proto`  . We can have the deploymentName from  `deploymentName` variable here
https://github.com/kubearmor/KubeArmor/blob/main/KubeArmor/core/kubeUpdate.go#L533

The doubt i am having is , does pod need to be controlled by a deployment . Can it not be controlled by a replicationSet without a deployment ?

In such case adding PodOwnerName would make more sense than just DeploymentName
and its available as variable `podOwnerName` in the following code 
https://github.com/kubearmor/KubeArmor/blob/main/KubeArmor/core/kubeUpdate.go#L529-L543

final Alert would have a added field , for eg: 
`PodOwnerName: replicaset/example-replicaset` ,
`PodOwnerName :deployment/example-deployment
`

Please add if i am missing something

**Comment by Prateeknandle** [comment]
@TheRealSibasishBehera actually I already implemented the code and added the changes, will soon open the pr, So, you may work on another issue, although appreciate your contribution, thanks. Also try to assign yourself an issue before you start working on it.

**Comment by TheRealSibasishBehera** [comment]
@Prateeknandle Thanks for working on this 
I was waiting for a response from maintainers  .I didnt know you were on it , as it was unassigned and there were no comments

Let me know if could help :slightly_smiling_face:

**Comment by Prateeknandle** [comment]
Hey @daemon1024, I implemented the chanages required, but how can we check the changes, I was using karmor, but ig we can't use this because it uses [fd.alertStream.Recv()](https://pkg.go.dev/github.com/kubearmor/KubeArmor/protobuf@v0.0.0-20221117040949-d3559c7ffd74#LogService_WatchAlertsClient.Recv) to receive the alerts and it doesn't have DeploymentName filed, so ig it will not detect it rn.

**Comment by Prateeknandle** [comment]
@AbhinavCSY we only need `DeploymentName` to be added in karmor logs ?

**Comment by AbhinavCSY** [comment]
Yes, for now only DeploymentName @Prateeknandle

**Comment by nyrahul** [comment]
> Yes, for now only DeploymentName @Prateeknandle

@Prateeknandle , we need to handle other types as well. Sorry about the confusion. Please check my updated task description.
