### ISSUE TITLE
add hostvisibility information to karmor probe

### ISSUE THREAD

**Issue by legorie** [kubearmor/KubeArmor#1078]
## Feature Request

To add the Host Visibility Level to the `karmor probe` command [Issue #199 of kubearmor-client ](https://github.com/kubearmor/kubearmor-client/issues/199), we need to modify the [karmorprobedata.go](https://github.com/kubearmor/KubeArmor/blob/main/KubeArmor/core/karmorprobedata.go) file; so that the required data is captured in the `/tmp/karmorProbeData.cfg` file.

**Comment by legorie** [comment]
Hi @Ankurk99 , I've created a draft PR for the proposed code change, would you please review and give your feedback.

**Comment by legorie** [comment]
Hi @Ankurk99 , Thanks for the feedback on the draft PR, will sign the commit in a new PR.
Have created a draft PR for the kubearmor-client changes, will some example outputs, please have a look and let me know:
https://github.com/kubearmor/kubearmor-client/pull/254

**Comment by Ankurk99** [comment]
> Hi @Ankurk99 , Thanks for the feedback on the draft PR, will sign the commit in a new PR.

You don't need to create a new PR for that. You can sign the previous commit with `git commit --amend --no-edit -s`

**Comment by legorie** [comment]
Thank you Ankur, was able to sign my previous commit using the command..
