### ISSUE TITLE
update documentation with the new namespace visibility annotations

### ISSUE THREAD

**Issue by achrefbensaad** [kubearmor/KubeArmor#1090]
## Feature Request

**Short Description**
PR #1088 , we have introduced the ability to select what kind of event to trace "file/network/process/capabilities".
How to leverage this feature is not yet documented.

The document should explicitly mention:
- [ ] if telemetry is disabled, the user wont get audit event even if there is an audit rule

**Comment by jatinagwal** [comment]
Would love to work on this. I think you have mentioned the wrong PR??

**Comment by achrefbensaad** [comment]
Hi @jatinagwal, Sure. Ill asign the issue to you.

you are right, I linked to the issue. This is the PR in question #1087, It is not merged yet.

**Comment by jatinagwal** [comment]
Hey @achrefbensaad , Will submit first draft by thursday

**Comment by kranurag7** [comment]
Hey @jatinagwal The PR is merged now.
