### ISSUE TITLE
Support for Arch linux

### ISSUE THREAD

**Issue by rahulk789** [kubearmor/KubeArmor#1093]
## Feature Request

Support for Arch linux.

- [ ]  enforcement supported? What is the LSM used?
- [ ]  Audit/Observability supported
- [ ]  Paste the output of karmor probe

**Comment by Ankurk99** [comment]
Hey @rahulk789, can you elaborate more on this? Are you talking about the linux distro "Arch linux" here?
If that's the case, then do we have any issue running KubeArmor on Arch? I am using Arch based linux (Manjaro) and don't see any issue.

**Comment by rahulk789** [comment]
Yes I am talking about the distro. I made this issue because i did not see Arch linux listed in https://github.com/kubearmor/KubeArmor/blob/main/getting-started/support_matrix.md
is there a particular reason for it not being listed? If this is just a mistake, we can fix it immediately with no trouble and close the issue.

**Comment by Ankurk99** [comment]
In the support matrix, we haven't put a lot of distros. It's just the more popular and the ones we have tested. If you want to go ahead with testing Arch Linux (with the Linux version) and add it to the matrix, we will be more than happy.

**Comment by rahulk789** [comment]
Update:
I have been following this documentation (systemd deployment on bare-metal)
https://github.com/kubearmor/KubeArmor/blob/main/getting-started/kubearmor_vm.md
running `sudo journalctl -u kubearmor -f` and restarting(or enabling/starting) the kubearmor service gave me the following error.

![image](https://user-images.githubusercontent.com/83643646/220943095-9eaff9e8-51c9-4bfc-ad8d-cc05e079b3a8.png)

version used: v0.8.0

I will try fixing this on my own (seems like i have to generate the object file? ) but any help is good.

**Comment by Ankurk99** [comment]
> I will try fixing this on my own (seems like i have to generate the object file? ) but any help is good.

Yes, you will need to generate the BPF compiled binaries. Run `make` inside /opt/kubearmor/BPF/

**Comment by Ankurk99** [comment]
Btw, we would be more interested to know about running KubeArmor on k8s.

**Comment by Ankurk99** [comment]
Hey @rahulk789, are you working on this?

**Comment by rahulk789** [comment]
Yes. I ran it using minikube and while running karmor install, it takes too long to deploy the second pod. Is there a way to check the logs ?

**Comment by Ankurk99** [comment]
Yes, you can check using `kubectl logs` and `kubectl describe` for more details. 
But I would recommend you to also check with k3s, as KubeArmor might have some issues with minikube. Ref: https://github.com/kubearmor/KubeArmor/issues/756

**Comment by rahulk789** [comment]
Thanks

**Comment by rahulk789** [comment]
Arch Linux with kernel 6.2.1-arch1-1 works successfully with k3s 
![image](https://user-images.githubusercontent.com/83643646/226315201-170dc638-1aaf-4f81-912b-508de0c1fed3.png)

**Comment by rahulk789** [comment]
@Ankurk99 Is there anything else you would like me to test on k3s before I send a pr changing the support matrix?
I shall work on bare-metal install until then.

**Comment by Ankurk99** [comment]
Yes, please raise a PR with `karmor sysdump` output file.
