### ISSUE TITLE
Support for DigitalOcean Kubernetes (DOKS)

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#1120]
## Feature Request

**Short Description**

Supporting [k8s cluster solution from Digital Ocean](https://www.digitalocean.com/products/kubernetes), aka DOKS.

**Describe the solution you'd like**

- [ ] Check if policy enforcement, observability, audit rules, network segmentation is supported
- [ ] Get output of `karmor probe`
- [ ] Update [kubearmor support matrix](https://github.com/kubearmor/KubeArmor/blob/main/getting-started/support_matrix.md)
- [ ] Provide and attach `karmor sysdump`

**Comment by SuperAayush** [comment]
Hey, I would like to work on this!!

**Comment by VedRatan** [comment]
Can I work on this one?

**Comment by nyrahul** [comment]
Thank you for your interest. Apologies for late reply. Please let us know if you are still interested. Thanks

**Comment by SuperAayush** [comment]
Hey @nyrahul!!
Would be more than interested and can you please share some resources I can refer to in order to understand this completely, since I am a beginner here.

Thank You!!

**Comment by VedRatan** [comment]
Yes @nyrahul I am interested in this issue.

**Comment by nyrahul** [comment]
Folks, thank you for the interest. For ref, [this issue](https://github.com/kubearmor/KubeArmor/issues/1107) handled the IBM k8s support.

**Comment by nyrahul** [comment]
@VedRatan , any updates here?

**Comment by Amishakumari544** [comment]
If no one is working, I want to work on this. @nyrahul

**Comment by nyrahul** [comment]
> If no one is working, I want to work on this. @nyrahul

Great! many thanks to your contributions.

**Comment by VedRatan** [comment]
Sorry, @nyrahul, I am working on this one, and will soon update you regarding this issue.

**Comment by VedRatan** [comment]
I was busy with my exams.

**Comment by Amishakumari544** [comment]
Hey @VedRatan If you want to work go ahead :)

**Comment by VedRatan** [comment]
Hey @Amishakumari544, if you want, you can work on this one. There will be absolutely no issues from my side.

**Comment by Ankurk99** [comment]
Hey @Amishakumari544, @VedRatan are you working on this issue? Were you able to setup the DOKS environment?

**Comment by Amishakumari544** [comment]
I was confused in deploying the kubearmor that is clear to me now.will ping if I need help for the next step.

**Comment by Vyom-Yadav** [comment]
@nyrahul Assign it to me.

**Comment by Ankurk99** [comment]
Hey @Vyom-Yadav, were you able to setup KubeArmor on DOKS?

**Comment by Vyom-Yadav** [comment]
> Hey @Vyom-Yadav, were you able to setup KubeArmor on DOKS?

Yup, I used PayPal.

**Comment by nyrahul** [comment]
Great news, KubeArmor is [now available](https://marketplace.digitalocean.com/apps/kubearmor) on Digital Ocean marketplace.
