### ISSUE TITLE
Support for AWS EKS-Fargate

### ISSUE THREAD

**Issue by kranurag7** [kubearmor/KubeArmor#1123]
## Feature Request
Support for AWS Fargate. This issue is intended to track the progress of support for AWS fargate. 

**Short Description**

This issue is intended to support running kubearmor on container-as-a-service platforms (CaaS) starting with AWS Fargate. 
This can be further extended to [GKE autopilot](https://github.com/kubearmor/KubeArmor/issues/805) and Azure container instances. We can't run daemonset on these platforms, and kubearmor requires a daemonset that needs to be run in your cluster. As of now kubearmor daemonset requires [hostNetwork & hostPID](https://github.com/kubearmor/KubeArmor/blob/main/deployments/EKS/kubearmor.yaml#L182-L183) and AWS Fargate doesn't allow access to hostNetwork. 

Here are a few of the links that are relevant to the issue. 
- [ability to use ebpf on fargate instances](https://github.com/aws/containers-roadmap/issues/1027)
- https://blog.aquasec.com/protecting-aws-fargate-containers-at-runtime
- https://sysdig.com/blog/falco-support-on-aws-fargate/
- https://docs.aws.amazon.com/AmazonECS/latest/bestpracticesguide/fargate-security-considerations.html
- https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-security

**Describe the solution you'd like**

The implementations are yet to be discussed.

**Comment by nyrahul** [comment]
Need a document to explain fargate kubearmor deployment.

**Comment by integratechfze** [comment]
> Need a document to explain fargate kubearmor deployment.

Do we have this ? @nyrahul

**Comment by nyrahul** [comment]
Hey @integratechfze , AWS Fargate support was not eventually added in the open source version of KubeArmor, hence we closed this issue. AWS Fargate, ECS support is available only in the AccuKnox Enterprise version.

AWS Fargate eventually used a completely different "enforcer" and didn't depend upon LSMs for enforcement. However, it (the chosen enforcer) still provides "inline mitigation" capabilities.
