### ISSUE TITLE
relay server crashing often

### ISSUE THREAD

**Issue by michalschott** [kubearmor/KubeArmor#1141]
I've noticed that relay is crashing very often, I was able to extract this from logs - https://gist.github.com/michalschott/8f1ff6451ba11673eed54f6ff7babd0f

image used: `kubearmor/kubearmor-relay-server:latest`

**Comment by Aryan-sharma11** [comment]
Hey, I would like to work on this issue

**Comment by Aryan-sharma11** [comment]
@michalschott Hey, can you please mention the environment and the steps to reproduce this issue?

**Comment by michalschott** [comment]
I have played with resource assigned to this deployment, it looks way better now.

From what I know, the error is caused due to multiple go routines trying to write to the same map variable, and one of the way is to use mutex to prevent this. Briefly looked at code and I can't see this in use.
