### ISSUE TITLE
KubeArmor ClusterRole missing permissions

### ISSUE THREAD

**Issue by daemon1024** [kubearmor/KubeArmor#1143]
## Bug Report

KubeArmor introduced custom cluster role as part of #1026 but for some reason it doesn't have enough permissions and Kubearmor container gets stuck at "The node information is not available"

cc @kranurag7

**Comment by Nold360** [comment]
It seems like the ClusterRole `kubearmor-clusterrole` doesn't exist at all. 

Would love to be have a helm chart or something like `karmor install --template` to just get the plain yaml for gitops.

**Comment by Ankurk99** [comment]
> It seems like the ClusterRole kubearmor-clusterrole doesn't exist at all.

We do have ClusterRole defined: https://github.com/kubearmor/KubeArmor/blob/main/deployments/k3s/kubearmor.yaml#L24

> Would love to be have a helm chart or something like karmor install --template to just get the plain yaml for gitops.

Do you mean to save KubeArmor manifest? For that we do have a command: `karmor install --save`

**Comment by DelusionalOptimist** [comment]
@kranurag7 @daemon1024, were we able to test the ClusterRole on other platforms? AFAIR, it was failing only on GKE, right?

**Comment by kranurag7** [comment]
> were we able to test the ClusterRole on other platforms? AFAIR, it was failing only on GKE, right?

I was able to test it on GKE standard cluster. It was AKS on which we were having issues.

**Comment by DelusionalOptimist** [comment]
Handled in v0.10.2. Good to close.
