### ISSUE TITLE
change KubeArmor logo in Readme

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#1147]
KubeArmor is using the CamelCase notation in all places except for in the logo. The aim is to use a CamelCase notation in the logo as well and please find attached the logo to be used.

Task:
- [ ] replace the KubeArmor logo with the attached logo in the README
- [ ] check any places where CamelCase notation is not used and amend it.

![kubearmor](https://user-images.githubusercontent.com/9133227/224220511-3118b63c-218e-4b99-9235-fe45d4067133.png)

**Comment by Amishakumari544** [comment]
I would like to work on this please assign me🙂

**Comment by nyrahul** [comment]
> I would like to work on this please assign me🙂

Awesome. Thank you for your interest. Please let us know on slack if we can help in any way.
