### ISSUE TITLE
Bug: KubeArmor running in host mode is dropping events due to busy even channel

### ISSUE THREAD

**Issue by Ankurk99** [kubearmor/KubeArmor#1155]
## Bug Report

**General Information**

- Environment description: Host mode with -enableKubeArmorHostPolicy and -enableKubeArmorPolicy
- Kernel version (run `uname -a`): 5.15.81-1-MANJARO

**To Reproduce**

1. `make run-container` 
2. Wait for a minute or two and observe the KubeArmor logs

**Observed behavior**
Getting the following warning:

```
WARN	Event droped due to busy event channel
```

**Comment by zhy76** [comment]
I'll fix this!
