### ISSUE TITLE
BPF LSM Host Policy Enforcement

### ISSUE THREAD

**Issue by daemon1024** [kubearmor/KubeArmor#1158]
Verify Host Policy Enforcement for BPF LSM. We have the code as part of https://github.com/KubeArmor/KubeArmor/blob/8b6634e2fccef55d15407b3fb4ee6b6de38e47d4/KubeArmor/enforcer/bpflsm/hostRulesHandling.go

But we need to check if it's working or not. 

Attaching screenshots from Slack reporting it not working

- GKE
  ![image](https://user-images.githubusercontent.com/47106543/225053701-035e9f11-7d8c-4e2c-97ef-e203de51d115.png)
- AWS 
  ![image](https://user-images.githubusercontent.com/47106543/225053750-0e971aba-bc13-4920-b327-2ccd2903ed24.png)

**Comment by nyrahul** [comment]
This is working. The basic point is that host policy/visibility is by default disabled in k8s environment and has to be enabled explicitly. Please check [the FAQ](https://github.com/kubearmor/KubeArmor/blob/main/getting-started/FAQ.md#how-to-enable-kubearmorhostpolicy-for-k8s-cluster).
