### ISSUE TITLE
Install KubeArmor in "kubearmor" namespace by default 

### ISSUE THREAD

**Issue by Ankurk99** [kubearmor/KubeArmor#1167]
## Feature Request

**Install KubeArmor in 'kubearmor' namespace**

Currently KubeArmor is being installed in kube-system namespace. The aim is to install it in a lesser privileged namespace (kubearmor).

**Is your feature request related to a problem? Please describe the use case.**
`kube-system` namespace is used for objects created by the Kubernetes system and is reserved for system-level resources and components that are critical to the functioning of the cluster. Installing any external deployments with the system critical resources is not recommended.

**Describe the solution you'd like**

The steps will include:
- [Feeder-service](https://github.com/accuknox/Feeder-service) changes need to be done in order to detect KubeArmor in any namespace (ref: https://github.com/accuknox/discovery-engine/pull/674)
- Change the default namespace from kube-system to kubearmor

Ref PR: https://github.com/kubearmor/KubeArmor/pull/1372

**Comment by DelusionalOptimist** [comment]
Just needs to be validated on SAAS before closing. cc @Ankurk99 @Prateeknandle

**Comment by nyrahul** [comment]
@Prateeknandle , what is the current status ?

**Comment by Prateeknandle** [comment]
pr is in review state

**Comment by Prateeknandle** [comment]
Validated on SAAS env, it's working
![Screenshot from 2023-07-31 20-39-14](https://github.com/kubearmor/KubeArmor/assets/56027872/ce26cc7c-0423-44f3-be13-11e62160b53e)

**Comment by Prateeknandle** [comment]
Validated on SAAS env, it's working
![Screenshot from 2023-07-31 20-39-14](https://github.com/kubearmor/KubeArmor/assets/56027872/ce26cc7c-0423-44f3-be13-11e62160b53e)

**Comment by Prateeknandle** [comment]
We have [agent-charts](https://github.com/accuknox/agents-chart) new release. 
> So basically, we deleted existing tag v0.1.5 of agents-chart & re-tagged it with new changes.
Agents-chart v0.1.5 is currently used in saas-dev for onboarding cluster

Now I'm not sure whether this would upgrade using `helm upgrade` or not. 
If it'll upgrade FS then we should move to the next step here.

cc: @nyrahul @Ankurk99

**Comment by Ankurk99** [comment]
> Now I'm not sure whether this would upgrade using helm upgrade or not.
If it'll upgrade FS then we should move to the next step here.

Yes, it updated the Feeder-service charts

**Comment by daemon1024** [comment]
Related https://github.com/kubearmor/KubeArmor/pull/1377
