### ISSUE TITLE
Use registry client for updating stable release workflow

### ISSUE THREAD

**Issue by daemon1024** [kubearmor/KubeArmor#1169]
## Feature Request

**Short Description**

We can leverage  [`regctl`](https://github.com/regclient/regclient) to just update our stable releases to have them point to specific version by
```
regctl image copy kubearmor/kubearmorxxx:<version-no> kubearmor/kubearmorxxx:stable
```

**Is your feature request related to a problem? Please describe the use case.**

We rebuild stable images everytime there's an update related to it while stable just needs to point to an existing  image. 

**Describe the solution you'd like**

Update ci-stable-release and ci-latest-release/push-stable to leverage `regctl`.

**Comment by zhy76** [comment]
I can try this, can you assign this to me?

**Comment by daemon1024** [comment]
Thanks @zhy76, Lemme know if you need any  help with this.
