### ISSUE TITLE
Call for ADOPTERS

### ISSUE THREAD

**Issue by daemon1024** [kubearmor/KubeArmor#1171]
The purpose of this issue is to get a list of organizations/individuals who are using KubeArmor to help armor up their workloads in Kubernetes.

The idea is to use the information provided in this issue to create the ADOPTERS.md file.

Please comment on this issue with details like:

Some references on Adopters.md from other CNCF projects:

https://github.com/containerd/containerd/blob/master/ADOPTERS.md
https://github.com/cortexproject/cortex/blob/master/ADOPTERS.md
https://github.com/kyverno/kyverno/blob/main/ADOPTERS.md

**Comment by Vyom-Yadav** [comment]
@daemon1024 Pin this issue to get more attention.

**Comment by Amishakumari544** [comment]
VMware: VMware, a leading provider of virtualization and cloud computing software, uses KubeArmor to protect its Kubernetes workloads.
Rancher Labs: Rancher Labs, a provider of open-source software for managing Kubernetes and container-based applications, uses KubeArmor to secure its Kubernetes deployments.

**Comment by nyrahul** [comment]
> VMware: VMware, a leading provider of virtualization and cloud computing software, uses KubeArmor to protect its Kubernetes workloads. Rancher Labs: Rancher Labs, a provider of open-source software for managing Kubernetes and container-based applications, uses KubeArmor to secure its Kubernetes deployments.

Hey @Amishakumari544 , is there any github ID that we can tag from VMWare and Rancher who can attest to these statements?

**Comment by nyrahul** [comment]
I like the format in this [ADOPTERS.md from k8up](https://github.com/k8up-io/k8up/blob/master/ADOPTERS.md).
