### ISSUE TITLE
Mirantis K8s engine support

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#1181]
## Feature Request

**Short Description**

Supporting [k8s cluster solution from Mirantis](https://www.mirantis.com/download/mirantis-cloud-native-platform/mirantis-kubernetes-engine/).

**Describe the solution you'd like**

- [ ] Check if policy enforcement, observability, audit rules, network segmentation is supported
- [ ] Get output of `karmor probe`
- [ ] Update [kubearmor support matrix](https://github.com/kubearmor/KubeArmor/blob/main/getting-started/support_matrix.md)
- [ ] Provide and attach `karmor sysdump`

**Comment by AshokAccuknox** [comment]
KubeArmor is Supporting Mirantis Kubernetes Engine (MKE). 

I have tested with MKE running in Bare metal environment. KubeArmor policies are enforced. Please check this document -[ here](https://accu-knox.atlassian.net/wiki/spaces/~60ac7b12317edd00717f1a42/pages/171966820/Mirantis+Cluster?atlOrigin=eyJpIjoiNDRkZjQ5ODhkZjVhNGRiZjgwZWM4NDFlNTRjYTBkOGEiLCJwIjoiY29uZmx1ZW5jZS1jaGF0cy1pbnQifQ)

Attaching

- [karmor-sysdump-Sun Mar 26 10_46_23 IST 2023.zip](https://github.com/kubearmor/KubeArmor/files/11070824/karmor-sysdump-Sun.Mar.26.10_46_23.IST.2023.zip)
- [karmor probe.txt](https://github.com/kubearmor/KubeArmor/files/11070829/karmor.probe.txt)

**Comment by AshokAccuknox** [comment]
**Mirantis Kubernetes Engine:** 

Mirantis Kubernetes Engine (formerly Docker Enterprise/UCP) is fully-baked Enterprise Kubernetes for development, testing, and production. It includes the Universal Control Plane webUI for easy management, Mirantis Secure Registry (formerly Docker Trusted Registry) for private container image storage and security scanning, and runs on Mirantis Container Runtime (formerly Docker Engine – Enterprise) — a hardened container runtime with optional FIPS 140-2 encryption and other security and reliability features

![mke-1](https://user-images.githubusercontent.com/86401171/227994587-2bd5bc9b-1984-4869-b080-5a33814630f9.png)


**Mirantis Cluster with 3 Manager and 2 worker nodes:**

This is a trial version _Mirantis Bare Metal Cluster running in AWS using Ubuntu 20.04 Operating System_. 


![mke-2](https://user-images.githubusercontent.com/86401171/227994742-4be5489f-213a-4ea3-b6bd-65e9453588cb.png)


![mke-3](https://user-images.githubusercontent.com/86401171/227994871-3c53085c-e593-4889-8111-2d92cb8ce1aa.png)


**Installing Sample wordpress-mysql application:** 


_Installed Sample Wordpress-Mysql Application using the following command:_

```sh 
kubectl apply -f https://raw.githubusercontent.com/kubearmor/KubeArmor/main/examples/wordpress-mysql/wordpress-mysql-deployment.yaml
```
![mke-4](https://user-images.githubusercontent.com/86401171/227995332-a679f184-dc81-48f3-9502-c981aeb3270e.png)




**Installing KubeArmor in MKE:**

Installed KubeArmor in the Mirantis Kubernetes Engine with following Commands: 

```sh 
curl -sfL http://get.kubearmor.io/ | sudo sh -s -- -b /usr/local/bin
karmor install
```
![mke-5](https://user-images.githubusercontent.com/86401171/227995626-c4b74faf-95e1-471a-8d77-736e80e2b599.png)



![mke-6](https://user-images.githubusercontent.com/86401171/227995655-bb429060-4eda-4515-a86f-a7c21431b3bd.png)


**Applying KubeArmor Policy:**

**Audit policy for mysql:** 

The following policy audits the access to the var/lib/mysql folder. 
```sh
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-mysql-audit-dir
  namespace: wordpress-mysql
spec:
  severity: 5
  selector:
    matchLabels:
      app: mysql
  file:
    matchDirectories:
      - dir: /var/lib/mysql/
        recursive: true
  action: Audit 
```

**After applying Policy:**

After Applying Policy we can get audit logs related to file or folder access by someone. 


![mke-7](https://user-images.githubusercontent.com/86401171/227995863-6f4b6217-85c3-470c-8f98-4154bbdac154.png)

**Logs:**


![mke-8](https://user-images.githubusercontent.com/86401171/227995897-06eab859-8b44-4124-8c59-5f46dab7433c.png)



**WordPress Config.php file block policy:** 

**Before Applying Policy:** 


![mke-9](https://user-images.githubusercontent.com/86401171/227995972-aa4db148-4d9e-40f3-b976-4711041875bf.png)

**Applying KubeArmor policy to block access to wp-config file:** 

The following policy denies access to wp-config.php file. 
```sh
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-wordpress-block-config
  namespace: wordpress-mysql
spec:
  severity: 10
  selector:
    matchLabels:
      app: wordpress
  file:
    matchPaths:
      - path: /var/www/html/wp-config.php
        fromSource:
          - path: /bin/cat
  action: Block
```
**After applying Policy:** 

After Applying KubeArmor policy wp-config.php file cannot be accessed. 

![mke-10](https://user-images.githubusercontent.com/86401171/227996132-9b920a92-b597-40f4-9cca-837c0067e184.png)


**Logs:**

![mke-11](https://user-images.githubusercontent.com/86401171/227996183-6715f933-bc8d-40fb-aeb6-d1d6038711d0.png)

**Comment by Ankurk99** [comment]
Hey @AshokAccuknox the screenshots you sent doesn't contain the corresponding logs (PolicyName is shown as DefaultPosture instead of the actual name). Do we have more logs for the same policy rule violation containing the policy name?
