### ISSUE TITLE
Error: rpc error: code = Unknown desc = no pods matching the input request

### ISSUE THREAD

**Issue by zhy76** [kubearmor/KubeArmor#1184]
## Bug Report

**General Information**
```shell
root@kindling-master01:/home/lz/myCode/kubearmor-client# ./karmor summary -p nginx
local port to be used for port forwarding discovery-engine-746fccb855-fmxw6: 32813 
Error: rpc error: code = Unknown desc = no system summary info present for the requested pod name
```

- Environment description (GKE, VM-Kubeadm, vagrant-dev-env, minikube, microk8s, ...)
```shell
kind
```
- Kernel version (run `uname -a`) 
```shell
Linux kindling-master01 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
- Orchestration system version in use (e.g. `kubectl version`, ...)
```shell
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-18T02:16:17Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-25T19:35:11Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}

```
- Link to relevant artifacts (policies, deployments scripts, ...)
- Target containers/pods

**To Reproduce**
follows: https://github.com/kubearmor/KubeArmor/blob/main/getting-started/workload_visibility.md#how-to-get-the-application-behavior

Install KubeArmor
curl -sfL http://get.kubearmor.io/ | sudo sh -s -- -b /usr/local/bin && karmor install
Install [Discovery-engine](https://github.com/kubearmor/discovery-engine)
kubectl apply -f https://raw.githubusercontent.com/kubearmor/discovery-engine/dev/deployments/k8s/deployment.yaml
Next you install the workload. If the workload is already installed, then the behavior will be shown based on the new system events only.
Get the application summary
karmor summary -n NAMESPACE

**Expected behavior**

A description of what you expected to happen.

**Screenshots**
![image](https://user-images.githubusercontent.com/56665618/227775817-619ad5a8-729d-47fe-886f-0685f4800c12.png)
![image](https://user-images.githubusercontent.com/56665618/227785148-752a4371-5929-408f-9d7d-bd8b16d30266.png)
![image](https://user-images.githubusercontent.com/56665618/227777198-0de5cf2f-aa75-4d54-94d2-22d3c94b887a.png)
![image](https://user-images.githubusercontent.com/56665618/227785246-c5c18855-1dba-4c8a-b7f0-c80ec0f579d2.png)

**Comment by xiao-jay** [comment]
Could you please tell me how to install nginx pod @zhy76

**Comment by zhy76** [comment]
> Could you please tell me how to install nginx pod @zhy76
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
```

**Comment by Ankurk99** [comment]
We are aware about KubeArmor not working on Kind and already have an issue for adding kind support: https://github.com/kubearmor/KubeArmor/issues/903

**Comment by zhy76** [comment]
> We are aware about KubeArmor not working on Kind and already have an issue for adding kind support: #903

Thanks for pointing that out！

**Comment by Ankurk99** [comment]
Closing this issue as duplicate. Please include any additional details in the original issue itself.
