### ISSUE TITLE
Unable to run Kubearmor in developement mode

### ISSUE THREAD

**Issue by Rexbeast2** [kubearmor/KubeArmor#1185]
## Bug Report

 error in brief

```
go: github.com/kubearmor/KubeArmor/deployments@v0.0.0-00010101000000-000000000000 requires
	github.com/kubearmor/KubeArmor/KubeArmor@v0.0.0-20221130063629-a2dd0301b858: parsing ../go.mod: open /home/ss/KubeArmor/go.mod: no such file or directory
go: github.com/kubearmor/KubeArmor/deployments@v0.0.0-00010101000000-000000000000 requires
	github.com/kubearmor/KubeArmor/KubeArmor@v0.0.0-20221130063629-a2dd0301b858: parsing ../go.mod: open /home/ss/KubeArmor/go.mod: no such file or directory
make: govvv: Command not found
cd /home/ss/KubeArmor/KubeArmor; make -C ../protobuf
make[1]: Entering directory '/home/ss/KubeArmor/protobuf'
make[1]: Nothing to be done for 'build'.
make[1]: Leaving directory '/home/ss/KubeArmor/protobuf'
cd /home/ss/KubeArmor/KubeArmor; go mod tidy
go: github.com/kubearmor/KubeArmor/deployments@v0.0.0-00010101000000-000000000000 requires
	github.com/kubearmor/KubeArmor/KubeArmor@v0.0.0-20221130063629-a2dd0301b858: parsing ../go.mod: open /home/ss/KubeArmor/go.mod: no such file or directory
make: *** [Makefile:24: build] Error 1

```

**General Information**

- Environment description -minikube version: `v1.29.0`
- Kernel version: `Linux ss 5.15.0-69-generic #76~20.04.1-Ubuntu SMP Mon Mar 20 15:54:06 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux`
- Orchestration system version in use: 
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:51:25Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/arm64"}
WARNING: version difference between client (1.23) and server (1.26) exceeds the supported minor version skew of +/-1

```

**To Reproduce**

1. Instruction 1
run command:  `$ cd KubeArmor/KubeArmor
~/KubeArmor/KubeArmor$ make run`

**Expected behavior**

KubeArmor should start running locally.

**Screenshots**

![Screenshot 2023-03-26 at 8 43 01 PM](https://user-images.githubusercontent.com/78963782/227785258-c4ae83bc-a290-4728-8af5-30a3ae56d15d.png)

**Comment by zhy76** [comment]
Seems like can't find go.mod?

**Comment by xiao-jay** [comment]
I think your go have some error，How did you install go? And please exec `go env` to get more infomation . I suggestion delete the old go. and exec `apt install golang`to install go.
I am very puzzled why the phase fails `github.com/kubearmor/KubeArmor/KubeArmor@v0.0.0-20221130063629-a2dd0301b858: parsing ../go.mod: open /home/ss/KubeArmor/go.mod: no such file or directory`

**Comment by DelusionalOptimist** [comment]
@Rexbeast2 have you been able to build KubeArmor after fixing your go env?

**Comment by DelusionalOptimist** [comment]
@Rexbeast2 closing this for now. Feel free to send a message on slack if you need help.
