### ISSUE TITLE
Test KubeArmor on Amazon Linux 2023

### ISSUE THREAD

**Issue by Ankurk99** [kubearmor/KubeArmor#1194]
## Feature Request

**Check the KubeArmor support on [Amazon Linux 2023](https://aws.amazon.com/linux/amazon-linux-2023/)**

Install KubeArmor on Amazon Linux 2023 and :

- [ ] Check if policy enforcement, observability, audit rules, network segmentation is supported
- [ ] Get output of `karmor probe`
- [ ] Update [kubearmor support matrix](https://github.com/kubearmor/KubeArmor/blob/main/getting-started/support_matrix.md)
- [ ] Provide and attach `karmor sysdump`

Also get Kernel information details.

**Comment by PrathyushaModala** [comment]
@Ankurk99 Can I work on this??

**Comment by Ankurk99** [comment]
@PrathyushaModala you already have an issue assigned https://github.com/kubearmor/KubeArmor/issues/846, can you please finish that first?

**Comment by PrathyushaModala** [comment]
I actually have knowledge of AWS that's why I'm curious to work on it. Please assign :)

**Comment by PrathyushaModala** [comment]
I actually have knowledge of AWS that's why I'm curious to work on it please assign :)

**Comment by Ankurk99** [comment]
Sorry @PrathyushaModala, this was a priority item so we handled it ourselves.

**Comment by PrathyushaModala** [comment]
No problem!!
