### ISSUE TITLE
Doc: Update KubeArmor Zoom link

### ISSUE THREAD

**Issue by Ankurk99** [kubearmor/KubeArmor#1240]
**Update KubeArmor Zoom link**

We have a new KubeArmor zoom link: http://zoom.kubearmor.io We need to update this in the README and create a new Google Calendar invite (and the ICS file) for the same.

**Comment by akashsawan1** [comment]
hey @Ankurk99 this will be a good start for me to contribute to KubeArmor.
Please assign this to me.

**Comment by akashsawan1** [comment]
I sincerely apologize for submitting multiple pull requests. The previous two pull requests did not pass the DCO test.

**Comment by Ankurk99** [comment]
No, worries.
Tip: You can sign older commits without creating a new PR :)

**Comment by akashsawan1** [comment]
Thank you , I will definitely keep that in mind.
