### ISSUE TITLE
Is installation by helm supported ?

### ISSUE THREAD

**Issue by cloud-66** [kubearmor/KubeArmor#1249]
## Bug Report
helm chart doesn't contain 
`Policy Manager Deployment`
`Host Policy Manager Deployment `
etc
there is no instruction installin by helm on site

**General Information**
I know nowdays there is popular to install by downloaded binary or sh script.
is helm chart installation method being supported ?

**Expected behavior**
install by helm chart

**Comment by kranurag7** [comment]
> is helm chart installation method being supported ?

No, It's not supported as of now. The recommended method of installation for getting started is `karmor install` 

Having said that, there was a discussion of adding helm support in one of the community meetings.

**Comment by nyrahul** [comment]
Yes, we discussed on making helm a first class citizen that involves handling following tasks:
1. fixing helm charts to deploy all required components
2. ensuring we have enough tests in GH actions to validate the helm support such that a future PR does not unknowningly break it.
