### ISSUE TITLE
Default Posture logs are getting shown up after block policy application

### ISSUE THREAD

**Issue by AshokAccuknox** [kubearmor/KubeArmor#1250]
## Bug Report
When I apply the following Vault Policy in my AKS cluster I am getting this default posture logs 
```sh
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-vault-protect
  namespace: default
spec:
  severity: 7
  selector:
    matchLabels:
      app.kubernetes.io/name: vault
      component: server
  file:
    matchDirectories:
    - dir: /vault/
      recursive: true
      action: Block
    - dir: /
      recursive: true
    - dir: /vault/
      recursive: true
      fromSource:
      - path: /bin/vault
  process:
    matchPaths:
    - path: /bin/busybox
    - path: /bin/vault
  action: Allow
  message: 'Vault Hardening Policy '
```

I am getting this default posture logs : 

```sh 
Action:Audit
ClusterName:azure-demo-cluster
ContainerID:d9c9959dcba6bc67d5124bc12eacd15cc617187716be17a9fee44682eef71878
ContainerImage:docker.io/hashicorp/vault:1.13.1@sha256:b888abc3fc0529550d4a6c87884419e86b8cb736fe556e3e717a6bc50888b3b8
ContainerName:vault
Data:syscall=SYS_OPENAT fd=-100 flags=O_RDONLY
Enforcer:eBPF Monitor
HostName:aks-agentpool-36168086-vmss000003
HostPID:2866379
HostPPID:2845784
Labels:component=server,helm.sh/chart=vault-0.24.1,statefulset.kubernetes.io/pod-name=vault-0,app.kubernetes.io/instance=vault,app.kubernetes.io/name=vault
NamespaceName:default
Operation:File
PID:1774
PPID:2845784
ParentProcessName:/usr/bin/containerd-shim-runc-v2
PodName:vault-0
PolicyName:DefaultPosture
ProcessName:/bin/vault
Resource:/sys/kernel/mm/transparent_hugepage/hpage_pmd_size
Result:Passed
Source:/bin/vault status -tls-skip-verify
Timestamp:1685458455
Type:MatchedPolicy
UID:100
UpdatedTime:2023-05-30T14:54:15.873859Z
cluster_id:369
component_name:kubearmor
instanceGroup:0
instanceID:0
tenant_id:11
```

**Comment by daemon1024** [comment]
Since we allow all files in the general, we shouldn't have received these default posture audit events. 

We have some issues with our policy matcher here ig.

**Comment by akhyaradn** [comment]
hi, can i help with this issue? what is the expected behaviour? btw i'm still new in this project, trying to make my first contribution!

**Comment by akhyaradn** [comment]
hi, can i help with this issue? what is the expected behavior? btw i'm still new to this project, trying to make my first contribution!

**Comment by Ankurk99** [comment]
Hey @akhyaradn, glad to see your interest. 
Here in the above policy, we have:
```
    - dir: /
      recursive: true
```
thus recursively allowing access to the `/` dir. But we are getting `Audit` based alerts from the KubeArmor, means it's detecting an unexpected access, which shouldn't be the case.

But we need to first reproduce the issue. As this issue is concerned with some fundamental KubeArmor functionalilty, I wouldn't recommend it to be a good-first-issue. Instead you can try out other issues marked with the good-first-issue tag. 
But if you still want to take a look at it, we will be glad to help.
