### ISSUE TITLE
feat(deployment): Change deployment mode to Helm charts 

### ISSUE THREAD

**Issue by DelusionalOptimist** [kubearmor/KubeArmor#1256]
## Feature Request

Use Helm charts for deploying KubeArmor and other related resources.
Roadmap:
Done (v0.10):
- [x] Update KubeArmor charts and deprecate old controllers - https://github.com/kubearmor/KubeArmor/pull/1253
- [x] Publish KubeArmor and Operator Helm charts - Workflow added in https://github.com/kubearmor/KubeArmor/pull/1253

In progress (v0.11):
- [x] Add KubeArmor operator - https://github.com/kubearmor/KubeArmor/pull/1246
- [x] Create Helm chart for operator - https://github.com/kubearmor/KubeArmor/pull/1246
- [x] Update CI to install Operator helm charts instead of KubeArmor helm charts - https://github.com/kubearmor/KubeArmor/pull/1246

Future (v0.12):
- [x] Update kubearmor-client to use Operator Helm charts for installation
- [ ] Update KubeArmorOperator to use ~~KubeArmor Helm charts~~ lifecycle operator for KubeArmor installation
- [x] Add README.md for helm-operator deployment
- [x] All the tests should use helm operator deployment (currently handled only for ginkgo tests)

**Comment by DelusionalOptimist** [comment]
cc @rksharma95

**Comment by rootxrishabh** [comment]
Hey @daemon1024 @DelusionalOptimist I would like to work on this : )

**Comment by rootxrishabh** [comment]
@DelusionalOptimist Currently karmor is installing though kubearmor controller getting all resource from [objects.go](https://github.com/kubearmor/KubeArmor/blob/main/deployments/get/objects.go), goal here is to integrate helm into karmor and install via operator. Please correct If I am wrong.

**Comment by DelusionalOptimist** [comment]
@rootxrishabh Yes, your understanding is correct. Just that right now the controller doesn't install kubearmor, karmor itself creates all these K8s objects using client-go.
And yes, we want to change this approach and use helm client in karmor to install the kubearmor operator's helm chart - https://github.com/kubearmor/KubeArmor/tree/main/deployments/helm/KubeArmorOperator

**Comment by DelusionalOptimist** [comment]
kubearmor-client now uses operator helm chart - https://github.com/kubearmor/kubearmor-client/pull/402.
Old installation is still present under the `--legacy` flag.

**Comment by DelusionalOptimist** [comment]
All tasks handled. Good to close!
Thanks @rksharma95 @rootxrishabh! :rocket:
