### ISSUE TITLE
Blank Document Displayed for " Protecting Unorchestrated Containerized Workloads" in KubeArmor Wiki

### ISSUE THREAD

**Issue by Aryan-sharma11** [kubearmor/KubeArmor#1272]
## Bug Report
Upon clicking the document link, a blank page is displayed, providing no content or information whatsoever. [Deploying KubeArmor to protect un orchestrated containerized workloads](https://github.com/kubearmor/KubeArmor/wiki/Deploying-KubeArmor-to-protect-un-orchestrated-containerized-workloads)
### Expected Result:
The document should display relevant information and guidelines for deploying KubeArmor to protect unorchestrated containerized workloads.

**Comment by nyrahul** [comment]
Removed the corresponding topic and replaced with other documentation. Currently the document for "Protecting unorchestrated containerized workloads" is not upto the point hence decided to replace the topic.
