### ISSUE TITLE
karmor summary info display is out of order 

### ISSUE THREAD

**Issue by zhy76** [kubearmor/KubeArmor#1276]
## Bug Report

**General Information**

- Environment description (GKE, VM-Kubeadm, vagrant-dev-env, minikube, microk8s, ...)
- Kernel version (run `uname -a`)
- Orchestration system version in use (e.g. `kubectl version`, ...)
- Link to relevant artifacts (policies, deployments scripts, ...)
- Target containers/pods

**To Reproduce**
use karmor summary
1. Instruction 1
2. Instruction 2

**Expected behavior**

A description of what you expected to happen.
karmor summary information is displayed in normal order

**Screenshots**

karmor summary info display is out of order, eg. labels should be: “app=wordpress” not “wordpress“，“Namespace Name” should be “wordpress-mysql” not “app=wordpress”
![image](https://github.com/kubearmor/KubeArmor/assets/56665618/9567b91e-45ca-4005-a92c-6acf45defd86)

**Comment by Aryan-sharma11** [comment]
@zhy76  Hey,  the issue was with the discovery engine protobuffs which has been handled. For ref see [324](https://github.com/kubearmor/kubearmor-client/issues/324) and [this](https://github.com/accuknox/discovery-engine/pull/737)

**Comment by Ankurk99** [comment]
Closing as resolved
