### ISSUE TITLE
Versioned Release for kubearmor-relay and kubearmor-controller

### ISSUE THREAD

**Issue by rksharma95** [kubearmor/KubeArmor#1291]
## Feature Request

At this point we don't have versioned release (v*) workflow for [kubearmor-relay](https://github.com/kubearmor/kubearmor-relay-server) and [KubeArmorController](https://github.com/kubearmor/KubeArmor/tree/main/pkg/KubeArmorController).

```[tasklist]
### Tasks
- [ ] https://github.com/kubearmor/kubearmor-relay-server/issues/32
- [ ] https://github.com/kubearmor/KubeArmor/pull/1322
```

**Comment by kranurag7** [comment]
@rksharma95 I would love to handle this.

**Comment by rksharma95** [comment]
Thanks, @kranurag7, for your interest in working on this priority issue! let me know if you would be able to work on it on a priority basis.
