### ISSUE TITLE
KubeArmor on RedHat Ecosystem Issue Tracker

### ISSUE THREAD

**Issue by rksharma95** [kubearmor/KubeArmor#1294]
This issue thread is a tracker for all these pending work items related to KubeArmor Integration on RedHat Ecosystem.

```[tasklist]
### Tasks
- [ ] #1200
- [ ] #1201
```

**Comment by nyrahul** [comment]
Please split up the UBI related changes from #1200 and lets target merging the base operator first.

**Comment by ShubhamTatvamasi** [comment]
Will be done after the v1.0.0 release.

**Comment by ShubhamTatvamasi** [comment]
Use v1.0.1 for release

**Comment by ShubhamTatvamasi** [comment]
PR: https://github.com/kubearmor/KubeArmor/pull/1439
