### ISSUE TITLE
Not showing logs for `mkdir` operation for hardening policy and write-block policy not blocking `touch` actions.

### ISSUE THREAD

**Issue by PriyaAccuknox** [kubearmor/KubeArmor#1302]
Bug1: The given "harden-wordpress-write-in-shm-dir" policy not blocking the write action inside the directory  /dev/shm/::
```sh 
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: harden-mysql-write-in-shm-dir
  namespace: wordpress-mysql
spec:
  action: Block
  file:
    matchDirectories:
    - dir: /dev/shm/
      readOnly: true
      recursive: true
  message: Alert! write to /dev/shm folder prevented.
  selector:
    matchLabels:
      app: mysql
  severity: 5
  tags:
  - MITRE_execution
  - MITRE
```
```sh
(priyashan-390305)$ kubectl exec -it wordpress-fb448db97-gmvw8 -n wordpress-mysql -- bash
root@wordpress-fb448db97-gmvw8:/var/www/html# cd /dev/shm
root@wordpress-fb448db97-gmvw8:/dev/shm# ls
file123  folder1
root@wordpress-fb448db97-gmvw8:/dev/shm# touch priya
root@wordpress-fb448db97-gmvw8:/dev/shm# ls
file123  folder1  priya
root@wordpress-fb448db97-gmvw8:/dev/shm# 
```
Bug 2: Not Alerting for "mkdir" action on karmor logs for all hardening policy.
```sh
root@wordpress-fb448db97-gmvw8:/etc# mkdir dir1 
mkdir: cannot create directory 'dir1': Permission denied
root@wordpress-fb448db97-gmvw8:/etc# mkdir dir2
mkdir: cannot create directory 'dir2': Permission denied
root@wordpress-fb448db97-gmvw8:/etc# touch file5
touch: cannot touch 'file5': Permission denied
root@wordpress-fb448db97-gmvw8:/etc# 
```
The below is karmor logs that I have received.
```sh
asfamalti@cloudshell:~ (third-nature-389009)$ karmor logs
local port to be used for port forwarding kubearmor-relay-6bc49fc67d-rlh89: 32867 
Created a gRPC client (localhost:32867)
Checked the liveness of the gRPC server
Started to watch alerts
== Alert / 2023-07-05 02:59:36.366086 ==
ClusterName: default
HostName: gke-cluster-1-default-pool-8863b833-rwzw
NamespaceName: wordpress-mysql
PodName: wordpress-fb448db97-gmvw8
Labels: app=wordpress
ContainerName: wordpress
ContainerID: e82f1767f5739ad7e906ede0911f317142da813b40e417da88f9d55b6d7881b7
ContainerImage: docker.io/library/wordpress:4.8-apache@sha256:6216f64ab88fc51d311e38c7f69ca3f9aaba621492b4f1fa93ddf63093768845
Type: MatchedPolicy
PolicyName: harden-wordpress-write-etc-dir
Severity: 5
Message: Alert! File creation under /etc/ directory detected.
Source: /usr/bin/touch file5
Resource: /etc/file5
Operation: File
Action: Block
Data: syscall=SYS_OPEN flags=O_WRONLY|O_CREAT|O_NOCTTY|O_NONBLOCK
Enforcer: BPFLSM
Result: Permission denied
ATags: [NIST_800-53_SI-7 NIST NIST_800-53_SI-4 NIST_800-53 MITRE_T1562.001_disable_or_modify_tools MITRE_T1036.005_match_legitimate_name_or_location MITRE_TA0003_persistence MITRE MITRE_T1036_masquerading MITRE_TA0005_defense_evasion]
HostPID: 770174
HostPPID: 767059
Owner: map[Name:wordpress Namespace:wordpress-mysql Ref:Deployment]
PID: 223
PPID: 207
ParentProcessName: /bin/bash
ProcessName: /bin/touch
Tags: NIST_800-53_SI-7,NIST,NIST_800-53_SI-4,NIST_800-53,MITRE_T1562.001_disable_or_modify_tools,MITRE_T1036.005_match_legitimate_name_or_location,MITRE_TA0003_persistence,MITRE,MITRE_T1036_masquerading,MITRE_TA0005_defense_evasion
```

**Comment by Ankurk99** [comment]
I was able to do enforcement with AppArmor but the alerts generated were shown from DefaultPosture, so there seems to be some issue with the PolicyMatcher.

Here in the below alert we are getting the `Resource` to be `/shm/b` though the actual path is `/dev/shm/b`
Ref alert:
```
== Alert / 2023-07-05 14:34:07.713815 ==
ClusterName: default
HostName: knownymous
NamespaceName: default
PodName: nginx-6c8b5bd58d-t7hrc
Labels: app=nginx
ContainerName: nginx
ContainerID: 8140701e549e68c96eedd7285cf7b10fbd813af0673e244ddc5d9a3340274f6c
ContainerImage: docker.io/library/nginx:latest@sha256:08bc36ad52474e528cc1ea3426b5e3f4bad8a130318e3140d6cfe29c8892c7ef
Type: MatchedPolicy
PolicyName: DefaultPosture
Source: /usr/bin/touch b
Resource: /shm/b
Operation: File
Action: Block
Data: syscall=SYS_OPENAT fd=-100 flags=O_WRONLY|O_CREAT|O_NOCTTY|O_NONBLOCK
Enforcer: AppArmor
Result: Permission denied
HostPID: 145970
HostPPID: 145633
Owner: map[Name:nginx Namespace:default Ref:Deployment]
PID: 59
PPID: 50
ParentProcessName: /usr/bin/dash
ProcessName: /usr/bin/touch
```

**Comment by PriyaAccuknox** [comment]
In K3S Apparmor enforcer is used and this  'harden-wordpress-write-in-shm-dir' is blocking the Action. In GKE alone not working so It might be the LSM Issue.  Please find the Below attached.
  @nyrahul  `master@gurumaster:~$ kubectl exec -it  wordpress-fb448db97-4zsbr -n wordpress-mysql  -- bash
root@wordpress-fb448db97-4zsbr:/var/www/html#
root@wordpress-fb448db97-4zsbr:/var/www/html#
root@wordpress-fb448db97-4zsbr:/var/www/html# cd /dev/shm/
root@wordpress-fb448db97-4zsbr:/dev/shm# ls
ehef
root@wordpress-fb448db97-4zsbr:/dev/shm# touch test1
touch: cannot touch 'test1': Permission denied
root@wordpress-fb448db97-4zsbr:/dev/shm#
[4:48](https://accuknox.slack.com/archives/D0575NCK0RK/p1690283886018259)
== Alert / 2023-07-25 11:15:08.269078 ==
ClusterName: default
HostName: gurumaster
NamespaceName: wordpress-mysql
PodName: wordpress-fb448db97-4zsbr
Labels: app=wordpress
ContainerName: wordpress
ContainerID: 1e4d5b3a9de871783aa7eb23001fa34e19dac37491e0fdc652c0a22b1cfcb05f
ContainerImage: [docker.io/library/wordpress:4.8-apache@sha256:6216f64ab88fc51d311e38c7f69ca3f9aaba621492b4f1fa93ddf63093768845](http://docker.io/library/wordpress:4.8-apache@sha256:6216f64ab88fc51d311e38c7f69ca3f9aaba621492b4f1fa93ddf63093768845)
Type: MatchedPolicy
PolicyName: DefaultPosture
Source: /usr/bin/touch test1
Resource: /shm/test1
Operation: File
Action: Block
Data: syscall=SYS_OPEN flags=O_WRONLY|O_CREAT|O_NOCTTY|O_NONBLOCK
Enforcer: eBPF Monitor
Result: Permission denied
HostPID: 38409
HostPPID: 38155
Owner: map[Name:wordpress Namespace:wordpress-mysql Ref:Deployment]
PID: 224
PPID: 217
ParentProcessName: /bin/bash
ProcessName: /bin/touch
releasing grpc client`
