### ISSUE TITLE
KubeArmor Unorchestrated Config Watcher

### ISSUE THREAD

**Issue by daemon1024** [kubearmor/KubeArmor#1303]
## Feature Request

**Short Description**

KubeArmor should update DefaultPosture and Visibility with unorchestrated workloads based on changes in the config file like it updates them with configmap in k8s.

**Is your feature request related to a problem? Please describe the use case.**

No way to change defaultposture or visibility without restarting KubeArmor when in systemd mode

**Describe the solution you'd like**

Leverage viper.ConfigWatcher -https://github.com/spf13/viper#watching-and-re-reading-config-files

**Comment by jingchu000** [comment]
hey @daemon1024 . Could you pls assign it to me?

**Comment by jingchu000** [comment]
@daemon1024 ，I am a newcomer. May I ask if my PR meets the requirements? If it doesn't meet the requirements, can you tell me what to do?

**Comment by jingchu000** [comment]
@daemon1024
