### ISSUE TITLE
handle policy addition and deletion in systemd mode.

### ISSUE THREAD

**Issue by Prateeknandle** [kubearmor/KubeArmor#1312]
## Bug Report
1. When we add an already apllied policy to a workload, we still get a `SUCCESS` message, rather it should say something like, `Policy already applied`.
2. Same issue with deletion of the policy, once it is being removed, and then we try to delete it again we still get `SUCCESS` message, rather it should say `Policy doesn't exist`

**To Reproduce**

1. using `karmor vm policy add` apply a policy twice, and you'll see `SUCCESS` both the times.
2. using `karmor vm policy delete` delete an applied policy twice, and you'll see `SUCCESS` both the times.

**Solution**
To handle this we should use grpc endpoint which keeps track on applied policies.

**Comment by daemon1024** [comment]
Reopening till https://github.com/kubearmor/kubearmor-client/pull/363 is merged
