### ISSUE TITLE
getting alert by email and other ways

### ISSUE THREAD

**Issue by cloud-66** [kubearmor/KubeArmor#1323]
## Feature Request

**Short Description**

there should be the way to get alert by email and other way (slack,telegram etcd)

**Is your feature request related to a problem? Please describe the use case.**
How to know about suspicious behavior ?

**Describe the solution you'd like**

I want to get email after some actions blocked or been audited

**Describe alternatives you've considered**

falco has different ways to do alert like program output. which may run program send email or curl webhook for posting to slack.

Maybe i missed , How to send alert about kubearmor security event ?

**Comment by cloud-66** [comment]
One of example is falcosidekick, which forward falco events to different outputs and you can do everything with them. How can i operate with kubearmor events ?

**Comment by Shreyas220** [comment]
Hey @cloud-66 thanks for raising this request. this is on our roadmap and we have already started working on sending events to falco sidekick. 
this feature will be out soon

**Comment by nyrahul** [comment]
KubeArmor now support [sidekick](https://github.com/kubearmor/sidekick) as well!
