### ISSUE TITLE
feat: add more columns for ksp 

### ISSUE THREAD

**Issue by kranurag7** [kubearmor/KubeArmor#1326]
## Feature Request

**Short Description**

As of now, when one invokes `kubectl get ksp`, our print columns are the default ones that ship with kubebuilder. 
```bash
$ kubectl get ksp -A 
NAMESPACE     NAME                           AGE
multiubuntu   ksp-ubuntu-1-file-path-block   7m44s
```
I think we can update this to include more columns here. Initially, I'm thinking of adding `spec.action` and `spec.severity`. I'll really appreciate more suggestion/feedback on this.

**Is your feature request related to a problem? Please describe the use case.**

I want to have more information when I invoke `kubectl get ksp` As of now, I've to do `kubectl get ksp <policy-name> -oyaml` 

**Describe the solution you'd like**

Since our new controller is written using kubebuilder we can leverage this.  
https://book.kubebuilder.io/reference/generating-crd.html#additional-printer-columns

**Describe alternatives you've considered**

N/A

**Comment by DelusionalOptimist** [comment]
Hey @kranurag7! Great idea. Having these fields would be nice. However, we have per rule based action and severity as well. The [policy specification doc](https://github.com/kubearmor/KubeArmor/blob/main/getting-started/security_policy_specification.md#policy-specification) needs to be updated I think. Ref - [Per rule actions](https://github.com/kubearmor/KubeArmor/blob/7ab3a56cfd76e23e7059410a39f169da29c333ed/deployments/CRD/KubeArmorPolicy.yaml#L51-L56) and [Per rule severity](https://github.com/kubearmor/KubeArmor/blob/7ab3a56cfd76e23e7059410a39f169da29c333ed/deployments/CRD/KubeArmorPolicy.yaml#L93-L96)

So, if we just provide the top level properties, it might be misleading for the user. Any good way to handle this? :thinking: 

Also, @daemon1024 proposed if we could possibly also add to this information about which deployments the policy is enforcing on. However, I'm not sure how would that happen and where would we map deployments with policies :eyes:

**Comment by sratslla** [comment]
I would like to work on this issue.
