### ISSUE TITLE
Modify FalcoSidekick to export kubearmor events 

### ISSUE THREAD

**Issue by Shreyas220** [kubearmor/KubeArmor#1328]
## Feature Request

**Short Description**
we need a way to export kubearmor events to different outputs (example: email,slack,redis,rabbitmq,kafka etc.)

**Describe the solution you'd like**
Modify falcosidekick to connect to relay server and export events.

- [x] Modify event consumer code
- [x] Helm
- [x] Tests
- [ ] Documentation

**Comment by daemon1024** [comment]
TODO: Publish helm charts

**Comment by Shreyas220** [comment]
1-> https://github.com/kubearmor/sidekick/pull/1
2 -> https://github.com/kubearmor/sidekick/pull/2
3 -> https://github.com/kubearmor/sidekick/pull/3
