### ISSUE TITLE
Least Permissive Access  rule  for each container in pod

### ISSUE THREAD

**Issue by cloud-66** [kubearmor/KubeArmor#1336]
## Feature Request

**Short Description**

KubeArmor could support different rule for each container in pod

**Is your feature request related to a problem? Please describe the use case.**

I use initContainer with privileged access to do some work before starting main container. Now i should create rule for whole pod with some privileged acesses, but main container mustn't have access to do it

**Describe the solution you'd like**

different rule for each container\initContainer in pod

**Comment by cloud-66** [comment]
I found in this blog post https://www.accuknox.com/blog/kubearmor-v0-7-release that there is Container based policy support. There is no information in documentation about it

**Comment by nyrahul** [comment]
* [This wiki page](https://github.com/kubearmor/KubeArmor/wiki/v0.7-Release-Blog#container-based-policy-support) about the release blog clarifies the syntax for using container specific policies.
* [This kubearmor automated test](https://github.com/kubearmor/KubeArmor/tree/main/tests/k8s_env/multicontainer) verifies this functionality as part of CI pipeline. Users can look at the sample container based policies for references.
