### ISSUE TITLE
Create PolicyReports for security events to use with Policy Reporter

### ISSUE THREAD

**Issue by cloud-66** [kubearmor/KubeArmor#1337]
## Feature Request

Kubearmor could create Policy Reports 

**Is your feature request related to a problem? Please describe the use case.**

Problem how to handle and action based on security events

**Describe the solution you'd like**

Periodicaly or instantly kubearmor should create policy reports for rules. This reports could be send to different targets
https://kyverno.github.io/policy-reporter/core/targets

**Describe alternatives you've considered**

I think alternative way to handle events is falcosidekick #1323 #1328
there is adapter to create policy reports from kubearmor log https://github.com/haardikdharma10/kubearmor-adapter
Have you any plans to support policy reports, which seems some kind of standart  resource for policy events?

**Comment by daemon1024** [comment]
@cloud-66 This is something exactly we discussed in the last call, and definitely on our roadmap. As you linked, Falco sidekick integrates with Policy Reports, once we handle #1328 we should hopefully work on this next.

Would you like to work towards this? We are actively looking for contributors to help out. 

On a related note, It would be great to know, How are you using KubeArmor? We recently started maintaining [ADOPTERS.md](https://github.com/kubearmor/KubeArmor/blob/main/ADOPTERS.md) and would love to hear your use-cases.

**Comment by cloud-66** [comment]
We are not widely using kubearmor, for now looking which tool we can use to cover our security requirements. Since kubarmor is the only tool that not only audits, but also blocks unwanted behavior in pods, I am looking it closely and would like it to develop successfully.

I am not developing in job position and don't have much experience, but I can try to get familiar with code of kubearmor. For now I don't know where to start implementation. If you have some thoughts I'll try work on it

**Comment by daemon1024** [comment]
Handled in #1328
