### ISSUE TITLE
Improve security clomonitor score

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#1353]
Current status
[![CLOMonitor](https://img.shields.io/endpoint?url=https://clomonitor.io/api/projects/cncf/kubearmor/badge)](https://clomonitor.io/projects/cncf/kubearmor)

```[tasklist]
### [KubeArmor](https://clomonitor.io/projects/cncf/kubearmor#kubearmor)
- [x] [Documentation - Roadmap](https://clomonitor.io/docs/topics/checks/#roadmap)  (thanks @rootxrishabh )
- [x] [License scanning](https://clomonitor.io/docs/topics/checks/#license-scanning)
- [x] [Artifact Hub badge](https://clomonitor.io/docs/topics/checks/#artifact-hub-badge)  (thanks @rootxrishabh )
- [x] [Community meeting](https://clomonitor.io/docs/topics/checks/#community-meeting)
- [x] [OpenSSF Scorecard badge](https://clomonitor.io/docs/topics/checks/#openssf-scorecard-badge)
- [ ] [Binary artifacts](https://clomonitor.io/docs/topics/checks/#binary-artifacts-from-openssf-scorecard)
- [ ] [Software bill of materials (SBOM)](https://clomonitor.io/docs/topics/checks/#software-bill-of-materials-sbom)
- [ ] [Signed releases](https://clomonitor.io/docs/topics/checks/#signed-releases-from-openssf-scorecard)
- [ ] [Token permissions](https://clomonitor.io/docs/topics/checks/#token-permissions-from-openssf-scorecard)
```

```[tasklist]
### [KubeArmor Client](https://clomonitor.io/projects/cncf/kubearmor#kubearmor-client)
- [x] [Contributing](https://clomonitor.io/docs/topics/checks/#contributing) (thanks @vishalrajofficial)
- [ ] [Maintainers](https://clomonitor.io/docs/topics/checks/#maintainers)
```

```[tasklist]
### [Policy Templates](https://clomonitor.io/projects/cncf/kubearmor#policy-templates)
- [x] [Contributing](https://clomonitor.io/docs/topics/checks/#contributing)
- [ ] [Maintainers](https://clomonitor.io/docs/topics/checks/#maintainers)
- [ ] [Contributor License Agreement](https://clomonitor.io/docs/topics/checks/#contributor-license-agreement)
- [x] [Developer Certificate of Origin](https://clomonitor.io/docs/topics/checks/#developer-certificate-of-origin)
```

```[tasklist]
### [kvm-service](https://clomonitor.io/projects/cncf/kubearmor#kvm-service)
- [x] [Contributing](https://clomonitor.io/docs/topics/checks/#contributing)
- [ ] [Maintainers](https://clomonitor.io/docs/topics/checks/#maintainers)
- [x] [Recent release](https://clomonitor.io/docs/topics/checks/#recent-release)
```

```[tasklist]
### [kastore](https://clomonitor.io/projects/cncf/kubearmor#kastore)
- [x] [Contributing](https://clomonitor.io/docs/topics/checks/#contributing)
- [ ] [Maintainers](https://clomonitor.io/docs/topics/checks/#maintainers)
- [ ] [Contributor License Agreement](https://clomonitor.io/docs/topics/checks/#contributor-license-agreement)
- [x] [Developer Certificate of Origin](https://clomonitor.io/docs/topics/checks/#developer-certificate-of-origin)
```

**Comment by h4shk4t** [comment]
Hello @nyrahul, is this a good first issue to start with? I would be interested to work on it if it is.

**Comment by Ankurk99** [comment]
Hey @h4shk4t, yes this should be a good-first-issue. I am assigning the issue to you, if you need any help please ping.

**Comment by vishalrajofficial** [comment]
I am interested in contributing further to this issue. I would greatly appreciate it if you could assign me as well.

**Comment by arsenalzp** [comment]
Hello,
Let me join your team to support with those tasks.

**Comment by vishalrajofficial** [comment]
I have submitted pull requests to the repositories of KubeArmor, policy-templates, and Kastore. In this regard, I humbly request your esteemed review of these contributions.

**Comment by vishalrajofficial** [comment]
@nyrahul Should I create a pull request for License Scanning? I ran a fossa scan, but it was limited and these are the results:

https://app.fossa.com/api/projects/custom%2B39510%2Fgithub.com%2Fkubearmor%2FKubeArmor.svg?type=shield&issueType=license

https://app.fossa.com/projects/custom%2B39510%2Fgithub.com%2Fkubearmor%2FKubeArmor?ref=badge_shield

**Comment by vishalrajofficial** [comment]
@nyrahul Would it be advisable for me to initiate a pull request for License Scanning? I executed a FOSSA scan, although it was constrained, and the outcomes are as follows:

https://app.fossa.com/projects/custom%2B39510%2Fgithub.com%2Fkubearmor%2FKubeArmor?ref=badge_shield

**Comment by yashpimple** [comment]
@nyrahul @Ankurk99  I am interested to contribute towards the projects and would like to get started with the above good first issue in KubeArmor

**Comment by sarthaksarthak9** [comment]
@nyrahul  I think community meeting is already in readme so we mark it as complete in above checkbar

**Comment by vishalrajofficial** [comment]
@Ankurk99 @nyrahul 
I've submitted pull requests to the kvm-service, kastore, and policy templates repositories. I would greatly appreciate it if you could review my contributions and provide suggestions for any necessary upgrades.

**Comment by rootxrishabh** [comment]
[Score is at 83](https://clomonitor.io/projects/cncf/kubearmor#kubearmor_security)

**Comment by swastik959** [comment]
@nyrahul hi I would like to contribute to this issue can you please assign it to me
