### ISSUE TITLE
Events dropped due to busy event channel

### ISSUE THREAD

**Issue by daemon1024** [kubearmor/KubeArmor#1356]
## Bug Report

KubeArmor Pod logs a LOT of 
`2023-08-08 06:40:11.xxxx	WARN	Event droped due to busy event channel`

**To Reproduce**

Trigger a lot of events in KubeArmor repeatedly

**Expected behavior**

It shouldn't be logged, it suggests there's an issue

**Screenshots**
![image](https://github.com/kubearmor/KubeArmor/assets/47106543/90425dd4-bb25-424a-9fa8-392dcaee47ee)

**Comment by daemon1024** [comment]
There's some flaw with the replay logic we have

https://github.com/kubearmor/KubeArmor/blob/46a1e116bcd7dcb43f87e8a3c685e434649f19b9/KubeArmor/monitor/systemMonitor.go#L622

This was introduced back in https://github.com/kubearmor/KubeArmor/pull/1068 to fill up context on events where we might have missed due to delay in information from CRI.

**Comment by h4shk4t** [comment]
I would like to pick up this issue.

**Comment by clemenkok** [comment]
Would like to work on this.

**Comment by nyrahul** [comment]
Folks, we might need a fix on this immediately. It would be better if the KubeArmor maintainer team picks it up.

**Comment by daemon1024** [comment]
These are more apparent on hosts running both generic applications and kubernetes env ( example local k8s setups )
Or on dockerized node environment like kind, minikube.

KubeArmor assosciates each event with either the container or the host based on pid ns and mnt ns.

But there are events out there which don't categorize into either of them but still have a different linux namespace.
Example
- systemd user processes
- flatpaks, snaps, appimages
- dockerised nodes, they are host for the containers but in the kernel space they are actually a container and kubearmor cannot understand that.

KubeArmor cannot assosciate the said event and hence the drops log.

Some performance improvement have prevented the tight loop on replay channel, as well the ebpf prog will not send file data for these events which drastically reduces the number of these logs.

But these will be specially handled based on how we plan to implement #1503
