### ISSUE TITLE
CEF format support

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#1371]
## Feature Request

**Short Description**

Common Event Format (CEF) is a standardized logging format consumed by Security Information and Event Management (SIEM) solutions. CEF is designed to simplify the process of logging security-related events and making it easier to integrate logs from different sources into a single system. CEF is based on the syslog format, which is a standard for message logging that is supported by most network devices and operating systems.

CEF uses a structured data format to log events, which includes a set of predefined fields that contain information about the event. The CEF format consists of two parts: the header and the message. The header contains metadata about the event, such as the timestamp, source IP address, and device hostname. The message contains details about the event, such as the event type, severity level, and any relevant data[^1].

Ref: [KubeArmor Logging Ecosystem](https://github.com/kubearmor/KubeArmor/wiki/KubeArmor-Logging-Ecosysytem)

- [ ] Identify the message field mappings.
- [ ] Identify the mode of integration. It would be best to keep the CEF as a separate adapter, just like OpenTelemetry that consume events from KubeArmor Relay and convert it into CEF format.
- [ ] CEF Adapter implementation[^2]
- [ ] System Tests
- [ ] Documentation

[^1]: https://www.splunk.com/en_us/blog/learn/common-event-format-cef.html
[^2]: https://github.com/kubearmor/KubeArmor/wiki/KubeArmor-Logging-Ecosysytem

**Comment by nyrahul** [comment]
@Shreyas220 , can we call this done as part of sidekick handling?

**Comment by Shreyas220** [comment]
> as part of sidekick handling

Yes, sidekick along with many other outputs will support CEF format to use it we will be require to set the following configurations 
- host - ip address we are sending the events to. In k8s env the syslog server would have a service, you can provide the that here
- Port
- format: it supports 2 format 1)JSON 2)CEF. By default it is JSON please mention cef if you want to use it
- protocol: it supports 2 format 1)TCP 2)UDP

a example looks like this 

```
CEF:0|Accuknox|Kubearmor|1.0|Kubearmor Event|Alert|uid=0 start=2023-08-20T15:43:00Z log=Hostname:aks-agentpool-16326778-vmss000000 NamespaceName:multiubuntu ContainerImage:docker.io/kubearmor/ubuntu-w-utils:0.1@sha256:b4693b003ed1fbf7f5ef2c8b9b3f96fd853c30e1b39549cf98bd772fbd99e260 PolicyName:ksp-group-1-proc-path-block-from-source ATags:[] PodName:ubuntu-1-deployment-565b9f669d-qdtdd HostPID:50299 PID:126 Data:syscall=SYS_EXECVE Message:block /bin/dash executing /bin/ls OwnerName:ubuntu-1-deployment Severity:5 Timestamp:1692546180 HostPPID:50298 PPID:125 ParentProcessName:/bin/dash Enforcer:AppArmor OwnerNamespace:multiubuntu ContainerID:c83070f30d3f3f328f057a032878e9070d1c66accdf4bfc6e6a523e4d77f8751 Resource:/bin/ls Labels:container=ubuntu-1,group=group-1 UID:0 Source:/bin/dash OwnerRef:Deployment UpdatedTime:2023-08-20T15:43:00.523662Z Result:Permission denied ClusterName:default ContainerName:ubuntu-1-container ProcessName:/bin/ls Operation:Process

```

**Comment by daemon1024** [comment]
Handled in #1328
