### ISSUE TITLE
Overwriting of security policies in `opt/kubearmor/policy`

### ISSUE THREAD

**Issue by Aryan-sharma11** [kubearmor/KubeArmor#1387]
## Bug Report

**General Information**

- Environment description :-  Kubearmor in systemd mode 
- Kernel version (run `uname -a`) : NA
- Orchestration system version in use (e.g. `kubectl version`, ...) : NA

**To Reproduce**

1. Instruction 1 : Run kubearmor in sytemd mode and apply policy on a container using `karmor vm policy add <policyname>` 
3. Instruction 2: Change the container name in policy and again apply it. Now if u list/read the policies under /opt/kubearmor/policy the policy applied earlier is now overwritten, while the policy is applied on both the containers.

**Expected behavior**

The policy applied on the previous container should be deleted. This scenario is handled in kubernetes environment but not in unorchestrated mode  .

**Comment by haytok** [comment]
HI, @nyrahul 

Could you assign me to work on this issue?

I think I can work on this bug as I have summarized in [this article](https://haytok.github.io/post/20230904/) the basics of controlling what commands can be run in a particular container by enforcing security with KubeArmor running in systemd mode.

**Comment by nyrahul** [comment]
> HI, @nyrahul
> 
> Could you assign me to work on this issue?
> 
> I think I can work on this bug as I have summarized in [this article](https://haytok.github.io/post/20230904/) the basics of controlling what commands can be run in a particular container by enforcing security with KubeArmor running in systemd mode.

Great to see the article you wrote. There has been some discussion on this issue and @Aryan-sharma11 will update the issue details.

**Comment by haytok** [comment]
Hi, @Aryan-sharma11 @nyrahul

Thanks for comments !!!
I have a question about the expected behavior.

> Change the container name in policy

Does this indicate, for example, value (`container`) of `kubearmor.io/container.name` in the following policy?

```yaml
..
metadata:
  name: block-diff
spec:
  selector:
    matchLabels:
      kubearmor.io/container.name: container
...
```

If this is correct, if the value of `kubearmor.io/container.name` in policy is changed, I think this issue will be fixed if the SecurityPolicy object in `dm.EndPoints` corresponding to the previous container name is deleted in [ParseAndUpdateContainerSecurityPolicy()](https://github.com/kubearmor/KubeArmor/blob/main/KubeArmor/core/unorchestratedUpdates.go#L83).

**Comment by Aryan-sharma11** [comment]
> Hi, @Aryan-sharma11 @nyrahul
> 
> Thanks for comments !!! I have a question about the expected behavior.
> 
> > Change the container name in policy
> 

> Does this indicate, for example, value (`container`) of `kubearmor.io/container.name` in the following policy?
> 
> ```yaml
> ..
> metadata:
>   name: block-diff
> spec:
>   selector:
>     matchLabels:
>       kubearmor.io/container.name: container
> ...
> ```
> 
> If this is correct, if the value of `kubearmor.io/container.name` in policy is changed, I think this issue will be fixed if the SecurityPolicy object in `dm.EndPoints` corresponding to the previous container name is deleted in [ParseAndUpdateContainerSecurityPolicy()](https://github.com/kubearmor/KubeArmor/blob/main/KubeArmor/core/unorchestratedUpdates.go#L83).

@haytok Hey, thanks for your interest in this issue.

Yes you are correct here, that if the container name is changed and the policy is applied, the policy is applied on earlier container as well as for the new container, ideally the case should be firstly the policy should be removed from the previous container(similar to Delete event [here](https://github.com/kubearmor/KubeArmor/blob/main/KubeArmor/core/unorchestratedUpdates.go#L529C1-L530C1))  and then applied for the new container
cc @nyrahul

**Comment by haytok** [comment]
Hi, @Aryan-sharma11 @nyrahul 

Thanks for comments !!!

I have created the pull request, so could you review if you have time ?
