### ISSUE TITLE
Move from Helm to Kustomize for installing KubeArmor

### ISSUE THREAD

**Issue by khareyash05** [kubearmor/KubeArmor#1391]
## Feature Request

**Short Description**
We can use Kustomize instead of Helm charts to install KubeArmor. Use of simple YAML files in Kustomize will also facilitate easy bug fix in installation and will also increase readability. Also use of Overlays in Kustomize will help reduce redundant config files.

**Comment by kranurag7** [comment]
@khareyash05 IMHO, I understand with helm you get errors that are hard to debug sometimes. I think in the near future, I'm not aware of any plan to move the default installation option using kustomize. I think it's going to be helm. 

Having said that, if you're encountering any issues now or in the near future, then feel free to tag me or open an issue. I'll try to have a look at that.  

Please note that we have different volumeMounts depending on the platform or provider we are deploying kubearmor onto, thus the configuration files are necessary for now.

**Comment by nyrahul** [comment]
Closing this since there is no plans to move to kustomize unless someone provides a clear problem statement with helm that kustomize addresses.
