### ISSUE TITLE
Include protected pods to the ksp status

### ISSUE THREAD

**Issue by achrefbensaad** [kubearmor/KubeArmor#1393]
## Feature Request

**Short Description**

Currently we rely on `karmor probe` output to figure out what are the pods that are protected by a certain ksp (KubeArmor Security Policy). We would like to include that information in the ksp status.

**Problem with `karmor probe`**

In `karmor probe` we are performing the policy matching on the client side. This turned out to cause some flakiness in output.

**Describe the solution you'd like**

Kubearmor already maintains a list of pods and theirs respective ksp's. We can use this information to update the ksp with the protected targets list.

By doing this, we will be able to query the list of protected pods by using `kubectl` and stabilize `karmor probe`

- [ ] Propose a KSP update
- [ ] Update KSP code
- [ ] Update kubearmor to patch the ksp with the protected pods/resources list

**Comment by daemon1024** [comment]
Related #1326

**Comment by nyrahul** [comment]
After extensive discussions and two attempts at handling this, the maintainer team has decided that it may not be a good idea to associate a policy statically to a set of pods/workloads. Changing the status/labels across the pods/resources have direct impact on these mappings and requires lot of control plane operations that will backfire in big cluster deployments.
