### ISSUE TITLE
Build bpftool from source in Vagrant env

### ISSUE THREAD

**Issue by daemon1024** [kubearmor/KubeArmor#1400]
`bpftool` can through out the following error

```
Error: failed to load BTF from /sys/kernel/btf/vmlinux: Unknown error -4001
```

in some cases due to kernel version mismatch with bpftool package installation causing issues in dev env. 

The workaround is to build bpftool from source in the env. We should automate this in the vagrantfile to reduce hiccups for contributors or dev env setup.

Ref:
https://stackoverflow.com/questions/70093863/linux-btf-bpftool-failed-to-get-ehdr-from-sys-kernel-btf-vmlinux
https://github.com/libbpf/bpftool#build

**Comment by pavan12395** [comment]
I would try to add a script for ubuntu 20.04 (NETNEXT=0) and ubuntu 22.04 (NETNEXT=1) which builds bpftool from the sources

Can you assign this issue to me

**Comment by daemon1024** [comment]
Thanks for taking this up @pavan12395 ☺️ You can reach out to me in this thread or on Slack if you need any help.

**Comment by pavan12395** [comment]
Hey @daemon1024, Tested these changes for NETNEXT=0,1 , Working fine.
