### ISSUE TITLE
Error running non-root container on containerd

### ISSUE THREAD

**Issue by rksharma95** [kubearmor/KubeArmor#1409]
## Bug Report

**General Information**

- Environment description (k3s)
- Kernel version (run `uname -a`) 5.14.0-284.25.1.el9_2.x86_64
- Orchestration system version in use (e.g. `kubectl version`, ...) v1.27.5+k3s1
- Link to relevant artifacts (policies, deployments scripts, ...)
- Target containers/pods `kubearmor-operator-*`

**To Reproduce**

1. Set up k3s with containerd
2. Deploy KubeArmor Operator using helm or manifest
3. Check if kubearmor operator pod is running, error `exec /operator: operation not permitted` is expected here

We're aware of this issue that we also faced with running (ubi-based, non-root) kubearmor container image on k8s clusters with containerd container runtime.  In these kind of scenarios the workaround is to add required capabilities to the binaries itself using the `setcap` during building the container image and assigning the required capabilities using the pod security context without `allowPrivilegeEscalation: false`. We tried all these workarounds but unfortunately none worked.
```
runAsUser: 1000
runAsGroup: 1000
allowPrivilegeEscalation: true
```
```
runAsUser: 0
runAsGroup: 0
allowPrivilegeEscalation: true
```

Related: https://github.com/kubernetes/enhancements/blob/master/keps/sig-security/2763-ambient-capabilities/README.md, 
https://github.com/containerd/containerd/issues/2516

**Expected behavior**

The operator should run successfully without any operation not permitted error.

**Screenshots**

**Comment by anurag-rajawat** [comment]
@rksharma95 I also faced the same issue while trying KubeArmor installation using the operator on k0s and I temporarily fixed it by commenting the below line.

https://github.com/kubearmor/KubeArmor/blob/3bf31234d0927bdb5d5799e6b021d5dba4690de0/pkg/KubeArmorOperator/Dockerfile#L61

**Comment by rksharma95** [comment]
> @rksharma95 I also faced the same issue while trying KubeArmor installation using the operator on k0s and I temporarily fixed it by commenting the below line.
> 
> https://github.com/kubearmor/KubeArmor/blob/3bf31234d0927bdb5d5799e6b021d5dba4690de0/pkg/KubeArmorOperator/Dockerfile#L61

What was the container runtime? If it's containerd is this temporary fix worked on containerd?

**Comment by anurag-rajawat** [comment]
> What was the container runtime? If it's containerd is this temporary fix worked on containerd?

Yes it is containerd.

**Comment by rksharma95** [comment]
@anurag-rajawat we've tried this workaround but unfortunately it never worked for us. you can see the failure here https://github.com/kubearmor/KubeArmor/actions/runs/6113392565/job/16664338697?pr=1270 , i'm not sure if it's working in a containerd env.
