### ISSUE TITLE
Replace AccuKnox org images with KubeArmor

### ISSUE THREAD

**Issue by ShubhamTatvamasi** [kubearmor/KubeArmor#1424]
On our contribution guide there are old images from the time when the KubeArmor was in AccuKnox org. We have to update those images to avoid confusion. 

https://github.com/kubearmor/KubeArmor/blob/main/contribution/contribution_guide.md

**Comment by VamshiReddy02** [comment]
can I work on this issue?

**Comment by ShubhamTatvamasi** [comment]
> can I work on this issue?

Sure @VamshiReddy02, let us assign this to you.
