### ISSUE TITLE
Update VMWare to VMware

### ISSUE THREAD

**Issue by ShubhamTatvamasi** [kubearmor/KubeArmor#1428]
Update `VMWare` to `VMware`

https://github.com/kubearmor/KubeArmor/blob/main/getting-started/support_matrix.md

**Comment by MeenuyD** [comment]
Hello @ShubhamTatvamasi I would like to work on this issue can you please assign it to me

**Comment by ShubhamTatvamasi** [comment]
> Hello @ShubhamTatvamasi I would like to work on this issue can you please assign it to me

Sure
