### ISSUE TITLE
Update the PolicyMatcher for matchPatterns

### ISSUE THREAD

**Issue by nam-jaehyun** [kubearmor/KubeArmor#143]
Currently, the policy matching logic for matchPatterns is missing.
Need to update the logic in [policyMatcher.go](https://github.com/accuknox/KubeArmor/blob/master/KubeArmor/feeder/policyMatcher.go).

**Comment by geyslan** [comment]
@nam-jaehyun please assign this to me.

The lack is related to these, right?

https://github.com/accuknox/KubeArmor/blob/530306afe75c60c4fe57e0ab692201a0f8e2ff71/KubeArmor/feeder/policyMatcher.go#L139-L141

https://github.com/accuknox/KubeArmor/blob/530306afe75c60c4fe57e0ab692201a0f8e2ff71/KubeArmor/feeder/policyMatcher.go#L259-L261

https://github.com/accuknox/KubeArmor/blob/530306afe75c60c4fe57e0ab692201a0f8e2ff71/KubeArmor/feeder/policyMatcher.go#L579-L581

Is this the current policies?

https://github.com/accuknox/KubeArmor/blob/master/getting-started/security_policy_specification.md

Thanks.

**Comment by nam-jaehyun** [comment]
@geyslan Yes, those are the missing part, and the key point is this.
In the cases of paths and directories, we can conduct some exact matching or prefix matching
to find the policy corresponding to an incoming log. However, when we use patterns, we need additional processes.
For example, how can we conduct the policy matching if a pattern looks like "/{usr/bin,bin}/foo"?

**Comment by geyslan** [comment]
> For example, how can we conduct the policy matching if a pattern looks like "/{usr/bin,bin}/foo"?

Regarding this, I think we need to specify and to clarify in the documentation some restriction rules for the pattern usage as the same [documentation](https://github.com/accuknox/KubeArmor/blob/master/getting-started/security_policy_specification.md) doesn't recommend the `matchPatterns`:

> Thus, we generally do not recommend using this match.

But I also noticed that documentation specifies:

> However, the coverage of regular expressions is highly dependent on [AppArmor](https://gitlab.com/apparmor/apparmor/-/wikis/AppArmor_Core_Policy_Reference) (Policy Core Reference).

Maybe we can rely on Golang own `regexp` package as a generic solution to treat inputs but perhaps not for checking them. I suppose that we are constrained to just checking for the regex validity in the policyMatcher.go, being forced to let its expansion against real file/path/other strings in later checking even I knowing it would not be optimal.

Although, as I said in the beginning, the rules could be restricted for some well defined [globbing](https://tldp.org/LDP/abs/html/globbingref.html) expansions.

Using your example:

`"/{usr/bin,bin}/foo"` would be expanded to:

`"/usr/bin/foo /bin/foo"`

Let me know if I'm not considering the whole scenario.

Edit:

I have another question:

_Updated Policies_ functions are only locking for updates (ADDED and MODIFIED). That shouldn't be the same case for DELETED?

https://github.com/accuknox/KubeArmor/blob/530306afe75c60c4fe57e0ab692201a0f8e2ff71/KubeArmor/feeder/policyMatcher.go#L445-L447

**Comment by nam-jaehyun** [comment]
1. I'm not sure that AppArmor's regex engine follows generic regex rules; thus, I feel that regexp may work differently.
However, it would be worth trying to generate several regex patterns and check them in both regexp and AppArmor.

2. the whole "matches" is always generated whenever there is a new policy or a modification in a policy; thus, we don't need to care about the removal of individual policies.

**Comment by geyslan** [comment]
>     1. I'm not sure that AppArmor's regex engine follows generic regex rules; thus, I feel that regexp may work differently.
>        However, it would be worth trying to generate several regex patterns and check them in both regexp and AppArmor.

I suspect that AppArmor doesn't support regex, based on its documentation. It actually works with Globbing patterns.

These are some Glob examples: https://play.golang.org/p/vB6iaiUQUhp

It looks like `Glob()` doesn't work very well in some scenarios.

>     2. the whole "matches" is always generated whenever there is a new policy or a modification in a policy; thus, we don't need to care about the removal of individual policies.

By saying that, you mean we don't need to lock during deletion, right?

Thanks a million.

---

Edit:

I have doubts about where the pattern should be handled. In user space it will be limited to simple and well-defined expansions.

**Comment by nam-jaehyun** [comment]
While we have policies with patterns in userspace, system logs come from the kernel space with the actual paths.
To generate alerts, we need to find which policies the system logs are mapped to according to the given patterns.

So, we need to ...
1. pre-compute patterns when they are applied in advance (UpdateSecurityPolicies in policyMatcher.go).
2. match the patterns with system logs for generating alerts (UpdateMatchedPolicy in policyMatcher.go).

Are those what you were curious about?

**Comment by geyslan** [comment]
> Are those what you were curious about?

Sure thing. Thanks a million.

**Comment by nam-jaehyun** [comment]
@geyslan When can we see the logs corresponding to patterns?

**Comment by geyslan** [comment]
Hi @nam-jaehyun, due the event auditor design tasks this was delayed. I'm going to focus on this soon.

**Comment by geyslan** [comment]
@oneiro-naut We are assuming here that AppArmor is the native policy spec? https://github.com/accuknox/KubeArmor/blob/55ff9ce5c374454dcdc2abbc03d7d4199994595b/KubeArmor/feeder/policyMatcher.go#L179-L183

**Comment by oneiro-naut** [comment]
> @oneiro-naut We are assuming here that AppArmor is the native policy spec? https://github.com/accuknox/KubeArmor/blob/55ff9ce5c374454dcdc2abbc03d7d4199994595b/KubeArmor/feeder/policyMatcher.go#L179-L183

Yes. In future other native LSM policies might be added and it will be set to true for them as well.

**Comment by geyslan** [comment]
@oneiro-naut I see. Thanks.

For `UpdateMatchedPolicy()` I'll consider AppArmor as native as well, and the previously added Regexp field as non native. I suppose Regexp (or glob) could be the KubeArmor native matchPattern. But we need to discuss this design.

---

Edit:

After the discussion we've had, I agree with you about adding another field to MatchPolicy related to pattern match type and about not involving the native flag.
