### ISSUE TITLE
Deleting policies in systemd KubeArmor showing error message

### ISSUE THREAD

**Issue by JayJersan** [kubearmor/KubeArmor#1449]
## Bug Report

**General Information**

- Environment description: Azure VM
- Kernel version: Linux azure-vm 5.15.0-1045-azure #52~20.04.1-Ubuntu SMP Fri Aug 18 13:12:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- KubeArmor version: kubearmor_1.0.1_linux-amd64.deb

**To Reproduce**

1. Apply a policy using `karmor vm policy add`
2. Delete the previously applied policy using `karmor vm policy delete`

**Expected behavior**

The message should say that the policy was deleted/removed successfully

**Comment by Aryan-sharma11** [comment]
@JayJersan Hi can you attach the screenshot of what messege you get, according to current implementation the message should be `Policy Deleted`. 
Also we have recently changed the handling of policy addition and deletion events in systemd mode so you have to update kubearmor client to latest version. For ref #1312

**Comment by JayJersan** [comment]
Deleting the policy:
![image](https://github.com/kubearmor/KubeArmor/assets/110662720/a1886140-23cc-45c0-bee4-3c068cde884c)

Now viewing the logs, it says that the policy was deleted:
![image](https://github.com/kubearmor/KubeArmor/assets/110662720/9307a01c-8d7b-46fd-af79-0bd5deb4393d)

karmor version output:
![image](https://github.com/kubearmor/KubeArmor/assets/110662720/4222d628-4d3a-4cec-a2b3-c8319f426804)

**Comment by Aryan-sharma11** [comment]
@JayJersan can you try doing `karmor selfupdate` the latest version should be 0.14.1

**Comment by JayJersan** [comment]
Yes, it is showing correctly now
![image](https://github.com/kubearmor/KubeArmor/assets/110662720/973b684c-4472-4ca9-acd8-1801c1b0b703)
The issue was due to the old karmor being used as you mentioned. Thank you!
