### ISSUE TITLE
Secure KubeArmor gRPC Endpoint

### ISSUE THREAD

**Issue by daemon1024** [kubearmor/KubeArmor#1464]
We use gRPC Insecure

https://github.com/kubearmor/kubearmor-relay-server/blob/34b9f3bd270e3edf6fbe3aae91504cc5f7f83ee3/relay-server/server/relayServer.go#L311

**Comment by daemon1024** [comment]
- [ ] - Relay should be compatible with both TLS/Insecure KA Connection
- [ ] - All Clients should be compatible with both TLS/Insecure Relay/KA Connections
- [ ] - Keep TLSConfig False till we are sure that no one is going to use older Clients
- [ ] - Clients aren't limited to kArmor but any client which connects to Relay/KubeArmor over gRPC

**Comment by rksharma95** [comment]
Overview of changes handled with linked PR:

### Configurations
`--tlsEnabled: "true/false"`
`--tlsCertPath: "valid path"` , common certificate path where CA, Client/Server cert files are present.
`--tlsCertProvider: "self/external"`, weather client/server certificate are provided (external) or need to be generated dynamically (self).

### Certificate Generation:
- A server or client would be able to create it's own certificate provided the access of the CA certificate and key.
- At this point KubeArmor daemonset/server generates it's own certificates, the access to the CA will be provided by mounting the CA certificate using the k8s secret in a k8s env.
- KubeArmor Relay and Karmor doesn't required to create their own certificates. the client certificates will be generated by either operator or helm template and will be stored in a k8s secret.

### HL Design Overview
![ka-secure-grpc](https://github.com/kubearmor/KubeArmor/assets/81104646/98d913da-e5d0-4a46-a88c-d7fcb78a467c)

**Comment by daemon1024** [comment]
Reopening till we have client and relay integrations

**Comment by DelusionalOptimist** [comment]
Future action items:
- [ ] Look into using an external CA (cert manager) instead of managing it ourselves and storing it in a k8s secret.
