### ISSUE TITLE
helm values for kubearmor relay stdout env

### ISSUE THREAD

**Issue by daemon1024** [kubearmor/KubeArmor#1469]
## Feature Request

**Short Description**

KubeArmor Relay supports emitting telemetry to STDOUT, but it's tedious process to edit the deployment and add the env vars to enable that feature. We should keep it as a flag in our helm chart

**Is your feature request related to a problem? Please describe the use case.**

https://github.com/kubearmor/kubearmor-relay-server#streaming-kubearmor-telemetry-to-external-siem-tools

the env vars that needs to be in helm values

**Comment by VedRatan** [comment]
Please assign this to me
