### ISSUE TITLE
Attribution to Tracee

### ISSUE THREAD

**Issue by itaysk** [kubearmor/KubeArmor#148]
Hello from Team [Tracee](https://github.com/aquasecurity/tracee)!
We recently came across this project and couldn't have ignored the stark resemblance of your code to the Tracee code in some places, specifically in the monitoring and eBPF parts. We are flattered that we managed to inspire you and you are free to continue and use any part of Tracee as long as you respect its open source license agreement. Pursuant to the agreement, we ask that you include the Tracee copyright and notice in the appropriate places. Our notice can be found here https://github.com/aquasecurity/tracee/blob/main/NOTICE.
Additionally we would appreciate if you would show courtesy and give credit to Tracee in your readme file footer, as is often practiced in the open source community.
Thanks,
Itay Shakury
Director of Open Source, Aqua Security

**Comment by nam-jaehyun** [comment]
Sure, we'll add some NOTICEs in this project.

**Comment by nyrahul** [comment]
> Hello from Team [Tracee](https://github.com/aquasecurity/tracee)!
> We recently came across this project and couldn't have ignored the stark resemblance of your code to the Tracee code in some places, specifically in the monitoring and eBPF parts. We are flattered that we managed to inspire you and you are free to continue and use any part of Tracee as long as you respect its open source license agreement. Pursuant to the agreement, we ask that you include the Tracee copyright and notice in the appropriate places. Our notice can be found here https://github.com/aquasecurity/tracee/blob/main/NOTICE.
> Additionally we would appreciate if you would show courtesy and give credit to Tracee in your readme file footer, as is often practiced in the open source community.
> Thanks,
> Itay Shakury
> Director of Open Source, Aqua Security

Surely Itay, we should have attributed this in the first place. Thank you for bringing this to our notice.
