### ISSUE TITLE
Update Twitter logo that is 'X'.

### ISSUE THREAD

**Issue by Ayush9026** [kubearmor/KubeArmor#1494]
## Feature Request

**Short Description**

Update Twitter logo with new one marked in screenshot below.
![Kubearmor](https://github.com/kubearmor/KubeArmor/assets/114745463/7e526a30-875e-4e61-b00d-c6e7e5310f88)

**Is your feature request related to a problem? Please describe the use case.**

UI/UX related. 

**Describe the solution you'd like**

Update with new one

**Comment by hanshal101** [comment]
Heyy @Ayush9026  I would like to work on this issue. Will you please guide me to the repo link for the website? I tried but couldn't find one.

**Comment by daemon1024** [comment]
Thanks for noticing this! 

Accuknox Website is not managed by the KubeArmor community. But I have informed the team to take note of it.
