### ISSUE TITLE
Add policy match support for native AppArmor policies

### ISSUE THREAD

**Issue by oneiro-naut** [kubearmor/KubeArmor#151]
KubeArmor allows native apparmor policies to be added as it is in YAML policies. These native policies are being enforced but do not generate any logs upon policy violations. This issue can be reproduced by simply applying any native apparmor policy and violating it in the selected pods. This should have ideally generated logs in the kubearmor.log file. But the log file will contain no such events.
```
apiVersion: security.accuknox.com/v1
kind: KubeArmorPolicy
metadata:
  name: native-apparmor-policy-1
  namespace: multiubuntu
spec:
  severity: 5
  message: "native read-only etc"
  selector:
    matchLabels:
      group: group-1
  apparmor: |
        deny /etc/{*,**} w,
```
After applying this policy we can check in one of the ubuntu pods with group=group-1 by trying to violate the policy. In this example it makes /etc/ directory read-only. 
```
vagrant@kubearmor-dev:/etc/apparmor.d$ kubectl exec -ti -n multiubuntu ubuntu-1-deployment-5c475fb4fb-rfttn -- /bin/bash
root@ubuntu-1-deployment-5c475fb4fb-rfttn:/# cd /etc
root@ubuntu-1-deployment-5c475fb4fb-rfttn:/etc# echo "data" >> hosts
bash: hosts: Permission denied
``` 
This violation should generate logs. We can check it by looking the contents of /tmp/kubearmor.log inside the kubearmor container.
```
vagrant@kubearmor-dev:/etc/apparmor.d$ kubectl exec -ti -n kube-system kubearmor-kp6kr -- /bin/bash
bash-5.0# cat /tmp/kubearmor.log

```
We can see its empty and does not contain any log for violation.
This could be the result of feeder not tracking native policy entries in its security policy map.[1]https://github.com/accuknox/KubeArmor/blob/cc3b39c19ba6f23cd418d042db7eac4e0b145e06/KubeArmor/feeder/policyMatcher.go#L446
Possible fix would be to modify it to add native apparmor policies to [1].
We might need to modify struct MatchPolicy[2] as well adding by adding field(s) for native policies.
https://github.com/accuknox/KubeArmor/blob/cc3b39c19ba6f23cd418d042db7eac4e0b145e06/KubeArmor/types/types.go#L179

**Comment by geyslan** [comment]
@oneiro-naut I am creating tests for policyMatcher.go and planning (perhaps) to refactor it massively. Could you explain your approach to this issue so we can work side by side? Thanks.

**Comment by oneiro-naut** [comment]
@geyslan I plan to add a condition to check if the security policy Spec contains non empty Apparmor field. If it does it will be appended to map [1] along with its associated metadata. Basically adding an if block inside this for loop. https://github.com/accuknox/KubeArmor/blob/cc3b39c19ba6f23cd418d042db7eac4e0b145e06/KubeArmor/feeder/policyMatcher.go#L22

**Comment by geyslan** [comment]
Ok. I'm following this issue so we can be aligned. Thanks.

**Comment by oneiro-naut** [comment]
Hi @nam-jaehyun . I have made few changes so far which are allowing native policy logs to be dumped in kubearmor.logs. But the problem is  the logs are gathering unrelated events along with the native one. Its expected since we don't parse the native rules and have no higher level tags or metadata associated with them. I have thought of some ways to match these native rules but all of them will require some form of parsing. But as per my understanding the purpose of having these native rules was to avoid parsing. Please let me know your thoughts on this.

**Comment by nam-jaehyun** [comment]
@oneiro-naut We wanted to support native AppArmor rules as they are. It doesn't mean that we don't parse the native rules.
In the view of a user, he/she uses native rules. In the view of KubeArmor, it can still parse the rules for specific reasons.

**Comment by nyrahul** [comment]
> @oneiro-naut We wanted to support native AppArmor rules as they are. It doesn't mean that we don't parse the native rules.
> In the view of a user, he/she uses native rules. In the view of KubeArmor, it can still parse the rules for specific reasons.

To summarize from today's discussion:
1. We won't parse native rules in KubeArmor since it is difficult to know what to expect. Secondly, the same might have to be done for other LSMs (SELinux) and this will get extremely complex in no time and still cannot guarantee that it will work in all cases.
2. For native rules and baseline LSM rules, when we get an audit/deny the event, we will augment the event with additional k8s metadata as we do currently for non-native policies. The only information that will be missing from the event would be the associated policy-name/type details.

The biggest limitation with the above proposal is **we won't be able to get per-policy stats in the context of native-policies**.

However, we can still get the alerts/events in a particular container/pod context. Secondly, this will also work for baseline LSM rules not provisioned through KubeArmor.

**Comment by oneiro-naut** [comment]
Thanks @nyrahul . I will make changes accordingly.

**Comment by nyrahul** [comment]
Also one more point:

**We need to reject the policy if someone attempts to specify a native AppArmor policy when the platform doesn't support that LSM.**

This validation code needs to be generic i.e. when we support SELinux native policies this validation should work as-is.

If you think this is difficult to handle now or out-of-scope for this issue then raise another issue and let's keep it in TODO.

**Comment by oneiro-naut** [comment]
> Also one more point:
> 
> **We need to reject the policy if someone attempts to specify a native AppArmor policy when the platform doesn't support that LSM.**
> 
> This validation code needs to be generic i.e. when we support SELinux native policies this validation should work as-is.
> 
> If you think this is difficult to handle now or out-of-scope for this issue then raise another issue and let's keep it in TODO.

Hi @nyrahul . I looked into this. I think we would need some generic fields to be added to the SecurityPolicy struct and the current KubeArmorPolicy CRD. Currently native is synonymous with Apparmor native only. So as a prerequisite to implement this point we would need to add a parent field so that yaml will look something like this:
```
spec:
  native: 
       enforcerType: selinux | apparmor | krsi 
       policy: |
          ...
```
I feel this point should be handled as a separate issue.

**Comment by nyrahul** [comment]
> I think we would need some generic fields to be added to the SecurityPolicy struct and the current KubeArmorPolicy CRD. Currently native is synonymous with Apparmor native only. So as a prerequisite to implement this point we would need to add a parent field so that yaml will look something like this:
> 
> ```
> spec:
>   native: 
>        enforcerType: selinux | apparmor | krsi 
>        policy: |
>           ...
> ```
> 
> I feel this point should be handled as a separate issue.

Handling it in a separate issue is fine but regarding adding generic fields, I am not sure if I follow.
It is already possible to know what LSM is to be used for the native policies.
![image](https://user-images.githubusercontent.com/9133227/122700774-8afa7180-d269-11eb-8267-8993f4a04f55.png)
