### ISSUE TITLE
KubeArmor policy misattribution

### ISSUE THREAD

**Issue by pa-federici** [kubearmor/KubeArmor#1527]
## KubeArmor policy misattribution

 **General Information**

* Environment description eks 1.28
* Kernel version Linux 5.10.192-183.736.amzn2.x86_64 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
* Orchestration system version in use Kubernetes v1.28.1
* Target issue riproduced on different containers, including on standard images from docker hub like ubuntu:23.04
* Tested with kubearmor/kubearmor and kubearmor/kubearmor-init image versions v1.0.1

**To Reproduce**

1. Create a pod with the image ubuntu:23.04
2. Set the "DefaultPosture" to Audit
3. Create a Kubearmor policy that match the container, add the root directory, setting action parameter to "Allow" and recursive parameter to "true". To allow all the file and process in the container
4. Create a file called `myscript.sh` and write a simple script inside.
   Example: 
   ```
    #!/bin/sh 
    echo "Hello, World!"
    ```
6. Remove all permissions on this file
       execute:
   ```bash
   chmod 000 myscript.sh
    ```
8. Launch `Karmor logs` command to collect the logs
9. Try to execute this script with the command `./myscript.sh`

**Expected behavior**

I expect that kubearmor will not generate any logs since the policy will not block the action on the container. But the log shows that it is blocked by "DefaultPosture"

**Screenshots**

![image](https://hackmd.io/_uploads/B1-iwSPBT.png)

**Comment by ernspa94** [comment]
Hi, same problem here. Can you check please?

**Comment by daemon1024** [comment]
Hey Folks, We fixed issues in our policy matcher and have new mechanisms to alert during audit mode for whitelist policy.

Updates in the context include
- #1569 
- #1370
- #1492

Please retry and let us know if it's still an issue. Thanks.

**Comment by bvenreply** [comment]
Hello, I checked on my end, I can confirm the above described issue no longer reproduces as of version `v1.1.1` onwards. Thanks a lot @daemon1024!

**Comment by daemon1024** [comment]
Thanks for verifying @bvenreply 🙌 Glad to know it's fixed.

P.s. please update to v1.1.2 ( already marked stable ), some bugs made it to v1.1.1 which are now fixed, especially around Policy Matcher. Thank You.
