### ISSUE TITLE
supporting netnext/latest kernels

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#153]
- [x] supporting netnext for dev env setup
- [x] fixing compilation issues for kubearmor for latest kernel (>5.10)
- [x] Updating dev guide document
- [x] speed up compilation

**Comment by geyslan** [comment]
Reproducible:

```bash
❯ NETNEXT=1 vagrant up
❯ NETNEXT=1 vagrant ssh
```

```bash
vagrant@kubearmor-dev-next:~/KubeArmor/KubeArmor$ make run
cd /home/vagrant/KubeArmor/KubeArmor; sudo rm -f /tmp/kubearmor.log
cd /home/vagrant/KubeArmor/KubeArmor; sudo -E ./kubearmor -logPath=/tmp/kubearmor.log
2021-06-19 00:18:07.958493	INFO	Started to serve gRPC-based log feeds
2021-06-19 00:18:07.961164	INFO	Initializing an eBPF program
In file included from <built-in>:1:
././include/linux/kconfig.h:5:10: fatal error: 'generated/autoconf.h' file not found
#include <generated/autoconf.h>
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
2021-06-19 00:18:09.103748	ERROR	Failed to initialize the system monitor
github.com/accuknox/KubeArmor/KubeArmor/log.Err
	/home/vagrant/KubeArmor/KubeArmor/log/logger.go:99
github.com/accuknox/KubeArmor/KubeArmor/feeder.(*Feeder).Err
	/home/vagrant/KubeArmor/KubeArmor/feeder/feeder.go:398
github.com/accuknox/KubeArmor/KubeArmor/core.KubeArmor
	/home/vagrant/KubeArmor/KubeArmor/core/kubeArmor.go:338
main.main
	/home/vagrant/KubeArmor/KubeArmor/main.go:60
runtime.main
	/usr/local/go/src/runtime/proc.go:225
2021-06-19 00:18:09.106191	INFO	Stopped the system monitor
2021-06-19 00:18:09.106250	INFO	Terminated the KubeArmor
2021-06-19 00:18:11.108718	INFO	Stopped the log feeder
2021-06-19 00:18:11.108896	INFO	Waiting for remaining routine terminations
```

I'm updating the vagrant box from version 94 to 96. `NETNEXT=1 vagrant box update`

https://vagrantcloud.com/cilium/boxes/ubuntu-next/versions/96/providers/virtualbox.box

When done I'll try to run KubeArmor on it.

**Comment by nyrahul** [comment]
Yes, this is the pending compilation issue still open.
I am using version 96 and it still fails. I think I know the problem, but I am trying to understand the best way to fix it. The problem is the header files location.

**Comment by geyslan** [comment]
The same error with version 96:

```bash
vagrant@kubearmor-dev-next:~/KubeArmor/KubeArmor$ make run
cd /home/vagrant/KubeArmor/KubeArmor; sudo rm -f /tmp/kubearmor.log
cd /home/vagrant/KubeArmor/KubeArmor; sudo -E ./kubearmor -logPath=/tmp/kubearmor.log
2021-06-19 02:26:39.715350	INFO	Started to serve gRPC-based log feeds
2021-06-19 02:26:39.721227	INFO	Initializing an eBPF program
In file included from <built-in>:1:
././include/linux/kconfig.h:5:10: fatal error: 'generated/autoconf.h' file not found
#include <generated/autoconf.h>
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
2021-06-19 02:26:40.876632	ERROR	Failed to initialize the system monitor
github.com/accuknox/KubeArmor/KubeArmor/log.Err
	/home/vagrant/KubeArmor/KubeArmor/log/logger.go:99
github.com/accuknox/KubeArmor/KubeArmor/feeder.(*Feeder).Err
	/home/vagrant/KubeArmor/KubeArmor/feeder/feeder.go:398
github.com/accuknox/KubeArmor/KubeArmor/core.KubeArmor
	/home/vagrant/KubeArmor/KubeArmor/core/kubeArmor.go:338
main.main
	/home/vagrant/KubeArmor/KubeArmor/main.go:60
runtime.main
	/usr/local/go/src/runtime/proc.go:225
2021-06-19 02:26:40.879780	INFO	Stopped the system monitor
2021-06-19 02:26:40.879788	INFO	Terminated the KubeArmor
2021-06-19 02:26:42.883124	INFO	Stopped the log feeder
2021-06-19 02:26:42.883295	INFO	Waiting for remaining routine terminations

vagrant@kubearmor-dev-next:~/KubeArmor/KubeArmor$ uname -a
Linux kubearmor-dev-next 5.13.0-rc3+ #1 SMP Thu Jun 17 20:34:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
vagrant@kubearmor-dev-next:~/KubeArmor/KubeArmor$
```

I think I've found the issue:

```bash
vagrant@kubearmor-dev-next:~$ ls -l /usr/src/linux-headers-5.13.0-rc3+/
total 1680
drwxr-xr-x  3 root root    4096 Jun 17 21:16 arch
drwxr-xr-x 31 root root    4096 Jun 17 21:16 include
-rw-r--r--  1 root root   65693 Jun 17 20:32 Makefile
-rw-r--r--  1 root root 1622297 Jun 17 20:33 Module.symvers
drwxr-xr-x 17 root root   12288 Jun 17 21:16 scripts
drwxr-xr-x  3 root root    4096 Jun 17 21:16 tools
```

Cilium image does not have all kernel include files.

So, after downloading and installing the linux-image, linux-headers and linux-modules packages from https://kernel.ubuntu.com/~kernel-ppa/mainline, KubeArmor worked smoothly again.

```bash
vagrant@kubearmor-dev-next:~/KubeArmor/KubeArmor$ make run
cd /home/vagrant/KubeArmor/KubeArmor; sudo rm -f /tmp/kubearmor.log
cd /home/vagrant/KubeArmor/KubeArmor; sudo -E ./kubearmor -logPath=/tmp/kubearmor.log
2021-06-19 03:00:33.197892	INFO	Started to serve gRPC-based log feeds
2021-06-19 03:00:33.199920	INFO	Initializing an eBPF program
2021-06-19 03:00:35.569707	INFO	Initialized the eBPF program
2021-06-19 03:00:35.878975	INFO	Started to monitor system events
2021-06-19 03:00:35.957410	INFO	Initialized AppArmor Enforcer
2021-06-19 03:00:35.957473	INFO	Started to protect containers
2021-06-19 03:00:36.979314	INFO	Initialized the Kubernetes client
2021-06-19 03:00:36.979346	INFO	Started to monitor Pod events
2021-06-19 03:00:36.979493	INFO	Started to monitor security policies
2021-06-19 03:00:37.011182	INFO	Container Runtime: docker://20.10.7
2021-06-19 03:00:37.011985	INFO	Started to monitor Docker events
2021-06-19 03:00:38.011471	INFO	Initialized KubeArmor
^C2021-06-19 03:05:08.095549	INFO	Got a signal to terminate the KubeArmor
2021-06-19 03:05:08.095588	INFO	Destroyed AppArmor Enforcer
2021-06-19 03:05:08.095597	INFO	Stopped the runtime enforcer
2021-06-19 03:05:09.401956	INFO	Stopped the system monitor
2021-06-19 03:05:09.402027	INFO	Terminated the KubeArmor
2021-06-19 03:05:11.403200	INFO	Stopped the log feeder
2021-06-19 03:05:11.403239	INFO	Waiting for remaining routine terminations
Makefile:12: recipe for target 'run' failed
make: *** [run] Interrupt

vagrant@kubearmor-dev-next:~/KubeArmor/KubeArmor$ uname -a
Linux kubearmor-dev-next 5.13.0-051300rc3-generic #202105232230 SMP Tue Jun 15 12:37:40 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

👍

**Comment by geyslan** [comment]
> Yes, this is the pending compilation issue still open.
> I am using version 96 and it still fails. I think I know the problem, but I am trying to understand the best way to fix it. The problem is the header files location.

Maybe adding rules to Vagrant to download and install a specific kernel version (image, modules and includes).

**Comment by nyrahul** [comment]
> > Yes, this is the pending compilation issue still open.
> > I am using version 96 and it still fails. I think I know the problem, but I am trying to understand the best way to fix it. The problem is the header files location.
> 
> Maybe adding rules to Vagrant to download and install a specific kernel version (image, modules and includes).

Yeah, the linux-headers download worked for me too ... But I was trying to check if there is any other way to do it... Note that cilium eBPF modules compile on the same image without these additional installs.

Turns out BCC has a way to specify the kernel-headers location using BCC_KERNEL_SOURCES.. Haven't tried this yet.

**Comment by geyslan** [comment]
In KubeArmor, there is only one use of BCC_KERNEL_SOURCE:
 
https://github.com/accuknox/KubeArmor/blob/0657bb66c3bbc80e27f1b4e966667041bd530706/KubeArmor/monitor/systemMonitor.go#L222-L247

The script `/GKE/download_cos_kernel_headers.sh` fails when running from outside KubeArmor (probably because it was designed for a specific environment):

```
vagrant@kubearmor-dev-next:~/KubeArmor/GKE$ ./download_cos_kernel_headers.sh 
./download_cos_kernel_headers.sh: line 3: cd: /KubeArmor/GKE: No such file or directory
./download_cos_kernel_headers.sh: line 6: /media/root/etc/os-release: No such file or directory
--2021-06-19 14:31:35--  https://0x010.com/cos//kernel-headers.tgz
Resolving 0x010.com (0x010.com)... 143.248.38.112
Connecting to 0x010.com (0x010.com)|143.248.38.112|:443... connected.
ERROR: cannot verify 0x010.com's certificate, issued by 'CN=Synology Inc. CA,O=Synology Inc.,L=Taipei,C=TW':
  Unable to locally verify the issuer's authority.
    ERROR: certificate common name 'synology.com' doesn't match requested host name '0x010.com'.
To connect to 0x010.com insecurely, use `--no-check-certificate'.
tar (child): kernel-headers.tgz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

**Comment by nam-jaehyun** [comment]
@geyslan I was updating the certificates for 0x010.com. At that time, it seems that you tried to download kernel headers.
I updated the certificate; thus, there would no certificate issue now.

**Comment by nyrahul** [comment]
> > Yes, this is the pending compilation issue still open.
> > I am using version 96 and it still fails. I think I know the problem, but I am trying to understand the best way to fix it. The problem is the header files location.
> 
> Maybe adding rules to Vagrant to download and install a specific kernel version (image, modules and includes).

@geyslan, Looks like the easiest is to handle by downloading the images. Now I am thinking what is the point of using Cilium/Ubuntu-net-next kernel image if we are going to update the kernel itself!
I guess we will simply use the same ubuntu-bionic image and update the kernel img/mods/hdrs.

**Comment by geyslan** [comment]
> @geyslan I was updating the certificates for 0x010.com. At that time, it seems that you tried to download kernel headers.
> I updated the certificate; thus, there would no certificate issue now.

@nam-jaehyun, I see. Could this script be run from the shell? If so, inside of which directory?

> > Maybe adding rules to Vagrant to download and install a specific kernel version (image, modules and includes).
> 
> @geyslan, Looks like the easiest is to handle by downloading the images. Now I am thinking what is the point of using Cilium/Ubuntu-net-next kernel image if we are going to update the kernel itself!
> I guess we will simply use the same ubuntu-bionic image and update the kernel img/mods/hdrs.

@nyrahul, I agree. `ubuntu-bionic` + `kernel updating` seem to be the most practical way at this point, indeed.
