### ISSUE TITLE
Enhancement Request: Custom Icons for KubeArmor Website Social Media Links

### ISSUE THREAD

**Issue by Ayush9026** [kubearmor/KubeArmor#1560]
## Feature Request

**Short Description**

The Kubearmor website currently lacks custom icons for its social media links, specifically for GitHub, Twitter, Slack and LinkedIn. This issue is created to propose the addition of distinctive icons for these platforms, enhancing the visual appeal and user experience of the website.

**Is your feature request related to a problem? Please describe the use case.**

Having custom icons for each social media platform helps to create a more cohesive and visually appealing design for the KubeArmor website. It also makes it easier for users to identify and click on the links, improving the overall user experience

**Describe the solution you'd like**

1.Identify or design custom icons that represent each social media platform.
2.Integrate these custom icons into the KubeArmor website for the respective social media links.

**Additional Information:**

Website URL: [https://kubearmor.io/]

Screenshot: 

![Kubearmor website](https://github.com/kubearmor/KubeArmor/assets/114745463/fb3d22fb-8f69-4a24-a950-dbd4a6235b53)

**Expected Outcome:**

Upon completion of this enhancement, users visiting the KubeArmor website will experience a visually enhanced design with custom icons for the Twitter, YouTube, Podcast, and Forum links, contributing to a more engaging and user-friendly interface.

**Comment by partik03** [comment]
@Ayush9026 Can I take up this one?

**Comment by Ayush9026** [comment]
Yes @partik03 you can start.

**Comment by kranurag7** [comment]
Hey, thanks for the issue. IIRC, the website as of now is built and published by Netlify and that is not part of this repo. 
// cc @ShubhamTatvamasi if you can handle this internally.

**Comment by partik03** [comment]
@kranurag7  ig this issue belongs to the website repository and should be tranferred there also please let me know if I can  work on this one or will it be handled internally as you mentioned

**Comment by kranurag7** [comment]
I think the changes needs to be done on [this repo](https://github.com/kubearmor/kubearmor.io). 
Please check a similar issue here : https://github.com/kubearmor/kubearmor.io/issues/37

Feel free to send a pull request on that repo. 
Thank you.

**Comment by daemon1024** [comment]
Closing this because https://github.com/kubearmor/kubearmor.io/issues/37 is open
