### ISSUE TITLE
chore(ebpf): update libbpf to v1

### ISSUE THREAD

**Issue by daemon1024** [kubearmor/KubeArmor#1580]
We are maintaining quite old commit of libbpf as KubeArmor submodule.
We need this submodule for compiling our system monitor byte code on the fly.

`libbpf` is now v1, and some of the APIs have changed so the update is not straight forward. We need to update code in https://github.com/kubearmor/KubeArmor/blob/main/KubeArmor/BPF/system_monitor.c to remove usage of deprecated APIs.

**Comment by rootxrishabh** [comment]
A total of 3 vulnerabilities exist. 2 of them have been fixed upstream for latest, and 1 remains.
Fixed:
https://osv.dev/vulnerability/OSV-2021-1562
https://osv.dev/vulnerability/OSV-2021-1576
Unpached:
https://osv.dev/vulnerability/OSV-2023-877 ([issue](https://github.com/libbpf/libbpf/issues/730) opened at libbpf)

**Comment by rootxrishabh** [comment]
@daemon1024 should I raise an issue with libbpf for [unpached](https://osv.dev/vulnerability/OSV-2023-877)?

**Comment by daemon1024** [comment]
It's fine let's just use the latest released version for now.
We can update again when they fix it
