### ISSUE TITLE
Local Operator installation doesn’t change posture settings when supplied in kubearmorconfig

### ISSUE THREAD

**Issue by rootxrishabh** [kubearmor/KubeArmor#1590]
## Bug Report

**General Information**

- Environment description - K3s
- Kernel version - `Linux kubearmor-os-1 6.2.0-1019-gcp #21~22.04.1-Ubuntu SMP Thu Nov 16 18:18:34 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
- Orchestration system version in use - v1.23
- Link to relevant artifacts (policies, deployments scripts, ...)
- Target containers/pods

**To Reproduce**

1. Set default posture settings to block.
![image](https://github.com/kubearmor/KubeArmor/assets/73490663/ea039736-5779-4210-8eda-828550c77cb0)

2. Deploy Kubearmor using helm-based local deployment.
![image](https://github.com/kubearmor/KubeArmor/assets/73490663/d1efab95-acf2-4974-815a-c507dd05f8ee)

3. Confirm posture settings using `karmor probe`.
![image](https://github.com/kubearmor/KubeArmor/assets/73490663/1e334415-e83f-4526-9d49-970d2d9547f1)

**Expected behavior**
Karmor probe should confirm that Default Posture is set to block based for File, Capabilities, and Network but rather shows audit.
CC @rksharma95

**Comment by rksharma95** [comment]
Can you check posture values in kubearmor configmap `kubearmor-config`?

**Comment by rootxrishabh** [comment]
The configmap does show up the values as intended. However, kubearmor-config does set posture settings globally and should block all activity related to file, process, and network globally, right?
![image](https://github.com/kubearmor/KubeArmor/assets/73490663/c091e16f-0a06-4bb0-ab80-9c155a0ce7db)

**Comment by rksharma95** [comment]
@rootxrishabh  yes you're right, global posture should be set to `block` for process, file and network. have you tested the enforcement with an allow based policy?

**Comment by rootxrishabh** [comment]
Ok so it looks like the posture settings are working well!
Policy applied:
`apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-ubuntu-5-net-tcp-allow-curl
  namespace: default    
spec:
  severity: 8
  selector:
    matchLabels:
      app: nginx         
  network:
    matchProtocols:
    - protocol: tcp
      fromSource:
      - path: /usr/bin/curl
  action:
    Allow`
    
Result - 
`root@nginx-85b98978db-mpjxz:/# curl google.com
curl: (6) Could not resolve host: google.com`

So I guess `karmor probe` needs to be tweaked when working with operator-based deployment.

**Comment by rootxrishabh** [comment]
One last question, Basically posture is only enforced around a policy right? For example, all posture set to block without a policy doesn't deny all processes, network and file activities. Right?

**Comment by rksharma95** [comment]
> One last question, Basically posture is only enforced around a policy right? For example, all posture set to block without a policy doesn't deny all processes, network and file activities. Right?

yes default posture comes into picture with a allow based policy, ref: https://github.com/kubearmor/KubeArmor/blob/main/getting-started/default_posture.md

**Comment by rootxrishabh** [comment]
Thanks @rksharma95, will be opening an issue at kubearmor-client for the probe info.
