### ISSUE TITLE
Can only BPF-LSM support all the features of KubeArmor?

### ISSUE THREAD

**Issue by dejavudwh** [kubearmor/KubeArmor#1592]
I checked out the Kubernetes Support Matrix, but I'm still not quite sure if I can use all the features of KubeArmor if I only have BPF-LSM and no AppArmor or SELinux?

**Comment by daemon1024** [comment]
Hey @dejavudwh 

Currently there are 2 features that are not supported in BPF LSM
- MatchPatterns in Security Policies
- Capabilities support 

We already have a PR for Capabilities support #1538 which will land soon into KubeArmor.

That said, we utilise BPF LSM as the preferred enforcer even if SELinux and AppArmor are available.
The reason for that being some limitations with SELinux and AppArmor themselves
Document for reference https://github.com/kubearmor/KubeArmor/wiki/Enforcer-Feature-Parity

**Comment by dejavudwh** [comment]
@daemon1024 Thank you very much for your answer.

**Comment by daemon1024** [comment]
@dejavudwh happy to answer any more questions :D I am marking this issue as complete. Feel free to open more issues or ask us on our Slack :D
