### ISSUE TITLE
Update Go version to 1.21 across the repo

### ISSUE THREAD

**Issue by PrimalPimmy** [kubearmor/KubeArmor#1613]
We need to update our Go version to 1.21. Even in the kubearmor-client.

**Comment by PR229** [comment]
Hi! I would like to work on this. I was going through the documentation and noticed the below in the [development guide](https://github.com/kubearmor/KubeArmor/blob/main/contribution/development_guide.md) - 

"KubeArmor does not work with Docker Desktops on Windows and macOS". I'm currently on a Mac, would I have to get a Linux system to work on this first? Thanks!

**Comment by DelusionalOptimist** [comment]
@PR229 @Ayush9026 Thanks for showing interest. There is already a PR under review.

**Comment by Aryan-sharma11** [comment]
Closed with #1642
