### ISSUE TITLE
Kubearmor --> kubearmor-relay reconnection logic fails on error

### ISSUE THREAD

**Issue by seswarrajan** [kubearmor/KubeArmor#1631]
## Kubearmor-Relay reconnection logic is not working

**General Information**

- Environment : [k3s]
- Kernel version [6.5.13-7-MANJARO]

**To Reproduce**

1. Download latest kubearmor-client[karmor]
2. Install kubearmor and relay using karmor install
3. Leave it run for sometime.

**Observed behavior**
There is an error in kubearmor-relay stating that it fails to connect to 

**Expected behavior**
Even if the connection b/w Kubearmor and kubearmor-relay fails, there should be reconnect mechanism.

**Screenshots**

**Comment by seswarrajan** [comment]
[relayLogSaasDev.txt](https://github.com/kubearmor/KubeArmor/files/14291455/relayLogSaasDev.txt)

**Comment by daemon1024** [comment]
Fixed in kubearmor-relay-server stable release
https://github.com/kubearmor/kubearmor-relay-server/releases/tag/v1.2.2
