### ISSUE TITLE
Add CI workflow to push KubeArmor Artifacts to RedHat and AWS Marketplace

### ISSUE THREAD

**Issue by rksharma95** [kubearmor/KubeArmor#1634]
## Feature Request

**Short Description**

KubeArmor is currently available on AWS and RedHat Ecosystems. However, the process of publishing images for each stable release is presently a manual task. It would be great to automate this process by setting up the CI workflow.

Please review this [wiki page](https://github.com/kubearmor/KubeArmor/wiki/Update-KubeArmor-Marketplace-Releases) for a concise overview of the tasks at hand.

- [ ]  Implement the automation of pushing artifacts to RedHat and AWS.
- [ ]  The CI should create an issue when images are pushed, as manual intervention is still needed to update the listings.

**Comment by Ayush9026** [comment]
/ assign @Ayush9026
