### ISSUE TITLE
bug: kubearmor-operator helm chart doesn't remove kubearmor-controller

### ISSUE THREAD

**Issue by DelusionalOptimist** [kubearmor/KubeArmor#1638]
## Bug Report

**General Information**

- Environment description: k3s or any k8s
- Kernel version: N/A
- Orchestration system version in use: `v1.23.9+k3s1`
- Link to relevant artifacts: kuebarmor-operator helm charts
- Target containers/pods: kubearmor-controller

**To Reproduce**

1. Install KubeArmor using kubearmor-operator helm chart.
2. Uninstall the helm release.
3. You'll see that kubearmor-controller pod stays installed and goes into error.

**Reason**
The secret containing the cert for mutating admission webhook, mounted as a volume on the controller, is deleted before kubearmor-controller deployment is.

**Expected behavior**

Cleanup should be ordered.

**Screenshots**
![image](https://github.com/kubearmor/KubeArmor/assets/54525605/9e4f4b3f-c02b-4fc1-8cae-b5f5069b3b71)

**Comment by rksharma95** [comment]
code to add operator as owner for controller deployment is missing with control loop here:
https://github.com/kubearmor/KubeArmor/blob/1e31e1ae46aa99629410239afac16e98ada1fa7d/pkg/KubeArmorOperator/internal/controller/resources.go#L390
