### ISSUE TITLE
mount procfs instead of using hostpid

### ISSUE THREAD

**Issue by daemon1024** [kubearmor/KubeArmor#1688]
## Feature Request

KubeArmor needs access to host's procfs to stich container and real time process information we get from eBPF. 

**Is your feature request related to a problem? Please describe the use case.**

Sharing pid ns with host is more risky than just accessing procfs.

**Describe the solution you'd like**

- We can mount and set procfs to readonly maybe alleviating a lot of risks involded with mounting procfs
- Add configuration in KubeArmor to support custom path prefix for procfs

Related #1186

**Comment by yp969803** [comment]
@daemon1024 is the issue open to work?

**Comment by daemon1024** [comment]
Yes @yp969803

**Comment by yp969803** [comment]
@daemon1024,  so, at the time of pod mutation i have to check the hostPID spec is true, if it is true, i have to do it false, and mount /proc volume in the pod ?
