### ISSUE TITLE
KubeArmor daemonset pods failing to deploy successfully on x86 Ubuntu EKS-A Baremetal Env. 

### ISSUE THREAD

**Issue by mikemcd3912** [kubearmor/KubeArmor#1698]
## Bug Report

**General Information**

- Environment description: EKS Anywhere Baremetal
- Kernel version (run `uname -a`) Linux 5.4.0-162-generic #179-Ubuntu SMP Mon Aug 14 08:51:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- Orchestration system version in use: 1.27
- Link to relevant artifacts: https://github.com/aws-samples/eks-anywhere-addons/tree/main/eks-anywhere-common/Addons/Partner/KubeArmor
- Target containers/pods: Kubearmor daemonset pods 
- Link to Paralell issue in EKS-Anywhere-Addons repo: https://github.com/aws-samples/eks-anywhere-addons/issues/232

**To Reproduce**

1. Deploy Kubearmor on EKS Anywhere baremetal environment matching the above via flux

The Kubearmor controller and relay pods start up and enter a 'ready' state, but the daemonset pods for all nodes enter a CrashLoopBackOff state shortly after deployment . The logs for the daemonset Kuberarmor container in the daemonset pods show that shortly after start the container begins to drop events due to replay timeouts. The failing deployment also causes the openebs PVC provisioner to fail to create new claims, preventing other workloads on the cluster from obtaining storage necessary to their successful function and deployment

**Expected behavior**

Kubearmor agent is expected to fully deploy and report ready

**Screenshots**
![312890779-29af9155-22fb-4f0c-8afc-6d97e050837e](https://github.com/kubearmor/KubeArmor/assets/61101829/b8942f33-b24a-41bd-a8ba-78ff4da1a280)

![312889863-e22f9144-e0a1-4e43-af08-e327efaa0c9e](https://github.com/kubearmor/KubeArmor/assets/61101829/6f583799-10ee-4035-92f9-0a33a00cd0c6)

[kubearmor.logs.txt](https://github.com/kubearmor/KubeArmor/files/14668061/kubearmor.logs.txt)

**Comment by mikemcd3912** [comment]
Opening for tracking per the request of a member of the EKS-Anywhere Partner Addons team 
@daemon1024  @rksharma95

**Comment by elamaran11** [comment]
@daemon1024 Is this fixed?

**Comment by daemon1024** [comment]
Hey @elamaran11 , Yes this is fixed in our recent releases. Hope we can get https://github.com/aws-samples/eks-anywhere-addons/pull/235 merged to upgrade our version on EKS-A

**Comment by elamaran11** [comment]
@daemon1024 Thanks for the confirmation. we will be validating this soon. Thanks!

**Comment by mikemcd3912** [comment]
@daemon1024 Thanks for the attention on this issue! We've validated the updated PR and have just merged the PR that fixed the issue.
