### ISSUE TITLE
Github Action Tasks for KubeArmor

### ISSUE THREAD

**Issue by daemon1024** [kubearmor/KubeArmor#170]
- [x] Build
		`make build`
- [x] Code Coverage
	- codecov
- [x] CodeQL Analysis / GoSec
- [x] Go related Checks
	- [x] lint
	- [x] fmt
- [x] Testing
	- [x] Unit Test
			`make testall`
	- [x] Auto testing framework
			https://github.com/accuknox/KubeArmor/blob/master/contribution/testing_guide.md
		- [x] For different kernel versions
			Github Actions allows to specify ubuntu 18.04/ ubuntu 20.04 as such, I am not sure if we can configure kernel versions
- [x] File Headers

**Comment by nam-jaehyun** [comment]
@daemon1024 Can you check ci-go.yml again?

**Comment by daemon1024** [comment]
Hey @nam-jaehyun , I looked through the fails earlier. It's due to the missing go.sum file.
Since `go.sum` was in the .gitignore earlier there was no change introduced by `go mod tidy` but now since it's not there, due to the missing file, go mod tidy introduces a change and hence failing the test.

**Comment by daemon1024** [comment]
I should detail out the error message more. I will send in a patch with go.sum and some refinements in ci, if it's fine with you?

**Comment by nam-jaehyun** [comment]
I updated ci-go.yml a bit. Please check the file again and update it if some updates are needed

**Comment by nam-jaehyun** [comment]
did you miss committing something?
![image](https://user-images.githubusercontent.com/67940721/127457989-2e3d9142-e3b8-4983-b696-07e44c8e87ad.png)

**Comment by daemon1024** [comment]
Need `make build-test` before running the tests now.
This will generate the testable binary.

**Comment by nam-jaehyun** [comment]
Is it possible to have a check logic or an option for that?
While we need the coverage in the GitHub action, we don't need that in a local development environment.

**Comment by daemon1024** [comment]
Makes sense. I will modify the script accordingly.
