### ISSUE TITLE
Snitch should not mount entire host rootfs

### ISSUE THREAD

**Issue by DelusionalOptimist** [kubearmor/KubeArmor#1705]
## Feature Request

**Short Description**
KubeArmor snitch currently mounts the entire rootfs of the host - [ref](https://github.com/kubearmor/KubeArmor/blob/main/pkg/KubeArmorOperator/internal/controller/resources.go#L258-L266) 

**Describe the solution you'd like**

We should specify the host path volume mounts at a more granular level. For example:
- For detecting container runtimes `/var/run` should be enough
- For apparmor profiles `/etc/apparmor.d` should be enough

and so on...

We may use older KubeArmor daemonset for reference on the same.

**Comment by rksharma95** [comment]
`/var/run, /run` to detect container runtime
`/sys/kernel/ `for btf, securityfs
`/sys/module/apparmor/parameters/enabled` ref: https://kubernetes.io/docs/tutorials/security/apparmor/#before-you-begin
`/var/lib/kubelet/seccomp` for seccomp

**Comment by Utkar5hM** [comment]
I would like to work on this.

**Comment by DelusionalOptimist** [comment]
Fixed in https://github.com/kubearmor/KubeArmor/pull/1658

**Comment by DelusionalOptimist** [comment]
@Utkar5hM please checkout issues with "good first issue" or "help wanted" label and let us know so that we can assign. Thanks : )
