### ISSUE TITLE
Keep eBPF maps separately even though KubeArmor is restarted

### ISSUE THREAD

**Issue by nam-jaehyun** [kubearmor/KubeArmor#171]
There could be some possibilities that KubeArmor is restarted due to unexpected reasons.
In this case, KubeArmor will lose the container-awareness stored in eBPF maps
and it cannot map the system events with the corresponding containers.
To prevent such a problem, KubeArmor needs to maintain eBPF maps separately (e.g., /sys/fs/bpf/...).

**Comment by oneiro-naut** [comment]
Hi @nam-jaehyun. We would need to modify this maps like[1]
https://github.com/accuknox/KubeArmor/blob/be1a0e39f7931ef6fe74f24b7f7ef35013f83ee8/KubeArmor/BPF/system_monitor.c#L84
to a pinned one? 
`BPF_TABLE_PINNED("hash", u32, u32, pid_ns_map, 1024, "/sys/fs/bpf/pid_ns_map");`

**Comment by nam-jaehyun** [comment]
@oneiro-naut Yes, something like that. However, let's think about this later.
Once the previous tasks are done, we can think about this and some related tasks as next steps.

**Comment by oneiro-naut** [comment]
Sure @nam-jaehyun. I understand.

**Comment by nam-jaehyun** [comment]
KubeArmor previously needed to catch the init process of a container to get the container information.
Since KubeArmor doesn't need the init process of a container to get the information, we don't need to address this issue.
