### ISSUE TITLE
Vagrantfile only checks for RSA algorithm for SSH keys

### ISSUE THREAD

**Issue by Ankurk99** [kubearmor/KubeArmor#175]
Currently Vagrantfile to provision kubearmor-dev checks only for ~/.ssh/id_rsa.pub, but it can cause error because not all users are using rsa algorithm for ssh keygeneration (maybe ed25519) that way the ssh keys will be saved as id_ed25519.pub and not id_rsa.pub. 
This can be corrected if we can generate id_rsa.pub if it doesn't exist.

**Comment by nam-jaehyun** [comment]
@Ankurk99 Is there any update on this issue?
