### ISSUE TITLE
Lost events coming from eBPF-based monitor

### ISSUE THREAD

**Issue by nam-jaehyun** [kubearmor/KubeArmor#193]
Currently, there are some cases that KubeArmor misses some events coming from the eBPF monitor.
This usually happens when a host has limited resources.
In addition, KubeArmor cannot sometimes generate alerts due to such losses.
We may be able to reproduce such losses by running the automated testing framework several times
and see the failed test cases.

**Comment by oneiro-naut** [comment]
@nam-jaehyun Is it true for ContainerLogs as well? 
https://github.com/kubearmor/KubeArmor/blob/f4fba7cf59b62145fffeff5c63d74bd89fbd96b2/KubeArmor/feeder/feeder.go#L553
I tried to get these logs using kubearmor-logclient and didn't get some of them.

**Comment by dku-boanlab** [comment]
I think that's because you didn't add the 'kubearmor-visibility' annotation.

**Comment by nam-jaehyun** [comment]
@oneiro-naut Can you take this issue?

**Comment by oneiro-naut** [comment]
@nam-jaehyun Sure thing. Thanks.

**Comment by nam-jaehyun** [comment]
For testing, I suggest this way.

1. Run KubeArmor
```
~/KubeArmor/KubeArmor$ sudo -E ./kubearmor -logPath=/tmp/kubearmor.log -logFilter=all -enableHostPolicy
```

2. Run the runtime test script
```
~/KubeArmor/tests$ ./test-scenarios-in-runtime.sh
```
- See if there are any failed cases

3. Repeatedly run the runtime test script even though there was no failed case in the previous execution.
```
~/KubeArmor/tests$ ./test-scenarios-in-runtime.sh
```
- See if there are any failed cases
- At this step, please do not re-run KubeArmor since we also want to see if KubeArmor works during repeated container deployments and deletions

4. After running the script multiple times, check the KubeArmor log (/tmp/kubearmor.log) and debug the issue.

**Comment by nam-jaehyun** [comment]
Observation 1

```
{"timestamp":1626262451,"updatedTime":"2021-07-14T11:34:11.271803Z","hostName":"kubearmor-dev","containerID":"cebb1075bfbecfd386869234acb72e51347a52222198207c3f028e34e6278828","hostPid":18361,"ppid":18332,"pid":1,"uid":0,"type":"ContainerLog","source":"/entrypoint.sh","operation":"Network","resource":"sa_family=AF_UNIX sun_path=/var/run/nscd/socket","data":"syscall=SYS_CONNECT fd=3","result":"No such file or directory"}
```
I got the container ID, but namespace and pod names were not added.

Observation 2
```
{"timestamp":1626262537,"updatedTime":"2021-07-14T11:35:37.717876Z","hostName":"kubearmor-dev","namespaceName":"multiubuntu","podName":"ubuntu-1-deployment-5d6b975744-qptct","containerID":"f47010ab3fc041f105e2fe23a97f18403fdd2027aeceabe6e4b81b7673cb9d21","containerName":"ubuntu-1-container","hostPid":22961,"ppid":22957,"pid":99,"uid":0,"type":"ContainerLog","source":"runc:[2:INIT]","operation":"Process","resource":"/bin/bash -c sleep 1","data":"syscall=SYS_EXECVE","result":"Passed"}
```
the source is "runc:[2:INIT]"; thus, this log is considered as ContainerLog, not MatchedPolicy.

Observation 3
```
{"timestamp":1626263744,"updatedTime":"2021-07-14T11:55:44.195132Z","hostName":"kubearmor-dev","containerID":"e3464b25c60ad14e007f5edc2db9ede6229faafd7aff9f0a3786f2bebbb902fd","hostPid":3132,"ppid":31512,"pid":102,"uid":0,"type":"ContainerLog","source":"/bin/cat /credentials/password","operation":"File","resource":"/credentials/password","data":"syscall=SYS_OPENAT fd=-100 flags=O_RDONLY","result":"Permission denied"}
```
The permission was denied due to the given policy, but namespace and pod names were not added; thus, this alert is considered as ContainerLog, not MatchedPolicy.

**Comment by oneiro-naut** [comment]
@nam-jaehyun Thanks a lot. I am going to look into this. I think the mismatches and wrong metadata in logs will need some changes in the feeder and monitor modules. I will debug this and try to synchronize with the observations you have made.

**Comment by oneiro-naut** [comment]
>At this step, please do not re-run KubeArmor since we also want to see if KubeArmor works during repeated container deployments and deletions.

@nam-jaehyun I did follow these steps and didn't re-run Kubearmor, it runs just fine upon repeated container deployments and deletion. I repeated the runtime test script multiple times(4 times at least) and strangely each time test_8(action: allowwithaudit) and test_9(action: allow) were failing consistently. Other than these 2 tests sometimes other tests failed as well.
Then I re-run kubearmor once and repeated the runtime test again. Test 8 and 9 failed all these times.

**Comment by oneiro-naut** [comment]
> Observation 2
> 
> ```
> {"timestamp":1626262537,"updatedTime":"2021-07-14T11:35:37.717876Z","hostName":"kubearmor-dev","namespaceName":"multiubuntu","podName":"ubuntu-1-deployment-5d6b975744-qptct","containerID":"f47010ab3fc041f105e2fe23a97f18403fdd2027aeceabe6e4b81b7673cb9d21","containerName":"ubuntu-1-container","hostPid":22961,"ppid":22957,"pid":99,"uid":0,"type":"ContainerLog","source":"runc:[2:INIT]","operation":"Process","resource":"/bin/bash -c sleep 1","data":"syscall=SYS_EXECVE","result":"Passed"}
> ```
> 
> the source is "runc:[2:INIT]"; thus, this log is considered as ContainerLog, not MatchedPolicy.

I think commit 4c582cad19485f035a921d69fac270a2b6148665 should handle this. I will check these.

**Comment by oneiro-naut** [comment]
> Observation 1
> 
> ```
> {"timestamp":1626262451,"updatedTime":"2021-07-14T11:34:11.271803Z","hostName":"kubearmor-dev","containerID":"cebb1075bfbecfd386869234acb72e51347a52222198207c3f028e34e6278828","hostPid":18361,"ppid":18332,"pid":1,"uid":0,"type":"ContainerLog","source":"/entrypoint.sh","operation":"Network","resource":"sa_family=AF_UNIX sun_path=/var/run/nscd/socket","data":"syscall=SYS_CONNECT fd=3","result":"No such file or directory"}
> ```
> 
> I got the container ID, but namespace and pod names were not added.
> Observation 3
> 
> ```
> {"timestamp":1626263744,"updatedTime":"2021-07-14T11:55:44.195132Z","hostName":"kubearmor-dev","containerID":"e3464b25c60ad14e007f5edc2db9ede6229faafd7aff9f0a3786f2bebbb902fd","hostPid":3132,"ppid":31512,"pid":102,"uid":0,"type":"ContainerLog","source":"/bin/cat /credentials/password","operation":"File","resource":"/credentials/password","data":"syscall=SYS_OPENAT fd=-100 flags=O_RDONLY","result":"Permission denied"}
> ```
> 
> The permission was denied due to the given policy, but namespace and pod names were not added; thus, this alert is considered as ContainerLog, not MatchedPolicy.

Hi @nam-jaehyun. I have done some analysis. Please let me know your thoughts on this.
These 2 are probably caused when we haven't added containers[1] info to dm.Containers[] and some log is generated before that. That would leave pod name and namespace name empty. 
[1]
https://github.com/kubearmor/KubeArmor/blob/18abb32c27ba24d258811786c09728060b9c920b/KubeArmor/monitor/logUpdate.go#L24
This can observed by checking the time of log generation and time of docker added event being received. 
Observation 1:
The early log for container e4400143ba6c is received before the added event.[Note: this log is actually the ./entrypoint.sh script it is very early point]
```
{"timestamp":1626414490,"updatedTime":"2021-07-16T05:48:10.482456Z","hostName":"kubearmor-dev-next","containerID":"e4400143ba6c30bdedf93d2a1801a870975781a7b0437263362ea95d0c7bd77a","hostPid":13575,"ppid":13557,"pid":1,"uid":0,"type":"ContainerLog","source":"/entrypoint.sh","operation":"File","resource":"/dev/tty","data":"syscall=SYS_OPENAT fd=-100 flags=O_RDWR|O_NONBLOCK","result":"No such device or address"}

```
Docker container added event(it will actually add the container in the dm.Containers[] map)
```
2021-07-16 05:48:10.512118	INFO	Detected a container (added/e4400143ba6c)
```
As  can be seen log is received earlier than it is actually added to dm.Containers[] map therefore it doesn't have the namespacename and pod name metadata which is actually received later.

The log received later than this have the namespacename and pod name in them.
``` 
{"timestamp":1626414490,"updatedTime":"2021-07-16T05:48:10.512841Z","hostName":"kubearmor-dev-next","namespaceName":"multiubuntu","podName":"ubuntu-1-deployment-5d4c98c574-96nnr","containerID":"e4400143ba6c30bdedf93d2a1801a870975781a7b0437263362ea95d0c7bd77a","containerName":"k8s_ubuntu-1-container_ubuntu-1-deployment-5d4c98c574-96nnr_multiubuntu_42f77831-dd51-4012-982f-cbd10bb8b718_0","hostPid":13612,"ppid":1,"pid":10,"uid":0,"type":"ContainerLog","source":"/usr/bin/netserver","operation":"Network","resource":"sa_family=AF_INET sin_port=12865 sin_addr=0.0.0.0","data":"syscall=SYS_BIND fd=4","result":"Address already in use"}
```
There needs to be a synchronization between these 2 events(ie receiving docker/containerd added event for container and logs received from them). If we will received added event later(which mostly happen and cant be avoided at least for ./entrypoint.sh events for containers).

**Comment by nam-jaehyun** [comment]
@oneiro-naut I updated some code related to this issue (#207). Please check the changes.

Checkpoints:
1. As you mentioned, there could be a sync issue; thus, we need a backup code to solve this issue.
2. I'm not sure why, but alerts are generated with ContainerLog instead of MatchedPolicy. it looks strange, and it rarely happens I think. Anyway, we need a backup code to solve this issue.
3. We need to clearly figure out when KubeArmor cannot generate alerts and logs. When I tested KubeArmor with already deployed containers, I couldn't get any logs. Please check this again.
```
Terminal 1) ~/KubeArmor/KubeArmor$ make run-with-host
Terminal 2) ~/KubeArmor/tests$ ./test-scenarios-with-multiubuntu.sh
                    Wait until all tests are done (all tests are passed at this point)
Terminal 1) Ctrl+C
Terminal 1) ~/KubeArmor/KubeArmor$ make run-with-host
Terminal 2) ~/KubeArmor/tests$ ./test-scenarios-with-multiubuntu.sh
                    tests are no longer passed...
Terminal 2) ~/KubeArmor/examples/multiubuntu$ kubectl delete -f .
```

```
Terminal 1) ~/KubeArmor/KubeArmor$ make run-with-host
Terminal 2) ~/KubeArmor/examples/multiubuntu$ kubectl apply -f .
                    Wait until all pods are ready
Terminal 1) Ctrl+C
Terminal 1) ~/KubeArmor/KubeArmor$ make run-with-host
Terminal 2) ~/KubeArmor/tests$ ./test-scenarios-with-multiubuntu.sh
                    tests are failed...
Terminal 2) ~/KubeArmor/examples/multiubuntu$ kubectl delete -f .
Terminal 1) Ctrl+C
```

In addition, please find corner cases if possible.

**Comment by oneiro-naut** [comment]
@nam-jaehyun The reason for matchedPolicy to be returned as containerLog seems to be caused because of missing matchpolicy structs which ideally should be added for each pod. We are calling it here:
https://github.com/kubearmor/KubeArmor/blob/155b35d3bfb0c8057b3aa102bf8f6d7a0cb42530/KubeArmor/core/kubeUpdate.go#L235
But I debugged and found that its not called each time we add security policy(or update security policy) and so even when the result is not passed we skip matching because we don't even have the secPolicy to match against.https://github.com/kubearmor/KubeArmor/blob/155b35d3bfb0c8057b3aa102bf8f6d7a0cb42530/KubeArmor/feeder/policyMatcher.go#L678

This seems to be caused because there is no particular synchronization between pod events and container events. The call to LogFeeder.UpdateSecurity() policy can be missed if pod added/modified events happen before corresponding container added/modified events happen. I am looking into this.

**Comment by nam-jaehyun** [comment]
@oneiro-naut I see. We need to fix those points. Please take an action for them.

**Comment by oneiro-naut** [comment]
@nam-jaehyun I fixed most of the corner cases and bugs. I think now its the limitation of test script in how it uses grep command to detect the logs. I checked in the log file all the MatchedPolicy were there but they can't be detected by the scripts whenever the source is `runc:[2:INIT]` in the log source field. I think it has to do with how test framework defines the cmd files for scenarios especially the `condition`. Basically now only the scripts need to have some modifications otherwise things seem to be working fine to me. I have fixed these issues as of yet:

1. MatchedPolicy being labelled as ContainerLogs.
2. Already deployed logs sometimes missing in the log file.
3. VisibilityEnabled and EnablePolicy variables weren't being initialized properly at some places:
Varible is being used to initialize but its value is later. I switched the sequence of these two and similar for EnablePolicy.
https://github.com/kubearmor/KubeArmor/blob/f6e7893f7c3c797f1535facc6fcae893159e0a56/KubeArmor/core/kubeUpdate.go#L73
https://github.com/kubearmor/KubeArmor/blob/f6e7893f7c3c797f1535facc6fcae893159e0a56/KubeArmor/core/kubeUpdate.go#L94
4. Variable being used but was not being initialized:
https://github.com/kubearmor/KubeArmor/blob/f6e7893f7c3c797f1535facc6fcae893159e0a56/KubeArmor/feeder/feeder.go#L532
5. Missing logs due to synchronization issues between k8sHandler and containerHandlers.

I have shared kubearmor.test and kubearmor.log file for the 2 cases(one with all tests passing and other with runc as the source in MatchedPolicy logs). Let me know your thoughts on the test script issue.

**Comment by nam-jaehyun** [comment]
@oneiro-naut where can I see your changes?

**Comment by oneiro-naut** [comment]
@nam-jaehyun  Should I raise a draft pr? I have logs and tests files as well that I can share. I have found cause of one issue just now basically what happens is whenever runc:[2:INIT] is the source of log. The SYS_OPENAT and SYS_OPEN system calls do not happen and so log.Operation where it is supposed to be "File" it becomes a "Process". And thats why is not matched by the grep command in the test scripts which match using operation info provided in the cmd file even though we get the corresponding MatchedPolicy logs in the kubearmor.log file. Good thing is that we are not missing any MatchedPolicy log in the log file itself now.
https://github.com/kubearmor/KubeArmor/blob/1094b8baa8ef8cae3898cee214bf03c32081e5ba/KubeArmor/monitor/logUpdate.go#L131
I am thinking how to tackle this.I think we should use to `policyName` as well here and in case of log.source as `runc INIT` we can completely ignore Operation field while matching its log and rely on policyName.:
https://github.com/kubearmor/KubeArmor/blob/1094b8baa8ef8cae3898cee214bf03c32081e5ba/tests/test-scenarios-in-runtime.sh#L114
We are currently using only these fields to match and missing policyName:
https://github.com/kubearmor/KubeArmor/blob/1094b8baa8ef8cae3898cee214bf03c32081e5ba/tests/test-scenarios-in-runtime.sh#L303

**Comment by nam-jaehyun** [comment]
@oneiro-naut can you raise a draft PR? let me review the changes.
