### ISSUE TITLE
Enable HostLogs to be pushed to LogQueue

### ISSUE THREAD

**Issue by oneiro-naut** [kubearmor/KubeArmor#194]
HostLogs are mentioned here in feeder module:
https://github.com/kubearmor/KubeArmor/blob/f4fba7cf59b62145fffeff5c63d74bd89fbd96b2/KubeArmor/feeder/feeder.go#L553
Which are later pushed to LogQueue here:
https://github.com/kubearmor/KubeArmor/blob/f4fba7cf59b62145fffeff5c63d74bd89fbd96b2/KubeArmor/feeder/feeder.go#L584
But in policyMatcher.go they aren't being returned. https://github.com/kubearmor/KubeArmor/blob/f4fba7cf59b62145fffeff5c63d74bd89fbd96b2/KubeArmor/feeder/policyMatcher.go#L948

We do have ContainerLogs which are returned and passed to feeder.PushLog function.
https://github.com/kubearmor/KubeArmor/blob/f4fba7cf59b62145fffeff5c63d74bd89fbd96b2/KubeArmor/feeder/policyMatcher.go#L923

We should add a similar condition in case of Host as well. This might allow us to get baseline policy violation events on Host(example already present LSM policies enforced by sources other than KubeArmor on host) as HostLogs which can later be received by the kubearmor-logclient.

**Comment by nam-jaehyun** [comment]
@oneiro-naut There would be no host log at this point because we will have too many logs.

**Comment by oneiro-naut** [comment]
@nam-jaehyun Would that be the case even if we restricted ourselves to `log.result != "passed"`? Actually I made some changes in my local branch to check using an AppArmor policy applied on host and the logs were still not captured.
I added another condition inside this block:https://github.com/kubearmor/KubeArmor/blob/f4fba7cf59b62145fffeff5c63d74bd89fbd96b2/KubeArmor/feeder/policyMatcher.go#L949
```
if log.Result != "Passed" {
 log.type = "HostLog"
 return log
}
```

**Comment by nam-jaehyun** [comment]
@oneiro-naut you mean that you added those lines at around 962 to get host logs?

**Comment by oneiro-naut** [comment]
@nam-jaehyun Exactly.

**Comment by nam-jaehyun** [comment]
then, can you also add the same thing at 934?
```
} else if log.Result != "Passed" {
 log.type = "ContainerLog"
 return log
}
```

**Comment by oneiro-naut** [comment]
@nam-jaehyun it wud allowing return non passed logs as containerlogs irrespective of visibility?

**Comment by nam-jaehyun** [comment]
@oneiro-naut yes, you're right. we will see passed logs only when visibility is enabled, but we will see the failed container and host logs all the time.

**Comment by oneiro-naut** [comment]
Hi @nam-jaehyun . I was debugging the bpf system_monitor code and have 1 doubt. Can you tell me why have we used this condition here when adding element to pid_ns_map for host(ie with MONITOR_HOST enabled). https://github.com/kubearmor/KubeArmor/blob/b6df53ce1a910224c3aeba117361e6b9ecf52f14/KubeArmor/BPF/system_monitor.c#L166
I used lsns and found out that every process executed on host is getting non 0 pid namespace inode number(I am able to dump ns_id by adding a bpf_trace_printk() just before this line and matched them with pid namespace on the vm host). I executed several commands and they are all caught. Because of this condition though none of them are being pushed further and no entries are being added to the pid_ns_map removing this condition makes it work.

**Comment by geyslan** [comment]
> I used lsns and found out that every process executed on host is getting non 0 pid namespace inode number(I am able to dump ns_id by adding a bpf_trace_printk() just before this line and matched them with pid namespace on the vm host). I executed several commands and they are all caught. Because of this condition though none of them are being pushed further and no entries are being added to the pid_ns_map removing this condition makes it work.

@oneiro-naut you can find the host namespace pid using (in host):

```bash
❯ readlink /proc/self/ns/pid
pid:[4026531836]

❯ lsns | grep -E 'pid.*systemd'
4026531836 pid       144    1500 uzu  /usr/lib/systemd/systemd --user
```

As you said, there is no namespace pid=0.

The namespace pid is being accessed directly by:

https://github.com/kubearmor/KubeArmor/blob/b6df53ce1a910224c3aeba117361e6b9ecf52f14/KubeArmor/BPF/system_monitor.c#L105

I don't know if all kernel (bpf) versions allow this direct reading. @nam-jaehyun do you know about this?

In addition to your suggestion of the `if (pid_ns != 0)` removal, I suggest changing the `get_task_pid_ns_id()` to something like this:

```c
static __always_inline u32 get_task_pid_ns_id(struct task_struct *task)
{
	struct nsproxy *nsp;
	struct pid_namespace *pns;	
	struct ns_common nsc;

	bpf_probe_read(&nsp, sizeof(nsp), &task->nsproxy);
	bpf_probe_read(&pns, sizeof(pns), &nsp->pid_ns_for_children);
	bpf_probe_read(&nsc, sizeof(nsc), &pns->ns);
	
	return nsc.inum;
}
```

**Comment by nam-jaehyun** [comment]
@oneiro-naut The reason that we had "if (pid_ns != 0) {" is because we deploy two eBPF monitors (one is for containers and the other is for the host). In the case of the monitor for the host, I wanted to filter out any processes for containers; thus, I added that line.

**Comment by nam-jaehyun** [comment]
@geyslan I think "readlink /proc/[hostpid]/ns/pid" would allow us to map container IDs and the PID namespaces in system events coming from the eBPF monitor, which means that it can be used for the alert generation for already-deployed containers as well.

@oneiro-naut The overall mapping process with already-deployed containers would be like this.
system event --> pidns + hostpid
--> readlink /proc/[hostpid]/ns/pid + {cat /proc/[hostpid]/cgroup | cat /proc/[hostpid]/cmdline} --> pidns + container ID

**Comment by oneiro-naut** [comment]
> @oneiro-naut The reason that we had "if (pid_ns != 0) {" is because we deploy two eBPF monitors (one is for containers and the other is for the host). In the case of the monitor for the host, I wanted to filter out any processes for containers; thus, I added that line.

@nam-jaehyun  But even for the host pid_ns we get non 0 value. So it's filtering away even the host events. Are we supposed to get 0 for the host pid_ns?

**Comment by dku-boanlab** [comment]
@oneiro-naut any suggestion for this?

**Comment by oneiro-naut** [comment]
@nam-jaehyun. I thought of one idea. What if we create an helper function similar to `bpf_get_current_comm(char *buf, int size_of_buf)` to somehow get the command name of the detected pid_ns event's init process(pid == 1) and using something like __builtin_memcmp(or anything to compare strings I am not sure) check if it's equal to "/sbin/init" maybe this way we can trace host pid_ns and differentiate it from other pid_ns which something else as their init process command? What are your thoughts on this?

**Comment by oneiro-naut** [comment]
@nam-jaehyun other way can be using pinned map with different names for host_pid_ns_map and container_pid_ns_map for container. And sharing these 2 maps between both ebpf processes so that when we get a potential host pid_ns we can check whether it's already in container_pid_ns or not. If it's found there we won't add it to host_pid_ns_map. Although I am not sure whether we can share the ebpf maps between 2 ebpf programs like this. And there will be race conditions as well in this possible solution so we would need to make sure that there is some form of synchronization so that container ebpf code always executes before host ebpf monitor code. If we are able to do something like this it can even enable us to get already-deployed containers because we will ensure that host_pid_ns_map and container_pid_ns_map are mutually disjoint.

**Comment by geyslan** [comment]
> @nam-jaehyun. I thought of one idea. What if we create an helper function similar to `bpf_get_current_comm(char *buf, int size_of_buf)` to somehow get the command name of the detected pid_ns event's init process(pid == 1) and using something like __builtin_memcmp(or anything to compare strings I am not sure) check if it's equal to "/sbin/init" maybe this way we can trace host pid_ns and differentiate it from other pid_ns which something else as their init process command? What are your thoughts on this?

I assume that `host ns_pid` could be discovered in userspace (KA), as it would be trivial to just call a `readlink` for `/proc/self/ns/pid` in KA, or to get it programatticaly using `stat()` and feed the proposed pinned map.

Concerning racing conditions, from libbpf we can make use of global variables, so a `lock` flag could be the solution.

What do you think?

**Comment by oneiro-naut** [comment]
@nam-jaehyun init pid_ns(host pid_ns) inode number is a constant defined in kernel. So rather than comparing with 0 we will just need to compare with this value defined [here](https://elixir.bootlin.com/linux/latest/source/include/linux/proc_ns.h#L46). I tested it and now we get host events in ebpf code. Container entries are dropped and not added just as required.

**Comment by dku-boanlab** [comment]
@oneiro-naut good to know!

**Comment by oneiro-naut** [comment]
@nam-jaehyun Now since we know that host pid_ns is known we can solve already-deployed containers extra entries(which were all host entries(kubelet, nice, etc.) except for containerd which I am not sure how to resolve).

**Comment by geyslan** [comment]
> @nam-jaehyun init pid_ns(host pid_ns) inode number is a constant defined in kernel. So rather than comparing with 0 we will just need to compare with this value defined [here](https://elixir.bootlin.com/linux/latest/source/include/linux/proc_ns.h#L46). I tested it and now we get host events in ebpf code. Container entries are dropped and not added just as required.

Just the best solution! 👍

0xEFFFFFFCU = 4026531836
