### ISSUE TITLE
Support OpenShift

### ISSUE THREAD

**Issue by nam-jaehyun** [kubearmor/KubeArmor#221]
KubeArmor will eventually need to support OpenShift too.

**Comment by anutosh491** [comment]
Hello @nam-jaehyun , I recently got onboard with KubeArmor and started contributing to good first issues . Along with other interesting projects that KubeArmor has to offer for the LFX mentorship program this summer ..... I am also interested in this project . I am comfortable with Go and K8s as of now . Could you share any relevant links , resources which I could look up for this ? Also what would you suggest me to do to get more familiar with this project !

**Comment by Ankurk99** [comment]
Done as a part of LFX mentorship
