### ISSUE TITLE
Event loss due to buffer overwrites in systemMonitor.c

### ISSUE THREAD

**Issue by oneiro-naut** [kubearmor/KubeArmor#249]
Steps to reproduce this issue:
Method 1: requires HostPolicy enabled
1. Run kubearmor with hostpolicy enabled.
```
vagrant@kubearmor-dev:~/KubeArmor/KubeArmor$ make && make run-with-host
```
2. Run watch command on host.(any watch command works)
```
vagrant@kubearmor-dev:~$ watch ps -au
```
3. Wait. After sometime kubearmor crashes with the following error.
```
2021-08-12 05:49:37.628234	INFO	Initialized KubeArmor
panic: runtime error: makeslice: len out of range

goroutine 69 [running]:
github.com/kubearmor/KubeArmor/KubeArmor/monitor.readByteSliceFromBuff(0x19f6f20, 0xc001532120, 0xffffffffa00b0a0a, 0x2610d58, 0x159f2e0, 0xc001ae489c, 0x0, 0x0)
	/home/vagrant/KubeArmor/KubeArmor/monitor/syscallParser.go:102 +0x72
github.com/kubearmor/KubeArmor/KubeArmor/monitor.readStringFromBuff(0x19f6f20, 0xc001532120, 0x0, 0x0, 0x0, 0x0)
	/home/vagrant/KubeArmor/KubeArmor/monitor/syscallParser.go:116 +0x169
github.com/kubearmor/KubeArmor/KubeArmor/monitor.readArgFromBuff(0x19f6f20, 0xc001532120, 0xc00118b3b0, 0x17adfa0, 0x15975a0, 0xc00118b3b0)
	/home/vagrant/KubeArmor/KubeArmor/monitor/syscallParser.go:961 +0x225
github.com/kubearmor/KubeArmor/KubeArmor/monitor.GetArgs(0xc001532120, 0xc000000002, 0x1a36c58, 0x2610d58, 0x15975a0, 0xc00118b3b0, 0x0)
	/home/vagrant/KubeArmor/KubeArmor/monitor/syscallParser.go:1038 +0x85
github.com/kubearmor/KubeArmor/KubeArmor/monitor.(*SystemMonitor).TraceSyscall(0xc0005006c0)
	/home/vagrant/KubeArmor/KubeArmor/monitor/systemMonitor.go:449 +0x338
created by github.com/kubearmor/KubeArmor/KubeArmor/core.(*KubeArmorDaemon).MonitorSystemEvents
	/home/vagrant/KubeArmor/KubeArmor/core/kubeArmor.go:238 +0x97
Makefile:37: recipe for target 'run-with-host' failed
make: *** [run-with-host] Error 2
```
Method 2: 
1. Run kubearmor.
```
vagrant@kubearmor-dev:~/KubeArmor/KubeArmor$ make && make run
```
2. Deploy multiubuntu pods.
3. Run watch command inside any pod using kubectl exec.
```
vagrant@kubearmor-dev:~$ kubectl exec -ti -n multiubuntu ubuntu-2-deployment-bc58cf44-g9jg7 -- bash
root@ubuntu-2-deployment-bc58cf44-g9jg7:/# watch ps -aux
```
4. Run watch in another pod using kubectl exec.
```
vagrant@kubearmor-dev:~$ kubectl exec -ti -n multiubuntu ubuntu-1-deployment-5d6b975744-h4cws -- bash
root@ubuntu-1-deployment-5d6b975744-h4cws:/# watch ps -aux
```
5. Wait. After sometime kubearmor crashes with the following error.
```
2021-08-12 06:00:30.411934	INFO	Initialized KubeArmor
panic: runtime error: makeslice: len out of range

goroutine 22 [running]:
github.com/kubearmor/KubeArmor/KubeArmor/monitor.readByteSliceFromBuff(0x19f6f20, 0xc0005f0900, 0xffffffff8d0b0a0a, 0x2610d58, 0x159f2e0, 0xc00187cb14, 0x0, 0x0)
	/home/vagrant/KubeArmor/KubeArmor/monitor/syscallParser.go:102 +0x72
github.com/kubearmor/KubeArmor/KubeArmor/monitor.readStringFromBuff(0x19f6f20, 0xc0005f0900, 0x0, 0x0, 0x0, 0x0)
	/home/vagrant/KubeArmor/KubeArmor/monitor/syscallParser.go:116 +0x169
github.com/kubearmor/KubeArmor/KubeArmor/monitor.readArgFromBuff(0x19f6f20, 0xc0005f0900, 0xc00220b540, 0x17adfa0, 0x15975a0, 0xc00220b540)
	/home/vagrant/KubeArmor/KubeArmor/monitor/syscallParser.go:961 +0x225
github.com/kubearmor/KubeArmor/KubeArmor/monitor.GetArgs(0xc0005f0900, 0xc000000002, 0x1a36c58, 0x2610d58, 0x15975a0, 0xc00220b540, 0x0)
	/home/vagrant/KubeArmor/KubeArmor/monitor/syscallParser.go:1038 +0x85
github.com/kubearmor/KubeArmor/KubeArmor/monitor.(*SystemMonitor).TraceSyscall(0xc000144ea0)
	/home/vagrant/KubeArmor/KubeArmor/monitor/systemMonitor.go:449 +0x338
created by github.com/kubearmor/KubeArmor/KubeArmor/core.(*KubeArmorDaemon).MonitorSystemEvents
	/home/vagrant/KubeArmor/KubeArmor/core/kubeArmor.go:238 +0x97
Makefile:27: recipe for target 'run' failed
make: *** [run] Error 2
```

**Comment by nam-jaehyun** [comment]
Yes, it sometimes happens since we don't have a lock for the buffer between the userspace and the ebpf.
The problem is that system events can overwrite the buffer before the userspace reads it.
Then, when the userspace reads the buffer, it cannot find the end of a string (null), causing such an issue.

**Comment by nam-jaehyun** [comment]
@oneiro-naut by the way, this issue is not the one specific to the watch command.

**Comment by oneiro-naut** [comment]
@nam-jaehyun It isn't. This is the buffer management issue that was discussed earlier. I just wanted to identify the best possible way to reproduce it. These set of steps always ensure a crash. I used watch because that way we get a lot of events and so the probability of events arriving almost at the same time and overwriting the other is very high. The same happens with other commands refreshing their data at a high rate example `screen`, `top` and even editor commands like `vim`(for example using vim on a file that is constantly being updated by something else).

**Comment by oneiro-naut** [comment]
> Yes, it sometimes happens since we don't have a lock for the buffer between the userspace and the ebpf.
> The problem is that system events can overwrite the buffer before the userspace reads it.
> Then, when the userspace reads the buffer, it cannot find the end of a string (null), causing such an issue.

I see. So basically there is a race condition here.

**Comment by oneiro-naut** [comment]
> The problem is that system events can overwrite the buffer before the userspace reads it.
> Then, when the userspace reads the buffer, it cannot find the end of a string (null), causing such an issue.

@nam-jaehyun Here something similar is happening due to buffer overwrite. We parse string argument length here:https://github.com/kubearmor/KubeArmor/blob/309713f0e8a34d50b93b354bfe5bac9922a6d75b/KubeArmor/monitor/syscallParser.go#L112

When overwrite occurs sometimes this value is negative. Then we use this value to allocate a slice here:
https://github.com/kubearmor/KubeArmor/blob/309713f0e8a34d50b93b354bfe5bac9922a6d75b/KubeArmor/monitor/syscallParser.go#L102
Notice that we don't check if len is negative and that's how we get this crash. I also noticed that in systemMonitor.c each time we got the buffer overwrite following condition failed:
```
    int sz = bpf_probe_read_str(&(bufs_p->buf[*off + sizeof(int)]), MAX_STRING_SIZE, ptr);
    if (sz > 0) {
```

To avoid the crash I just added a safety condition in the commit ec6a493. However this will only prevent the crash and we simply drop the malformed buffer. But the overwrite causes lots of events to be dropped(this might explain why we the test scripts sometimes fail randomly). For this I thought about a possible solution:
This assumes that we convert the current percpu_array from single element array to double element array. The idea is to use the other index if current index is being used by some event. We currently have:
```
BPF_PERCPU_ARRAY(bufs, bufs_t, 1);
BPF_PERCPU_ARRAY(bufs_offset, u32, 1);
```
We can change it to:
```
BPF_PERCPU_ARRAY(bufs, bufs_t, 2);
BPF_PERCPU_ARRAY(bufs_offset, u32, 2);
```
and add a new percpu_array to store counters:
```
BPF_PERCPU_ARRAY(bufs_counter, u8, 2);
```
1. We use `__sync_lock_test_and_set`(or some atomic fetch and set function) to fetch current counter value and set it to 1. 
2. We check fetched current value of `bufs_counter` for index=0:
https://github.com/kubearmor/KubeArmor/blob/309713f0e8a34d50b93b354bfe5bac9922a6d75b/KubeArmor/BPF/system_monitor.c#L605
If its 1 we check it for index=1. If that's unused(ie it is 0) we use it for that event. If both indices have counter 1 we simply drop the event by returning(this way we will ensure that no buffers are overwritten).
2. Once we are done with submitting the buffer to perf_output we can reset counter for current index to 0.https://github.com/kubearmor/KubeArmor/blob/309713f0e8a34d50b93b354bfe5bac9922a6d75b/KubeArmor/BPF/system_monitor.c#L616

With this solution works we will ensure 2 things:
1. No buffer will be overwritten.
2. Number of events dropped will be reduced. 

I am not sure if we can use `__sync_lock_test_and_set` in ebpf code.

**Comment by oneiro-naut** [comment]
Hi @nam-jaehyun . I was doing some research and earlier I thought that perhaps we could just make another percpu_array to store an integer as a lock variable. But then I haven't been able to find a way to use "fetch and set" like instruction on map elements (although some atomic bpf instructions seem to be added from kernel version 4.20 onward). If such instructions were available to use we could simply use them for implementing locks. I did check `bpf_spin_lock` but it's currently restricted to normal bpf_array and hash elements. Also it was introduced in kernel version 5.4 and still not available in bcc. Which made me think that would there be such a problem if we used simple bpf_array instead of percpu_array? I think even in case of the usual bpf_array we will still face such problems? Finally, since we can't use locks so I thought maybe we can minimize the overwrites using bpf_queue to store context, arguments and other information. Please let me know if I am thinking in the right direction.
