### ISSUE TITLE
eventAuditor: NETNEXT kernel without proper bpftool

### ISSUE THREAD

**Issue by geyslan** [kubearmor/KubeArmor#262]
**`event-auditor` branch**

The `bpftool` is needed to dump the vmlinux.h from the kernel. The NETNEXT kernel version `5.13.0-051300rc3-generic` doesn't provide a proper packaged bpftool.

**Comment by geyslan** [comment]
Officially, the most up-to-date ubuntu package that contains bpftool is `linux-tools-common` 5.11.0-20.21+21.10.1.

https://packages.ubuntu.com/search?keywords=linux-tools-common

Probably for this kernel:
https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.11.21/amd64/

**Comment by geyslan** [comment]
> Probably for this kernel:
> https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.11.21/amd64/

I've tested the 5.11.21 kernel to get along with the bpftool. A full Ubuntu upgrade was required for clang and bpftool work correctly. In other words, the `bionic` version has been upgraded to `impish`. I suppose it would be easier to just start with impish release. 

@nyrahul @nam-jaehyun Is there any requirements that don't allow this?

**Comment by nam-jaehyun** [comment]
@geyslan yes, NETNEXT=1 just increases the kernel version (5.13).
you can add an option to change the base image. the current base image is ubuntu/bionic64 (i.e., ubuntu 18.04).
according to the option, you can use ubuntu/impish64 (i.e., ubuntu 20.10).

**Comment by nam-jaehyun** [comment]
@geyslan also, please add the required packages (e.g., linux-tools-common) in setup.sh.

**Comment by nam-jaehyun** [comment]
I updated the NETNEXT option.
NETNEXT=0 -> ubuntu/bionic64 (ubuntu 18.04, kernel 4.15)
NETNEXT=1 -> ubuntu/impish64 (ubuntu 20.10, kernel 5.11)
NETNEXT=2 -> ubuntu/focal64 (ubuntu 20.04, kernel 5.4)

@geyslan can you add any required packages (e.g., linux-tools-common) in contribution/self-managed-k8s/setup.sh?
