### ISSUE TITLE
KubeArmor: NETNEXT={0,2} haven't BTF support

### ISSUE THREAD

**Issue by geyslan** [kubearmor/KubeArmor#271]
`NETNEXT=0` => `bionic`  kernel 4.15.0-144
`NETNEXT=2` => `focal` kernel 5.4.0-81

This lack could be solved using `pahole` and `llvm-objcopy` to feed libbpf.

Error:

```
vagrant@kubearmor-dev:~/KubeArmor/KubeArmor$ make
/home/vagrant/KubeArmor/KubeArmor/patch.sh
go: downloading github.com/iovisor/gobpf v0.2.0
cd /home/vagrant/KubeArmor/KubeArmor; make -C /home/vagrant/KubeArmor/KubeArmor/eventAuditor/BPF
make[1]: Entering directory '/home/vagrant/KubeArmor/KubeArmor/eventAuditor/BPF'
INFO: compiling include/libbpf.a
make[2]: Entering directory '/home/vagrant/KubeArmor/KubeArmor/eventAuditor/BPF/libbpf/src'
make[2]: pkg-config: Command not found
  MKDIR    staticobjs
  CC       bpf.o
  CC       btf.o
  CC       libbpf.o
  CC       libbpf_errno.o
  CC       netlink.o
  CC       nlattr.o
  CC       str_error.o
  CC       libbpf_probes.o
  CC       bpf_prog_linfo.o
  CC       xsk.o
  CC       btf_dump.o
  CC       hashmap.o
  CC       ringbuf.o
  CC       strset.o
  CC       linker.o
  CC       gen_loader.o
  AR       libbpf.a
  INSTALL  bpf.h libbpf.h btf.h libbpf_common.h libbpf_legacy.h xsk.h bpf_helpers.h bpf_helper_defs.h bpf_tracing.h bpf_endian.h bpf_core_read.h skel_internal.h
  INSTALL  libbpf.pc
  INSTALL  libbpf.a
make[2]: Leaving directory '/home/vagrant/KubeArmor/KubeArmor/eventAuditor/BPF/libbpf/src'
Makefile:79: *** ERROR: kernel does not seem to support BTF.  Stop.
make[1]: Leaving directory '/home/vagrant/KubeArmor/KubeArmor/eventAuditor/BPF'
Makefile:21: recipe for target 'build' failed
make: *** [build] Error 2
```

```bash
vagrant@kubearmor-dev:~/KubeArmor/KubeArmor$ uname -a
Linux kubearmor-dev 4.15.0-144-generic #148-Ubuntu SMP Sat May 8 02:33:43 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by nam-jaehyun** [comment]
BTF is supported from 5.8 and above. that's why those kernels do not have BTF features.

**Comment by geyslan** [comment]
_/sys/kernel/btf/vmlinux appeared in 5.4 kernel (upstream version). If you see it on 4.18, that means someone backported the changes. But for BPF CO-RE (which I assume is what you are referring to) to work, kernel itself doesn't need to "support BTF", it just needs to have .BTF data built-in inside its vmlinux binary image, and that image needs to be in one of the supported locations (see [0]). Starting from 5.2 kernel CONFIG_DEBUG_INTO_BTF=y is supported with adds .BTF section as part of the kernel build process._

_But one could technically add .BTF by using pahole tool (part of dwarves package) even before that, as long as vmlinux image contains DWARF information._

[Re: [iovisor-dev] Which is oldest linux kernel version that can support BTF? #bcc](https://www.mail-archive.com/iovisor-dev@lists.iovisor.org/msg01709.html)

**Comment by nam-jaehyun** [comment]
For the BTF features, we use ubuntu/impish.
Let's not consider the older versions at this point.
