### ISSUE TITLE
Security Policy gives a Segmentation Fault 

### ISSUE THREAD

**Issue by vaibhavmew** [kubearmor/KubeArmor#287]
Policy Type
file
path + fromSource(path)

**example1.yaml**

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: example1
  namespace: multiubuntu
spec:
  severity: 5
  message: "No message"
  selector:
    matchLabels:
      container: ubuntu-2
  file:
    matchPaths:
    - path: /home/user1/a.txt
      fromSource:
      - path: /home/user1/run_a.sh
  action:
    Block

**run_a.sh** contains
`#!/bin/bash
cat /home/user1/a.txt`

The policy should stop the access of a.txt from run_a.sh but instead gives Segmentation Fault.

AppArmor profile
#include <tunables/global>

profile kubearmor-multiubuntu-ubuntu-2-container flags=(attach_disconnected,mediate_deleted) {
  ## == PRE START == ##
  #include <abstractions/base>
  umount,
  file,
  network,
  capability,
  ## == PRE END == ##

  ## == POLICY START == ##
  /home/user1/run_a.sh cx,
  profile /home/user1/run_a.sh {
    /home/user1/run_a.sh rix,
    ## == PRE START (/home/user1/run_a.sh) == ##
    #include <abstractions/base>
    umount,
    network,
    capability,
    ## == PRE END (/home/user1/run_a.sh) == ##

    ## == POLICY START (/home/user1/run_a.sh) == ##
    deny /home/user1/a.txt rw,
    ## == POLICY END (/home/user1/run_a.sh) == ##

    ## == POST START (/home/user1/run_a.sh) == ##
    /lib/x86_64-linux-gnu/{*,**} r,

    deny @{PROC}/{*,**^[0-9*],sys/kernel/shm*} wkx,
    deny @{PROC}/sysrq-trigger rwklx,
    deny @{PROC}/mem rwklx,
    deny @{PROC}/kmem rwklx,
    deny @{PROC}/kcore rwklx,

    deny mount,

    deny /sys/[^f]*/** wklx,
    deny /sys/f[^s]*/** wklx,
    deny /sys/fs/[^c]*/** wklx,
    deny /sys/fs/c[^g]*/** wklx,
    deny /sys/fs/cg[^r]*/** wklx,
    deny /sys/firmware/efi/efivars/** rwklx,
    deny /sys/kernel/security/** rwklx,
    ## == POST END (/home/user1/run_a.sh) == ##
  }
  ## == POLICY END == ##

  ## == POST START == ##
  /lib/x86_64-linux-gnu/{*,**} r,

  deny @{PROC}/{*,**^[0-9*],sys/kernel/shm*} wkx,
  deny @{PROC}/sysrq-trigger rwklx,
  deny @{PROC}/mem rwklx,
  deny @{PROC}/kmem rwklx,
  deny @{PROC}/kcore rwklx,

  deny mount,

  deny /sys/[^f]*/** wklx,
  deny /sys/f[^s]*/** wklx,
  deny /sys/fs/[^c]*/** wklx,
  deny /sys/fs/c[^g]*/** wklx,
  deny /sys/fs/cg[^r]*/** wklx,
  deny /sys/firmware/efi/efivars/** rwklx,
  deny /sys/kernel/security/** rwklx,
  ## == POST END == ##
}

**Comment by oneiro-naut** [comment]
@vaibhavmew Can you share the output for following command:`sudo cat /var/log/audit/audit.log|grep apparmor|tail -15` when you trigger this segmentation fault. Can you also share some screenshot of the segmentation fault.

**Comment by vaibhavmew** [comment]
@oneiro-naut 
**Output of the command that you mentioned**
`type=AVC msg=audit(1629955756.305:639): apparmor="DENIED" operation="ptrace" profile="kubearmor-multiubuntu-ubuntu-3-container" pid=1414 comm="readlink" requested_mask="trace" denied_mask="trace" peer="kubearmor-multiubuntu-ubuntu-3-container"
type=AVC msg=audit(1629955759.354:640): apparmor="DENIED" operation="ptrace" profile="kubearmor-multiubuntu-ubuntu-1-container" pid=1563 comm="readlink" requested_mask="trace" denied_mask="trace" peer="kubearmor-multiubuntu-ubuntu-1-container"
type=AVC msg=audit(1629955762.344:641): apparmor="DENIED" operation="ptrace" profile="kubearmor-multiubuntu-ubuntu-4-container" pid=1727 comm="readlink" requested_mask="trace" denied_mask="trace" peer="kubearmor-multiubuntu-ubuntu-4-container"
type=AVC msg=audit(1629955766.658:642): apparmor="DENIED" operation="ptrace" profile="kubearmor-multiubuntu-ubuntu-2-container" pid=1962 comm="readlink" requested_mask="trace" denied_mask="trace" peer="kubearmor-multiubuntu-ubuntu-2-container"
type=AVC msg=audit(1629955876.717:643): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="kubearmor-multiubuntu-ubuntu-2-container" pid=3309 comm="apparmor_parser"
type=SYSCALL msg=audit(1629955876.717:643): arch=c000003e syscall=1 success=yes exit=8921 a0=6 a1=55fe4d146f60 a2=22d9 a3=0 items=0 ppid=3301 pid=3309 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="apparmor_parser" exe="/sbin/apparmor_parser" key=(null)
type=AVC msg=audit(1629955876.725:644): apparmor="STATUS" operation="profile_load" profile="unconfined" name="kubearmor-multiubuntu-ubuntu-2-container///home/user1/run_a.sh" pid=3309 comm="apparmor_parser"
type=SYSCALL msg=audit(1629955876.725:644): arch=c000003e syscall=1 success=yes exit=25833 a0=6 a1=55fe4d14b380 a2=64e9 a3=0 items=0 ppid=3301 pid=3309 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="apparmor_parser" exe="/sbin/apparmor_parser" key=(null)
type=AVC msg=audit(1629956023.763:645): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="kubearmor-multiubuntu-ubuntu-2-container" pid=4445 comm="apparmor_parser"
type=SYSCALL msg=audit(1629956023.763:645): arch=c000003e syscall=1 success=yes exit=8601 a0=6 a1=562d5a5ede20 a2=2199 a3=0 items=0 ppid=4444 pid=4445 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="apparmor_parser" exe="/sbin/apparmor_parser" key=(null)
type=AVC msg=audit(1629956084.193:646): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="kubearmor-multiubuntu-ubuntu-2-container" pid=4959 comm="apparmor_parser"
type=SYSCALL msg=audit(1629956084.193:646): arch=c000003e syscall=1 success=yes exit=8921 a0=6 a1=55f570ac0f60 a2=22d9 a3=0 items=0 ppid=4958 pid=4959 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="apparmor_parser" exe="/sbin/apparmor_parser" key=(null)
type=AVC msg=audit(1629956084.229:647): apparmor="STATUS" operation="profile_replace" info="same as current profile, skipping" profile="unconfined" name="kubearmor-multiubuntu-ubuntu-2-container///home/user1/run_a.sh" pid=4959 comm="apparmor_parser"
type=SYSCALL msg=audit(1629956084.229:647): arch=c000003e syscall=1 success=yes exit=25833 a0=6 a1=55f570ac5380 a2=64e9 a3=0 items=0 ppid=4958 pid=4959 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="apparmor_parser" exe="/sbin/apparmor_parser" key=(null)
type=AVC msg=audit(1629956120.091:648): apparmor="DENIED" operation="file_mmap" profile="kubearmor-multiubuntu-ubuntu-2-container///home/user1/run_a.sh" name="/bin/bash" pid=5269 comm="run_a.sh" requested_mask="rm" denied_mask="rm" fsuid=0 ouid=0
`

**Comment by oneiro-naut** [comment]
```
type=AVC msg=audit(1629956120.091:648): apparmor="DENIED" operation="file_mmap" profile="kubearmor-multiubuntu-ubuntu-2-container///home/user1/run_a.sh" name="/bin/bash" pid=5269 comm="run_a.sh" requested_mask="rm" denied_mask="rm" fsuid=0 ouid=0 
```
@daemon1024 We will need to allow file mmap explicitly here in the base rule:
```
profile /home/user1/run_a.sh {
/home/user1/run_a.sh rix,
```
so that `rix` becomes something like `rmix` not sure if the syntax is correct(to allow file_mmap here). There is one more doubt that I have isn't `r` enough to specify that we are also allowing file_mmap operation as well.

**Comment by daemon1024** [comment]
`r` provides with `mmap_r` and `ix` provides with `mmap_x` permission, I don't think we should be needing to add `m` explicitly. But regardless even after adding those permissions it seems to be seg faulting.

**Comment by nam-jaehyun** [comment]
the given policy itself doesn't make sense to me.

**Comment by vaibhavmew** [comment]
The policy is working now.
