### ISSUE TITLE
matchPath with fromSource does not work as expected

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#296]
## Bug Report

**General Information**
`matchPath` and the corresponding `fromSource` construct is supposed to only operate on a given path and the source binary. However, it currently seems the blocking happens across all the paths for that `fromSource`. In the example, I wanted to block `cat` access to `/var/www/html/wp-config.php` path. But it results in blocking all the paths.

- Environment description (GKE, VM-Kubeadm, vagrant-dev-env, minikube, microk8s, ...)
VM-Kubeadm

- Kernel version (run `uname -a`)
Linux vbox1804 4.15.0-154-generic # 161-Ubuntu SMP Fri Jul 30 13:04:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- Orchestration system version in use (e.g. `kubectl version`, ...)
1.22.1

- Link to relevant artifacts (policies, deployments scripts, ...)
[ksp-wordpress-block-config.yaml](https://github.com/kubearmor/KubeArmor/blob/master/examples/wordpress-mysql/security-policies/ksp-wordpress-block-config.yaml)

- Target containers/pods
[Wordpress-mysql example](https://github.com/kubearmor/KubeArmor/tree/master/examples/wordpress-mysql)

**To Reproduce**
1. Install [wordpress-mysql app](https://github.com/kubearmor/KubeArmor/tree/master/examples/wordpress-mysql)
2. Apply policy [ksp-wordpress-block-config.yaml](https://github.com/kubearmor/KubeArmor/blob/master/examples/wordpress-mysql/security-policies/ksp-wordpress-block-config.yaml)
3. `kubectl exec -it -n wordpress-mysql <wordpress-POD> -- bash`
4. [WORKING] `cat /var/www/html/wp-config.php` should result in permission denied
5. [NOT WORKING]`cat /etc/host.conf` should not result in permission denied

**Expected behavior**
`cat /etc/host.conf` or cat-ting any other file should not result in permission denied but currently, it does.

**Comment by daemon1024** [comment]
I will take this up :)

**Comment by nam-jaehyun** [comment]
During the update of the AppArmor logic, I fixed the 'fromSource' issue.
@daemon1024 can you double-check if this issue is solved with the latest code?

**Comment by daemon1024** [comment]
Seems to be working fine on latest code
```
vagrant@kubearmor-dev ~> kubectl exec -n wordpress-mysql wordpress-dbcd8b97b-pn85s -it -- bash
root@wordpress-dbcd8b97b-pn85s:/var/www/html# cat /var/www/html/wp-config.php
cat: /var/www/html/wp-config.php: Permission denied
root@wordpress-dbcd8b97b-pn85s:/var/www/html# cat /etc/host.conf
multi on 										##Fixed
root@wordpress-dbcd8b97b-pn85s:/var/www/html# exit
exit
```
