### ISSUE TITLE
KVM Service - Handling of Resource Definitions

### ISSUE THREAD

**Issue by nandhued** [kubearmor/KubeArmor#314]
The VM/bare-metal nodes will have a corresponding KVM-resource in the controlling k8s cluster. This resource will keep a mapping of labels in the context of the external VM.

- [ ] Create
- [ ] Update
- [ ] Delete

_Start-Date:_ 03/02/2021
_Effort Estimate:_ **3.25**
- [ ] Design - 0.25
- [ ] Coding - 2
- [ ] Unit Test - 1

**Comment by seswarrajan** [comment]
https://github.com/kubearmor/KVMService/pull/3 
Merged in above pull request
