### ISSUE TITLE
Vagrant Box: bcc installation failed

### ISSUE THREAD

**Issue by elfadel** [kubearmor/KubeArmor#325]
During the execution of vagrant up, the bcc installation failed on my side. See the image below:
![Screenshot from 2021-09-05 13-42-23](https://user-images.githubusercontent.com/27213369/132167341-745e5603-8ab5-452e-9980-e728a791d8f2.png)

**Comment by elfadel** [comment]
I fix it by updating the bcc installation procedure n the vagrant script. I will submit a PR soon.

**Comment by nam-jaehyun** [comment]
I haven't seen such errors while I'm creating the Vagrant setup almost per day.
Can you describe the issue and your solution?

**Comment by elfadel** [comment]
Oki. Currently, I am testing the solution for `focal64` and `bionic64` boxes. I will provide more details at the end of tests.

**Comment by elfadel** [comment]
Closing this issue. After several tests, it comes out that the crashing during the `vagrant up` is due to the size of memory I allocate to the VM.
