### ISSUE TITLE
KVM Service - Watcher for Policy

### ISSUE THREAD

**Issue by seswarrajan** [kubearmor/KubeArmor#372]
- [ ] Add
- [ ] Delete
- [ ] Update 
by the user and sending updates to the corresponding ext workload

_Start-Date:_
_Effort Estimate:_ **3.5**
- [ ] Design - 0.5
- [ ] Coding - 2
- [ ] Unit Test - 1

**Comment by nyrahul** [comment]
@seswarrajan , can we close this issue? I believe we have the code here?

**Comment by seswarrajan** [comment]
Merged PR into MAIN
