### ISSUE TITLE
ContainerMonitor: use libbpf instead of bcc

### ISSUE THREAD

**Issue by nam-jaehyun** [kubearmor/KubeArmor#38]
bcc requires kernel headers and it seems unstable when we test KubeArmor on several environments (with different kernel versions). Thus, we're planning to change the base of the container monitor from bcc to libbpf.

**Comment by oneiro-naut** [comment]
@nam-jaehyun It seems to be a bcc issue(#195) because of which passing enableHostPolicy=true to kubearmor fails with error:
```
vagrant@kubearmor-dev:~/KubeArmor/KubeArmor$ kubectl logs -n kube-system kubearmor-dwg4h
2021-07-08 09:26:38.617147	INFO	Started to serve gRPC-based log feeds
2021-07-08 09:26:38.619524	INFO	Initializing an eBPF program
2021-07-08 09:26:47.890546	INFO	Initialized the eBPF program
cannot attach kprobe, Resource busy
2021-07-08 09:26:48.153857	ERROR	Failed to initialize the system monitor
github.com/kubearmor/KubeArmor/KubeArmor/log.Err
	/usr/src/KubeArmor/KubeArmor/log/logger.go:99
github.com/kubearmor/KubeArmor/KubeArmor/feeder.(*Feeder).Err
	/usr/src/KubeArmor/KubeArmor/feeder/feeder.go:423
github.com/kubearmor/KubeArmor/KubeArmor/core.KubeArmor
	/usr/src/KubeArmor/KubeArmor/core/kubeArmor.go:354
main.main
	/usr/src/KubeArmor/KubeArmor/main.go:60
runtime.main
	/usr/local/go/src/runtime/proc.go:204
```
The issue seems to be fixed now in bcc. Strangely its happening in our case.

**Comment by geyslan** [comment]
For this, we already have a codepath with libbpf: https://github.com/kubearmor/KubeArmor/tree/event-auditor/KubeArmor/eventAuditor/BPF

And as I've mentioned here https://github.com/kubearmor/KubeArmor/pull/270#issuecomment-900325919, it can be moved to other path.

**Comment by akshatagarwl** [comment]
@nam-jaehyun Can I work on this?
