### ISSUE TITLE
Vagrant: Kubernetes (kubelet) failed to start with containerd as CRI runtime

### ISSUE THREAD

**Issue by elfadel** [kubearmor/KubeArmor#450]
When KubeArmor is launched (from vagrant script) with `containerd` as container runtime, k8s cannot work properly. A subsequent error message is: `KubeletNotReady              [container runtime status check may not have completed yet, container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized]`.

**Comment by nam-jaehyun** [comment]
@elfadel This is not an issue of KubeArmor. This is kind of an issue about an environment that we didn't support so far.
As you know, we only supported K8s with docker for the vagrant environment at this time.
It would be nice if you can make changes to support a vagrant environment with both docker and containerd.

**Comment by elfadel** [comment]
> @elfadel This is not an issue of KubeArmor. This is kind of an issue about an environment that we didn't support so far.

Right @nam-jaehyun, this is not a KubeArmor issue.

**Comment by elfadel** [comment]
> As you know, we only supported K8s with docker for the vagrant environment at this time.
> It would be nice if you can make changes to support a vagrant environment with both docker and containerd.

Done. I will make a PR soon.
