### ISSUE TITLE
doc updates for karmor cli

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#464]
## Bug Report

KubeArmor now has an explicit CLI tool [karmor](https://github.com/kubearmor/kubearmor-client) that can be used for installation/uninstall/logs/status/sysdump etc. The documentation in kubearmor needs to be updated to use this.

**Changes to handle**

- [ ] [Deployment Guide](https://github.com/kubearmor/KubeArmor/blob/master/getting-started/deployment_guide.md)
- [ ] [EKS Guide](https://github.com/kubearmor/KubeArmor/blob/master/deployments/EKS/README.md)

**Comment by sayantani11** [comment]
@nyrahul for starters, can I take this? It will help me in understanding the project better.

**Comment by nyrahul** [comment]
> @nyrahul for starters, can I take this? It will help me in understanding the project better.

Thank you. Issue is now assigned to you.

The documentation in general needs to outline following steps:

1. Installation/Uninstallation (using [karmor cli](https://github.com/kubearmor/kubearmor-client))
2. Using a demo application and applying a security policy using kubearmor. ([Multiubuntu example](https://github.com/kubearmor/KubeArmor/blob/master/getting-started/security_policy_examples.md) will help here)
3. Getting KubeArmor logs. This involves two steps:
     a. Using kubectl port-forward with kubearmor-relay service
     b. `karmor log` will then connect to this forwarded port.
4. Prepare sample videos for each deployment platform.

**Comment by nyrahul** [comment]
This issue was extensively discussed in the community meeting on 4th Nov 2021.

Key points that came out:
1. We need sample documentation for integrating with KubeArmor alerts/telemetry. This would be a separate issue.
2. For individual k8s platforms we can create a sample video using asciinema. Again his would be a separate issue.
