### ISSUE TITLE
create alias for kubectl in development environment

### ISSUE THREAD

**Issue by navarrothiago** [kubearmor/KubeArmor#466]
It would be good to have some alias inside development environment. I'd suggest the following ones:

```
alias k='kubectl'
# complete -F __start_kubectl k
alias ks='kubectl -n kube-system'
# complete -F __start_kubectl ks
alias wk='watch -n2 kubectl get pods -o wide'
alias wks='watch -n2 kubectl -n kube-system get pods -o wide'
alias wka='watch -n2 kubectl get all --all-namespaces -o wide'
```

**Comment by nam-jaehyun** [comment]
I feel these aliases are related to Kubernetes rather than KubeArmor.
Do we need to provide these aliases by KubeArmor?

**Comment by nyrahul** [comment]
The choice of aliases is very subjective. Different users will have different choices. It is easily possible for the user to replicate their list of aliases in Kubearmor's vagrant login.
