### ISSUE TITLE
KubeAmor installation is missing in Multiubuntu guide

### ISSUE THREAD

**Issue by navarrothiago** [kubearmor/KubeArmor#469]
If we check [Multiubuntu](https://github.com/kubearmor/KubeArmor/blob/master/examples/multiubuntu.md), there is no instructions for KubeAmor installation. I was testing using [development environment](https://github.com/kubearmor/KubeArmor/blob/master/contribution/development_guide.md) and there is any step related to CRDs deployments and I faced some error. Maybe we can put some "Be sure that you have already deployed KubeArmor using [Deployment Guide](https://github.com/kubearmor/KubeArmor/blob/master/getting-started/deployment_guide.md).

**Comment by nyrahul** [comment]
The user is expected to have gone through the "Getting Started Guide" before using any examples. Also, the README documentation has undergone a significant revamp.
