### ISSUE TITLE
KubeArmor Documentation

### ISSUE THREAD

**Issue by daemon1024** [kubearmor/KubeArmor#477]
Currently the KubeArmor documentation is scattered and difficult to follow.
This is a meta issue to track and improve KubeArmor documentation by collecting the docs into an organised manner with proper references and leveraging [collapsible sections](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections)

Following is the planned structure of the documents. Feel free to comment on the referenced issues if you are interested in helping us out, or comment on this thread if you want to propose something.

**Page 1**
- [ ] Cluster Setup
    - [x] Support Matrix #732 
	- [x] #492
	- [x] #493
	- [x] #494
		- [x] Containerd
		- [x] Docker	
	- [x] #495
	- [x] #496
	- [x] #497
- [ ] KubeArmor Installation Documentation
	- [ ] `karmor` - #464 
	- [x] #498
- [ ] What's next
	- [ ] Example App and Policy Enforcement
    - [ ] Troubleshooting Guide

**Page 2**
- [ ] Example App and Sample Polcies
- [ ] What's Next
	- [ ] Policy Example Document
	- [ ] Observe KubeArmor events
    - [ ] Troubleshooting Guide

**Page 3**
- [ ] KubeArmor event observation
	- [ ]  `karmor log`
- [ ] What's next
    - [ ] Alerts/Telemetry API
    - [ ] Troubleshooting Guide
 
**Page 4**
- [x] #499
	- [ ] karmor sysdymp
	- [ ] karmor probe - https://github.com/kubearmor/kubearmor-client/issues/19
	- [ ] kubearmor slack and github
- [ ] System Requirements?

**Page 5**
- [ ] VM/Bare-Metal
	- [ ] Requirements
	- [ ] Setup
	- [ ] Usage

More consideration points:
- Adding more asciinema videos like https://asciinema.org/a/VJuSM8rNhOavYEn2LZmFq8Lvo

**Comment by nyrahul** [comment]
This issue encompasses changes to be handled in #464 

We also need a document section for handling KubeArmor usage on VM/Bare-metals.

**Comment by nam-jaehyun** [comment]
@daemon1024 @nyrahul Can you split this issue into multiple ones?
Then, people can choose one of them in parallel while we may need to reorganize the pages later.

**Comment by nam-jaehyun** [comment]
@daemon1024 in terms of self-managed k8s, let's have two items: one is for docker and the other is for containerd.
Also, I removed helm-based KubeArmor deployment.

**Comment by sayantani11** [comment]
@daemon1024 The collapsible section link doesn't work

**Comment by daemon1024** [comment]
https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab

Hopefully this helps!
