### ISSUE TITLE
Documentation for enabling pod/containers/hosts visibility

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#481]
## Description
KubeArmor currently supports enabling visibility for containers/hosts. This was handled as part of #126 and #398.

We need the following in documentation:
- [ ] Enabling visibility in the sample app
- [ ] How to fetch the visibility info from `karmor log`?
- [ ] Sample JSONs

**General Information**

- Environment description (GKE, VM-Kubeadm, vagrant-dev-env, minikube, microk8s, ...)
All

- Kernel version (run `uname -a`)
All

- Link to relevant artifacts (policies, deployments scripts, ...)
#126 and #398

**Comment by TheRealSibasishBehera** [comment]
Hi I am new here , if nobody is working on this issue currently , i would like to work on it as my first issue 🙂

**Comment by nyrahul** [comment]
> Hi I am new here , if nobody is working on this issue currently , i would like to work on it as my first issue 🙂

Thank you for your interest. Any questions please let us know here on the issue or in the kubearmor slack channel.

**Comment by TheRealSibasishBehera** [comment]
i think the slack link in the readme as well as website is showing error
if its still online , i would like to join it 
my mail : beherasibasishkkc@gmail.com
