### ISSUE TITLE
problem using bcc-dev edge ver pkg for alpine

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#491]
## Bug Report
After the latest kubearmor image update, the kubearmor pods were going into CrashLoopBackOff for following reason:
```
Error relocating /usr/lib/libbcc.so.0: btf__load_vmlinux_btf: symbol not found
Error code: 127
```

There was a problem using the latest update of [bcc-dev (edge, 0.23.0-r0)](https://pkgs.alpinelinux.org/packages?name=bcc-dev&branch=edge&repo=community&arch=x86_64). This pkg was updated yesterday.

#490 affixed [0.20.0-r1 of bcc-dev from alpine branch v3.14](https://pkgs.alpinelinux.org/packages?name=bcc-dev&branch=v3.14&repo=community&arch=x86_64) which seems to be working fine.
With this change Kubearmor won't be using the bcc-dev updates any more and hence the problem needs to be looked into.

**General Information**

- Environment description (GKE, VM-Kubeadm, vagrant-dev-env, minikube, microk8s, ...)
All

- Kernel version (run `uname -a`)
All

**To Reproduce**
Prepare kubearmor image using bcc-dev edge version and launch the pods. The pods will go into CrashLoopBackOff.

**Expected behavior**
The kubearmor pods need to be started normally.

CC: @daemon1024

**Comment by nam-jaehyun** [comment]
For safety, let's add one more testing logic that GitHub action builds a test image before pushing the latest image to Github Hub. In this process, we need to check if the test image can be deployed in a k8s cluster and the KubeArmor daemonset runs without errors.

**Comment by nyrahul** [comment]
> For safety, let's add one more testing logic that GitHub action builds a test image before pushing the latest image to Docker Hub. In this process, we need to check if the test image can be deployed in a k8s cluster and the KubeArmor daemonset runs without errors.

Yeah! Good point. I believe the current tests are run directly in a self-managed k8s env with kubearmor running as a host process. The only change we may have to do is to use karmor cli to do the tests (which will automatically install kubearmor images). Is this right?

**Comment by Ankurk99** [comment]
The issue here is that recently function "libbpf_find_kernel_btf" was renamed to "btf__load_vmlinux_btf" in the Linux kernel [Commit link](https://github.com/torvalds/linux/commit/a710eed386f182fcbfe517b659f60024fdb7c40c#diff-333e3796217dda054b006e3cfe59f542121cf8a07f67f21c6ab7851ecf0c02e1). These changes were then included in the bcc library which takes usage of this function, but not able to find the new function name in the older kernels, thus showing the above error.
