### ISSUE TITLE
EKS Cluster Setup Documentation

### ISSUE THREAD

**Issue by daemon1024** [kubearmor/KubeArmor#493]
Add prerequisites to setting up KubeArmor in a EKS Cluster in the [getting started ](https://github.com/kubearmor/KubeArmor/tree/main/getting-started) guide as a section

Reference https://github.com/kubearmor/KubeArmor/tree/main/deployments/EKS#prerequisite-for-the-deployment

**Hi, If it is the first time that you contribute to KubeArmor, follow these steps:**
Write a comment in this issue thread to let other possible contributors know that you are working on this bug. For eg : `Hey all, I would like to work on this issue.`, checkout [Contributing Guide :fire::sparkles: ](https://github.com/kubearmor/KubeArmor/blob/main/CONTRIBUTING.md)and feel free to ask anything related to this issue in this thread or on our [slack channel](https://kubearmor.herokuapp.com/) ✌🏽

**Comment by slayer321** [comment]
Hey @daemon1024, can I work on this?

**Comment by nyrahul** [comment]
@daemon1024 , I think we have the necessary documentation in the context. What is the ask here?

**Comment by daemon1024** [comment]
Yup. Closing this. Need to clean up list in https://github.com/kubearmor/KubeArmor/issues/477
