### ISSUE TITLE
Minikube Cluster Setup Documentation

### ISSUE THREAD

**Issue by daemon1024** [kubearmor/KubeArmor#496]
Add prerequisites to setting up KubeArmor in a Minikube Cluster in the [getting started ](https://github.com/kubearmor/KubeArmor/tree/main/getting-started) guide as a section.

Ref https://github.com/kubearmor/KubeArmor/tree/main/contribution/minikube

**Hi, If it is the first time that you contribute to KubeArmor, follow these steps:**
Write a comment in this issue thread to let other possible contributors know that you are working on this bug. For eg : `Hey all, I would like to work on this issue.`, checkout [Contributing Guide :fire::sparkles: ](https://github.com/kubearmor/KubeArmor/blob/main/CONTRIBUTING.md)and feel free to ask anything related to this issue in this thread or on our [slack channel](https://kubearmor.herokuapp.com/) ✌🏽

**Comment by sayantani11** [comment]
@daemon1024 Can I take this?

**Comment by daemon1024** [comment]
Sure go ahead @sayantani11

**Comment by ErenYeager713** [comment]
Hey @daemon1024 , I would like to work on this issue.

**Comment by daemon1024** [comment]
Hey @ErenYeager713, @sayantani11 is already working on this. Can you checkout https://github.com/kubearmor/KubeArmor/blob/main/CONTRIBUTING.md#how-to-contribute-to-kubearmor to find more issues to contribute to? Thanks.

**Comment by ErenYeager713** [comment]
Sure

**Comment by Akshit42-hue** [comment]
Can I take it up @daemon1024
