### ISSUE TITLE
KubeArmor Manual Installation

### ISSUE THREAD

**Issue by daemon1024** [kubearmor/KubeArmor#498]
We recently updated our [guide](https://github.com/kubearmor/KubeArmor/blob/main/getting-started/deployment_guide.md) with kArmor based installation. We should also provide a section pointing to manual YAML based KubeArmor deployment.

Ref https://github.com/kubearmor/KubeArmor/tree/main/deployments

**Hi, If it is the first time that you contribute to KubeArmor, follow these steps:**
Write a comment in this issue thread to let other possible contributors know that you are working on this bug. For eg : `Hey all, I would like to work on this issue.`, checkout [Contributing Guide :fire::sparkles: ](https://github.com/kubearmor/KubeArmor/blob/main/CONTRIBUTING.md)and feel free to ask anything related to this issue in this thread or on our [slack channel](https://kubearmor.herokuapp.com/) ✌🏽

**Comment by sayantani11** [comment]
Hi all, I would like to work on this issue... also @daemon1024  do I add the deployment link provided or point to each particular deployment in the guide? I hope I am able to explain myself

**Comment by daemon1024** [comment]
@sayantani11 I think it should be the link provided in the issue, with context that you need to choose the YAML based on your environment. Followed by an example with generic deployment YAML!

Thanks for taking interest in this 😄
