### ISSUE TITLE
Troubleshooting Guide

### ISSUE THREAD

**Issue by daemon1024** [kubearmor/KubeArmor#499]
- Provide List of Checks
- `karmor sysdump` utility
- List of Information required and Format to ask for help

**Hi, If it is the first time that you contribute to KubeArmor, follow these steps:**
Write a comment in this issue thread to let other possible contributors know that you are working on this bug. For eg : `Hey all, I would like to work on this issue.`, checkout [Contributing Guide :fire::sparkles: ](https://github.com/kubearmor/KubeArmor/blob/main/CONTRIBUTING.md)and feel free to ask anything related to this issue in this thread or on our [slack channel](https://kubearmor.herokuapp.com/) ✌🏽

**Comment by h20220025** [comment]
hi @daemon1024 @nyrahul , This issue seems to be a good initiation of my journey towards contribution to FOSS projects.
Can you please assign this to me?

**Comment by daemon1024** [comment]
@h20220025 Glad you found it interesting. Please feel free to ask for help if needed in this thread or on slack.

Looking forward to the PR 😁

**Comment by h20220025** [comment]
Thank You

**Comment by HariVamsiK** [comment]
Hey @nyrahul.. As we have talked in the last community call that I would take up another issue. I'll take this up if @h20220025 is not working on it.

**Comment by HariVamsiK** [comment]
@h20220025 If you are not working on this, can I take it up??

**Comment by h20220025** [comment]
@HariVamsiK I am not working on this issue as I have been busy with other issues. So You can work on this if you want.

**Comment by Abhishek-569** [comment]
I want to work on this issue.  Thankful for any suggestions.

**Comment by nyrahul** [comment]
> I want to work on this issue. Thankful for any suggestions.

There are two places where it could be of use:
1. This could go in as an FAQ [here](https://github.com/kubearmor/KubeArmor/blob/main/getting-started/FAQ.md).
2. This FAQ can be referenced from [getting started guide](https://github.com/kubearmor/KubeArmor/blob/main/getting-started/deployment_guide.md) and from [development guide](https://github.com/kubearmor/KubeArmor/blob/main/contribution/development_guide.md) where necessary.

**Comment by Abhishek-569** [comment]
@nyrahul  Why the slack channel link is directing to this  https://kubearmor.herokuapp.com/ ? Can you send me the link for the slack channel invite to be added here. Thanks.

**Comment by Amishakumari544** [comment]
Hey, have you tried to join through the readme file?

**Comment by Abhishek-569** [comment]
Yes. will be using that here.

**Comment by Abhishek-569** [comment]
Where should I add [this ](https://github.com/Abhishek-569/KubeArmor/blob/faqGuide/getting-started/FAQ.md#what-are-the-steps-to-follow-if-its-your-first-time-contributing-to-kubearmor)in [development guide](https://github.com/kubearmor/KubeArmor/blob/main/contribution/development_guide.md)?

**Comment by nyrahul** [comment]
> Where should I add [this ](https://github.com/Abhishek-569/KubeArmor/blob/faqGuide/getting-started/FAQ.md#what-are-the-steps-to-follow-if-its-your-first-time-contributing-to-kubearmor)in [development guide](https://github.com/kubearmor/KubeArmor/blob/main/contribution/development_guide.md)?

The aim is to have the text in the FAQ and reference that from the dev guide.

**Comment by Abhishek-569** [comment]
Yes where to add this reference in dev guide? under which heading ?

**Comment by nyrahul** [comment]
Would suggest adding this in the [Environment Check section](https://github.com/kubearmor/KubeArmor/blob/main/contribution/development_guide.md#3--environment-check) of the dev guide.

You can add a note in there saying, if you face any problems have a look at this FAQ etc.

**Comment by Abhishek-569** [comment]
please let me know if it is correct.PR https://github.com/kubearmor/KubeArmor/pull/1153

**Comment by Abhishek-569** [comment]
@nyrahul Should the question begin like ` How can I troubleshoot Kubearmor failures? `?

**Comment by Rajdeep1311** [comment]
Is this anyone working on this?

**Comment by HariVamsiK** [comment]
The issue was worked on and appropriate changes were made in the files and linked to the PR#1163. I think there are some conflicts and it needs approval from 2 reviewers.
