### ISSUE TITLE
Tracking external node uptime/downtime

### ISSUE THREAD

**Issue by seswarrajan** [kubearmor/KubeArmor#507]
The controller cluster needs to track the uptime, downtime of the external node based on the GRPC connection availability.
In the future, this could be used to provide alerts/telemetry to the user.

**Comment by nyrahul** [comment]
Hey @seswarrajan , this issue needs to be raised in KVMService repo.

**Comment by seswarrajan** [comment]
This issue is a duplicate of https://github.com/kubearmor/KVMService/issues/14
Hence closing the same
