### ISSUE TITLE
docker push stopped working from vagrant dev VM

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#522]
## Bug Report

[This commit](https://github.com/kubearmor/KubeArmor/pull/505/commits/1be8d9d79cb2e1870a3e4063b144738c873795ba) introduced a change in `KubeArmor/KubeArmor/build/push_kubearmor.sh` to use `docker push -a` to push all the tags. `-a` option is not present in docker-ce version 18.09 which is by default installed in the ubuntu 18.04 vagrant dev VM. `-a` option was introduced to push multiple tags, one for latest and another that has the GITHUB_SHA for the corresponding github code so as to maintain the mapping. Point is, we need `-a` docker push option to work.

**General Information**

- Environment description (GKE, VM-Kubeadm, vagrant-dev-env, minikube, microk8s, ...)
Ubuntu 18.04 Vagrant Dev VM

**To Reproduce**

1. Setup dev env vagrant VM using instructions [here](https://github.com/kubearmor/KubeArmor/blob/main/contribution/development_guide.md).
2. `cd KubeArmor/KubeArmor && build/push_kubearmor.sh`

This results in:
```
vagrant@kubearmor-dev:~/KubeArmor/KubeArmor$ build/push_kubearmor.sh 
[INFO] Pushing kubearmor/kubearmor
docker push -a kubearmor/kubearmor
unknown shorthand flag: 'a' in -a
See 'docker push --help'.
[FAILED] Failed to push kubearmor/kubearmor
```

**Expected behavior**

`build/push_kubearmor.sh ` should push the docker image.

**Workaroud?**

If one updates the docker version in the vagrant vm simply by :
```
sudo apt install docker-ce docker-ce-cli
```
then it updates the docker version and the script works.

**Comment by nyrahul** [comment]
Hey @nam-jaehyun , Is there any specific reason why we are installing docker-ce/docker-ce-cli version 18.09 in the vagrant dev VM? [ref](https://github.com/kubearmor/KubeArmor/blob/b86aa474a56a976a7407ba3ef6faa191fc4820aa/contribution/self-managed-k8s/docker/install_docker.sh#L38).

**Comment by nam-jaehyun** [comment]
that is the minimum version that KubeArmor supports

**Comment by nyrahul** [comment]
> that is the minimum version that KubeArmor supports

Is it ok to switch to latest docker in the vagrant dev env? Based on my tests, it seems to work without issues.

**Comment by nam-jaehyun** [comment]
@nyrahul it seems that this issue was already addressed with your previous PR (removing -a). If so, can you close this?

**Comment by nyrahul** [comment]
> @nyrahul it seems that this issue was already addressed with your previous PR (removing -a). If so, can you close this?

Yes it was handled as part of #553
