### ISSUE TITLE
KubeArmor crashing with Segmentation fault

### ISSUE THREAD

**Issue by Ankurk99** [kubearmor/KubeArmor#526]
## Bug Report

**KubeArmor crashing**

- Environment description: Tested on vagrant-dev-env but should be a global issue

**To Reproduce**

1. Setup dev env vagrant VM
2. cd KubeArmor/KubeArmor/build && ./build_kubearmor.sh
3. Run kubearmor 
	- cd deployment/docker && kubectl apply -f kubearmor.yaml

This results in KubeArmor crashing with following error:
`Error code: 139`
`/KubeArmor/entrypoint.sh: line 34: 303904 Segmentation fault      (core dumped) /KubeArmor/kubearmor ${ARMOR_OPTIONS[@]}
`

**Expected behavior**
KubeArmor should run fine

**Known reason for the issue**
The following error is due to the recently limit resources imposition [https://github.com/kubearmor/KubeArmor/commit/7b7d3103c59a21ce4444ab1f152642915d7720f0](https://github.com/kubearmor/KubeArmor/commit/7b7d3103c59a21ce4444ab1f152642915d7720f0)

**Workaround**
Remove the KubeArmor resources limit [https://github.com/kubearmor/KubeArmor/blob/7b7d3103c59a21ce4444ab1f152642915d7720f0/deployments/docker/kubearmor.yaml#L139-L145](https://github.com/kubearmor/KubeArmor/blob/7b7d3103c59a21ce4444ab1f152642915d7720f0/deployments/docker/kubearmor.yaml#L139-L145)

**Comment by Ankurk99** [comment]
@nam-jaehyun Is there any other workaround like increasing the resources limit?

**Comment by nyrahul** [comment]
@Ankurk99 , did you test by removing the resource limits (as mentioned in the workaround) and did it work for you?

**Comment by Ankurk99** [comment]
Yes @nyrahul, it is running fine after removing the resource limits. I tested it locally and on github actions too (https://github.com/kubearmor/KubeArmor/runs/4461345837?check_suite_focus=true, here test is passing fine. The issue is with Docker authentication).
