### ISSUE TITLE
Adopt a license scanning tool, like FOSSA or Snyk

### ISSUE THREAD

**Issue by namdeirf** [kubearmor/KubeArmor#528]
## Feature Request

**Short Description**

Per the CNCF [Sandbox requirements](https://github.com/cncf/sandbox/issues/226), the KubeArmor repo needs to adopt a license scanning tool. 

**Is your feature request related to a problem? Please describe the use case.**

Not related to a problem

**Describe the solution you'd like**

[FOSSA](https://fossa.com/) or [Snyk](https://snyk.io/plans/)

**Describe alternatives you've considered**

We are not limited to the above options, and we can change when done.

**Comment by namdeirf** [comment]
Spoke with CNCF (https://github.com/cncf/sandbox/issues/226) and they can provide us with a license or we can create our own, they stated no preference.

1) Our decisions are: pick a tool - 

- [ ] FOSSA / Only license scanning
- [ ] Snyk / License scanning and other features
- [ ] Other 

2) Create our own license or use CNCF

- If we want to use their tool/license, a maintainer needs to submit a request, https://servicedesk.cncf.io.
- Synk is [here](https://snyk.io/plans/), FOSSA is [here](https://fossa.com/product/open-source-license-compliance)

Amongst our maintainers: @nyrahul, @asifalix and @nam-jaehyun we should vote in this thread via comments. Any others with insights should share as well.

**Comment by daemon1024** [comment]
We already use a license scanning tool called [Apache SkyWalking Eyes](https://github.com/apache/skywalking-eyes) which is configured to run here 
https://github.com/kubearmor/KubeArmor/blob/60c105f04f1f3bf6fdc5d90264236e104c153d34/.github/workflows/ci-go.yml#L55-L56
If needed, we can discuss any changes is required in the way it is configured to run.
Else if it doesn't fit the requirements, we can proceed with the mentioned tools.

**Comment by namdeirf** [comment]
Thank you @daemon1024! CNCF is asking for a license scanning report, comment below, is that something you can provide?

>@namdeirf can we see a license scanning report of this tool provided for your project?

**Comment by daemon1024** [comment]
@namdeirf here's a report generated by the tool - https://gist.github.com/daemon1024/3ed45e9294f5bd4f273d03d90d0a6549 
Hope this helps.

Used `dependency resolve` command provided by the tool to generate this
> This command serves as assistance for human beings to audit the dependencies license

Ref https://github.com/apache/skywalking-eyes#resolve-dependencies-licenses

**Comment by namdeirf** [comment]
Thank you @daemon1024, might be a silly question is it okay if I just share with them the link above? Or should I download a copy of that file.

**Comment by daemon1024** [comment]
@namdeirf Yeah it's perfectly ok 🙌🏽 Pasted in there, so that it could be shared 😬

**Comment by namdeirf** [comment]
Per a request from CNCF @daemon1024, is there a way to create a 'badge' on our READme page that will allow people to create a report [like the one you created](https://gist.github.com/daemon1024/3ed45e9294f5bd4f273d03d90d0a6549) on demand? 

Essentially our license compliance needs to be able to be verified publicly by whomever. Apparently, FOSSA offers this option.

Let me know if you want to jump on a call/Slack to explain further.

**Comment by nyrahul** [comment]
Have requested CNCF Service Desk for a synk license. Synk could be very useful since it does vulnerability scanning as well as license scanning.

**Comment by nyrahul** [comment]
CNCF had graciously (and promptly) allocated us a licensed use of Snyk and it is already been put to use. @daemon1024 @namdeirf , I have added you as collaborators and you might have received the invites to check the reports.

**Comment by namdeirf** [comment]
Thank you!

**Comment by namdeirf** [comment]
We have adopted Snyk via a CNCF license.
