### ISSUE TITLE
Reconsider k8s environment detection

### ISSUE THREAD

**Issue by daemon1024** [kubearmor/KubeArmor#537]
## Bug Report

We currently check local k8s environment using 
https://github.com/kubearmor/KubeArmor/blob/d99a1cb5f90892ce0a64e1c98b3916741890603b/KubeArmor/common/common.go#L265
which is not a valid way, since there might be a `.kube` folder but no valid config. So we should revisit this.

**General Information**

- Environment description: process mode

**To Reproduce**

1. Create a `.kube` folder in home directory
2. Try host based policy enforcement using gRPC

It tries to match node selectors but it should not cause it's not in k8s mode.

cc @nam-jaehyun

**Comment by JeongyoonMoon** [comment]
Can I work on this issue? @nam-jaehyun
