### ISSUE TITLE
Remove container name dependency from documents

### ISSUE THREAD

**Issue by h3llix** [kubearmor/KubeArmor#550]
## Feature Request
For example: In `multiubuntu.md` user needs to manually type in container name and this could be removed using kubectl jsonpath

**Describe the solution you'd like**
Please refer this #549

**Comment by nam-jaehyun** [comment]
@h3llix can you also check the other documents and update them together?

**Comment by h3llix** [comment]
@nam-jaehyun Sure. I'll fix them.
