### ISSUE TITLE
Kubearmor pod stuck in ContainerCreating with GKE Rapid Release Version

### ISSUE THREAD

**Issue by vishnusomank** [kubearmor/KubeArmor#579]
## Bug Report

**General Information**

- Environment description (GKE, VM-Kubeadm, vagrant-dev-env, minikube, microk8s, ...)
        `GKE Rapid Release Version 1.22.3-gke.700`
- Kernel version (run `uname -a`)

        Linux gke-cluster-1-default-pool-7b6c3cc6-hlf8 5.10.68+ #1 SMP Wed Oct 6 22:30:49 UTC 2021 x86_64 Intel(R) Xeon(R) CPU @ 2.20GHz GenuineIntel GNU/Linux
- Orchestration system version in use (e.g. `kubectl version`, ...)
    ```
    Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3-gke.700", GitCommit:"e21de5d6cf1b351bc99285c3c762098b8617b773", GitTreeState:"clean", BuildDate:"2021-11-05T09:25:32Z", GoVersion:"go1.16.7b7", Compiler:"gc", Platform:"linux/amd64"}
- Link to relevant artifacts (policies, deployments scripts, ...)
- Target containers/pods
    ```ubuntu 20.04 ```

**To Reproduce**

1. Install KubeArmor using CLI
```karmor install ```
2. Check for pod status
```kubectl get po -A -lkubearmor-app=kubearmor -o wide```

**Current behavior**

The pods are stuck in Containercreating phase with kubelet error `FailedMount`
```
kubectl get po -A -lkubearmor-app=kubearmor                                 
NAMESPACE     NAME              READY   STATUS              RESTARTS   AGE
kube-system   kubearmor-f2qvs   0/1     ContainerCreating   0          27m
kube-system   kubearmor-fjwb6   0/1     ContainerCreating   0          27m
kube-system   kubearmor-w5rsj   0/1     ContainerCreating   0          27m
```
```
kubectl -n kube-system describe $(kubectl get po -A -lkubearmor-app=kubearmor -o name)
Name:         kubearmor-f2qvs
Namespace:    kube-system
Priority:     0
Node:         gke-cluster-1-default-pool-c0d7970d-1f2f/10.128.0.57
Start Time:   Fri, 28 Jan 2022 00:43:17 +0530
Labels:       controller-revision-hash=7d45978987
              kubearmor-app=kubearmor
              pod-template-generation=1
Annotations:  container.apparmor.security.beta.kubernetes.io/kubearmor: unconfined
Status:       Pending
IP:           10.128.0.57
IPs:
  IP:           10.128.0.57
Controlled By:  DaemonSet/kubearmor
Containers:
  kubearmor:
    Container ID:  
    Image:         kubearmor/kubearmor:latest
    Image ID:      
    Port:          32767/TCP
    Host Port:     32767/TCP
    Args:
      -gRPC=32767
      -logPath=/tmp/kubearmor.log
      -enableKubeArmorHostPolicy
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Liveness:       exec [/bin/bash -c if [ -z $(pgrep kubearmor) ]; then exit 1; fi;] delay=60s timeout=1s period=10s #success=1 #failure=3
    Environment:    <none>
    Mounts:
      /etc/apparmor.d from etc-apparmor-d-path (rw)
      /lib/modules from lib-modules-path (ro)
      /media/root/etc/os-release from os-release-path (ro)
      /run/containerd from containerd-storage-path (ro)
      /sys/fs/bpf from sys-fs-bpf-path (rw)
      /sys/kernel/debug from sys-kernel-debug-path (rw)
      /usr/src from usr-src-path (ro)
      /var/lib/docker from docker-storage-path (ro)
      /var/run/containerd/containerd.sock from containerd-sock-path (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-zbbpw (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  usr-src-path:
    Type:          HostPath (bare host directory volume)
    Path:          /usr/src
    HostPathType:  Directory
  lib-modules-path:
    Type:          HostPath (bare host directory volume)
    Path:          /lib/modules
    HostPathType:  Directory
  sys-fs-bpf-path:
    Type:          HostPath (bare host directory volume)
    Path:          /sys/fs/bpf
    HostPathType:  Directory
  sys-kernel-debug-path:
    Type:          HostPath (bare host directory volume)
    Path:          /sys/kernel/debug
    HostPathType:  Directory
  os-release-path:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/os-release
    HostPathType:  File
  etc-apparmor-d-path:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/apparmor.d
    HostPathType:  DirectoryOrCreate
  containerd-sock-path:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/containerd/containerd.sock
    HostPathType:  Socket
  containerd-storage-path:
    Type:          HostPath (bare host directory volume)
    Path:          /run/containerd
    HostPathType:  DirectoryOrCreate
  docker-storage-path:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/docker
    HostPathType:  DirectoryOrCreate
  kube-api-access-zbbpw:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 op=Exists
                             node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/network-unavailable:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason       Age                    From               Message
  ----     ------       ----                   ----               -------
  Normal   Scheduled    28m                    default-scheduler  Successfully assigned kube-system/kubearmor-f2qvs to gke-cluster-1-default-pool-c0d7970d-1f2f
  Warning  FailedMount  26m                    kubelet            Unable to attach or mount volumes: unmounted volumes=[usr-src-path], unattached volumes=[sys-fs-bpf-path containerd-storage-path kube-api-access-zbbpw usr-src-path docker-storage-path sys-kernel-debug-path lib-modules-path os-release-path etc-apparmor-d-path containerd-sock-path]: timed out waiting for the condition
  Warning  FailedMount  24m                    kubelet            Unable to attach or mount volumes: unmounted volumes=[usr-src-path], unattached volumes=[sys-kernel-debug-path docker-storage-path kube-api-access-zbbpw containerd-storage-path lib-modules-path containerd-sock-path usr-src-path sys-fs-bpf-path os-release-path etc-apparmor-d-path]: timed out waiting for the condition
  Warning  FailedMount  22m                    kubelet            Unable to attach or mount volumes: unmounted volumes=[usr-src-path], unattached volumes=[sys-fs-bpf-path sys-kernel-debug-path usr-src-path os-release-path containerd-sock-path containerd-storage-path docker-storage-path kube-api-access-zbbpw lib-modules-path etc-apparmor-d-path]: timed out waiting for the condition
  Warning  FailedMount  19m                    kubelet            Unable to attach or mount volumes: unmounted volumes=[usr-src-path], unattached volumes=[os-release-path usr-src-path docker-storage-path containerd-storage-path containerd-sock-path kube-api-access-zbbpw lib-modules-path sys-fs-bpf-path sys-kernel-debug-path etc-apparmor-d-path]: timed out waiting for the condition
  Warning  FailedMount  17m                    kubelet            Unable to attach or mount volumes: unmounted volumes=[usr-src-path], unattached volumes=[containerd-sock-path docker-storage-path lib-modules-path os-release-path etc-apparmor-d-path usr-src-path containerd-storage-path sys-fs-bpf-path sys-kernel-debug-path kube-api-access-zbbpw]: timed out waiting for the condition
  Warning  FailedMount  15m                    kubelet            Unable to attach or mount volumes: unmounted volumes=[usr-src-path], unattached volumes=[sys-fs-bpf-path containerd-sock-path kube-api-access-zbbpw usr-src-path os-release-path lib-modules-path sys-kernel-debug-path etc-apparmor-d-path containerd-storage-path docker-storage-path]: timed out waiting for the condition
  Warning  FailedMount  13m                    kubelet            Unable to attach or mount volumes: unmounted volumes=[usr-src-path], unattached volumes=[containerd-sock-path containerd-storage-path docker-storage-path usr-src-path lib-modules-path os-release-path kube-api-access-zbbpw sys-fs-bpf-path sys-kernel-debug-path etc-apparmor-d-path]: timed out waiting for the condition
  Warning  FailedMount  10m                    kubelet            Unable to attach or mount volumes: unmounted volumes=[usr-src-path], unattached volumes=[kube-api-access-zbbpw usr-src-path sys-kernel-debug-path containerd-storage-path containerd-sock-path etc-apparmor-d-path docker-storage-path sys-fs-bpf-path lib-modules-path os-release-path]: timed out waiting for the condition
  Warning  FailedMount  6m14s (x2 over 8m32s)  kubelet            (combined from similar events): Unable to attach or mount volumes: unmounted volumes=[usr-src-path], unattached volumes=[os-release-path etc-apparmor-d-path containerd-storage-path kube-api-access-zbbpw sys-kernel-debug-path lib-modules-path containerd-sock-path docker-storage-path sys-fs-bpf-path usr-src-path]: timed out waiting for the condition
  Warning  FailedMount  2m11s (x21 over 28m)   kubelet            MountVolume.SetUp failed for volume "usr-src-path" : hostPath type check failed: /usr/src is not a directory
  ```

**Expected behavior**

Kubearmor pods upd and running

**Comment by Ankurk99** [comment]
@vishnusomank I tried replicating the error but KubeArmor is running fine for me. Can you confirm if you are still facing the issue?

**Comment by Ankurk99** [comment]
Currently the KubeArmor seems to be running fine, if you face the problem again please feel free to open the issue.

**Comment by nyrahul** [comment]
Opening this issue, since it looks like I just heard about this issue from a user (@vfarcic).

<details>
  <summary>Feedback/response verbatim</summary>
  
Here's the `karmor sysdump` output.

Sysdump at karmor-sysdump-Sun Mar 13 16:07:37 CET 2022.zip
Error: container "kubearmor" in pod "kubearmor-2w6pn" is waiting to start: ContainerCreating

I'm guessing that's not very useful since kubearmo pods are not starting.
```
$ kubectl -n kube-system describe pod kubearmor-2w6pn

...
Events:
  Type     Reason       Age                  From               Message
  ----     ------       ----                 ----               -------
  Normal   Scheduled    3m41s                default-scheduler  Successfully assigned kube-system/kubearmor-2w6pn to gke-devops-catalog-devops-catalog-85f045c9-zrmw
  Warning  FailedMount  98s                  kubelet            Unable to attach or mount volumes: unmounted volumes=[usr-src-path], unattached volumes=[lib-modules-path sys-kernel-debug-path containerd-storage-path docker-storage-path usr-src-path sys-fs-bpf-path sys-kernel-security-path os-release-path kube-api-access-x2xp8 etc-apparmor-d-path containerd-sock-path]: timed out waiting for the condition
  Warning  FailedMount  93s (x9 over 3m41s)  kubelet            MountVolume.SetUp failed for volume "usr-src-path" : hostPath type check failed: /usr/src is not a directory
```

It cannot mount the volume.

The cluster in question is GKE with COS. According to https://docs.kubearmor.com/kubearmor/getting-started/deployment_guide#k8s-platforms-tested, that should work. I'm guessing that there are "special" requirements that are not documented (or it's not obvious where the reqs are).
</details>

@vfarcic thanks for the feedback

**Comment by vfarcic** [comment]
GKE version: `1.22.6-gke.1000`

You can recreate the same cluster through the following commands.

```bash
git clone https://github.com/vfarcic/devops-catalog-code

cd devops-catalog-code/terraform-gke/simple

gcloud auth application-default login

gcloud container get-server-config --region us-east1

export K8S_VERSION=1.22.6-gke.1000

terraform init

terraform apply --var k8s_version=$K8S_VERSION

export KUBECONFIG=$PWD/kubeconfig
```

**Comment by nyrahul** [comment]
Yep I am able to reproduce the problem with the given release version. Thanks
@Ankurk99, @nam-jaehyun, lets discuss this tomorrow and figure out the best way to support it.

**Comment by nyrahul** [comment]
@Ankurk99, @nam-jaehyun, the 1.22.* version is now available as part of GKE Regular Channel as well. Thus this is no more a problem with only Rapid Release channel.

**Comment by nyrahul** [comment]
keeping it open for few manual tests.

**Comment by nyrahul** [comment]
The tests are done.
- [x] GKE Rapid Release
- [x] GKE Regular Release channel with latest image (v1.22.6-gke.1000 (default), v1.22.7-gke.900 (latest))
- [x] GKE with ubuntu images

One has to update the karmor tool to v0.6.4 using following command:
```
$ curl -sfL https://raw.githubusercontent.com/kubearmor/kubearmor-client/main/install.sh | sudo sh -s -- -b /usr/local/bin

$ karmor version
karmor version 0.6.4 linux/amd64 BuildDate=2022-03-15T14:40:29Z
kubearmor image (running) version kubearmor/kubearmor:stable
```

CC: @vfarcic, thanks again for the feedback.
