### ISSUE TITLE
Test KubeArmor on AWS (EKS)

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#58]
Check if the KubeArmor can work on AWS k8s engines.

- [x] Check if the kernel primitives needed for KubeArmor are readily available
- [x] Test KubeArmor on AWS
- [x] Create a document for EKS deployment

Check if anyone can deploy KubeArmor based on the document

- [x] Double validation by someone else

**Comment by seungsoo-lee** [comment]
AWS EKS uses Amazon Linux 2 as an OS image, there are no other options.

The kernel version is 4.14 by default, and we can upgrade to 5.4.

BUT, Amazon Linux 2 does not support AppArmor. They suggest using SELinux.

ref. https://forums.aws.amazon.com/thread.jspa?threadID=320641


![Screen Shot 2021-02-02 at 12 01 15 PM](https://user-images.githubusercontent.com/7541723/106546385-6ddd3480-654e-11eb-9757-e6e8653ea870.png)

**Comment by seungsoo-lee** [comment]
![image](https://user-images.githubusercontent.com/7541723/110273067-17608b80-800f-11eb-9aaa-96a97e9e9440.png)

currently, SELinux not supported in aws/eks

**Comment by danmx** [comment]
5.10 lts kernel should be supported soon (they tend to follow lts versions). I think there will be a problem with EKS Fargate since it's a very [locked down microVM](https://github.com/aws/containers-roadmap/issues/1000#issuecomment-768463969) running a sidecar that runs eBPF will be impossible. One thing that could be used is ptrace, like [Falco](https://sysdig.com/blog/falco-support-on-aws-fargate/), to bypass the limitations.

**Comment by nyrahul** [comment]
> 5.10 lts kernel should be supported soon (they tend to follow lts versions). I think there will be a problem with EKS Fargate since it's a very [locked down microVM](https://github.com/aws/containers-roadmap/issues/1000#issuecomment-768463969) running a sidecar that runs eBPF will be impossible. One thing that could be used is ptrace, like [Falco](https://sysdig.com/blog/falco-support-on-aws-fargate/), to bypass the limitations.

Interesting point. However, at this juncture, our aim is to get it working for vanilla EKS (not fargate). Fargate will be a different challenge for the reasons you mentioned.
