### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by viveksahu26** [kubearmor/KubeArmor#593]
## Documentation issue
Basically, I was going through docs.  
Just below the policy in the section [how does kubearmor works](https://docs.kubearmor.com/kubearmor/#how-does-kubearmor-work), it is stated as :
`In the above policy - we are preventing the microservice-1 from accessing any the mysql conf file (/etc/mysql/my.cnf), or data file path (/etc/mysql/data).`

As I can see that `microservice-1` is not a app name, it's a label name of that app. So, according to me the statement would be like:- 
 `In the above policy - we are preventing the app with label microservice-1 from accessing any the mysql conf file (/etc/mysql/my.cnf), or data file path (/etc/mysql/data).`

**General Information**

Not necessary, as it is a documentation issue.

**To Reproduce**
Not required

**Expected behavior**
Already mention above.

A description of what you expected to happen.

**Screenshots**

none

**Comment by viveksahu26** [comment]
Hey @nyrahul , could you please confirm that whether this issue is valid or not.

**Comment by nyrahul** [comment]
> Hey @nyrahul , could you please confirm that whether this issue is valid or not.

Hey @viveksahu26 , the link you specified in the issue description does not have the text you mentioning. Can you please verify again? Thanks

**Comment by viveksahu26** [comment]
Hey @nyrahul , I am also not getting that link. So, closing this issue for now. Will reopen in future if link found or same issue found.
