### ISSUE TITLE
Documentation issue.

### ISSUE THREAD

**Issue by viveksahu26** [kubearmor/KubeArmor#594]
## Documentation issue

Just below [design](https://docs.kubearmor.com/kubearmor/kubearmor-design), it is stated that :-
`KubeArmor operates with [Linux security modules (LSMs)](https://en.wikipedia.org/wiki/Linux_Security_Modules), **while** using eBPF to be able to track the syscalls that are happening.`

As it is mention in the [documentation ](https://docs.kubearmor.com/kubearmor/#how-does-kubearmor-work )that KubeArmor uses LSM and ebpf. So, according me the above statement would be like, 
`KubeArmor operates with [Linux security modules (LSMs)](https://en.wikipedia.org/wiki/Linux_Security_Modules), **and also**  using eBPF to be able to track the syscalls that are happening.`

**General Information**
Not required.

**To Reproduce**

Not Required.

**Expected behavior**

A description of what you expected to happen.
Replacing `while`  ---> `and also`

**Screenshots**

none

**Comment by nyrahul** [comment]
I think the english "while using eBPF to be able to track ..." reads fine for me. Will close this since we haven't received any comments on this one from anyone else.
