### ISSUE TITLE
Implement `defaultArmor` option

### ISSUE THREAD

**Issue by daemon1024** [kubearmor/KubeArmor#595]
## Feature Request

Implement `defaultPosture` option in CLI and CRD

**Is your feature request related to a problem? Please describe the use case.**

Bug:
KubeArmor doesn't have a default posture in global context in case we only have from Source based policies.
Feature:
Add an option to audit events instead of blocking in case of whitelisting policies.

**Describe the solution you'd like**

Add options in KubeArmor to have a configurable default posture.

Initial Goals

- [ ] ~~`-defaultArmor` CLI option~~
	- [ ] Allow ( Current Behaviour )
	- [ ] Block
	- [ ] Audit
- [ ] `defaultFileArmor` - default position for both files/processes 
- [ ] `defaultNetworkArmor`
- [ ] Discuss on how to handle in CRD

cc @nyrahul @nam-jaehyun

**Comment by nyrahul** [comment]
SGTM, handling in CRD can be kept in different issue altogether and can be done later.

**Comment by nam-jaehyun** [comment]
@nyrahul as Rahul said we can handle the CRD part later.
let's use defaultFileAction and defaultNetworkAction rather than xxxArmor.
what is the purpose of "-defaultArmor"?

**Comment by daemon1024** [comment]
Just noted the CRD Part so as keep it as a later action item.

> what is the purpose of "-defaultArmor"?

@nam-jaehyun A global option, if someone doesn't want to individually configure file/network/future more options like caps maybe.

**Comment by nyrahul** [comment]
> Just noted the CRD Part so as keep it as a later action item.
> 
> > what is the purpose of "-defaultArmor"?
> 
> @nam-jaehyun A global option, if someone doesn't want to individually configure file/network/future more options like caps maybe.

@daemon1024, do we need a global option if we have specific options for `file`, `network`? If we have multiple option then we need to add conditions around it. We can simply keep `file`, `network` options. Maybe I miscommunicated this during our design call.
