### ISSUE TITLE
policy enforcement issue when kubearmor is restarted in systemd mode

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#605]
## Bug Report

When kubearmor is operating in systemd mode, and if someone applies a set of policies and then restarts the kubearmor then one has to reapply the set of policies manually.

**General Information**

- Environment description (GKE, VM-Kubeadm, vagrant-dev-env, minikube, microk8s, ...)
systemd (non-k8s) mode 

- Kernel version (run `uname -a`)
Any supported kernel ver

- Orchestration system version in use (e.g. `kubectl version`, ...)
systemd

**To Reproduce**

1. start kubearmor in systemd mode
2. apply policy1
3. restart kubearmor
4. policy1 is no more enforced

Note that this works seamlessly in k8s mode i.e., even if the kubearmor pod is deleted and restarted the previously enforced policies remain enforced.

**Expected behavior**

Previously enforced policies should remain enforced on restart in systemd mode.

CC: @seswarrajan

**Comment by sayantani11** [comment]
Can I take this?

**Comment by slayer321** [comment]
Hey @nyrahul , I did like to work on this issue.
Will need some pointer how can i start with this issue
