### ISSUE TITLE
Update documentation to install latest version of bcc 

### ISSUE THREAD

**Issue by Ankurk99** [kubearmor/KubeArmor#609]
## Feature Request

**Short Description**
Currently documentation mentions to only install bcc and doesn't specify that the version should be 0.21.0 or greater (here https://github.com/kubearmor/KubeArmor/blob/main/getting-started/kubearmor_vm.md), this causes KubeArmor failing in initializing system monitor upon deployment if the user installs lower version of bcc (for eg: using package manager)

**Is your feature request related to a problem? Please describe the use case.**
Older bcc and newer kernel version have issue where bcc internal bpf.h doesn't define BPF_SK_LOOKUP but newer kernel header file uses it
Issue: https://github.com/kubearmor/KubeArmor/issues/200

**Describe the solution you'd like**
Mention in documentation to install latest version of bcc (0.21.0 or greater)

**Comment by slayer321** [comment]
Hey @Ankurk99 , I did like to work on this issue .

**Comment by Ankurk99** [comment]
Please reach out on Slack if you have any questions.
