### ISSUE TITLE
observability and policy discovery helper tool

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#613]
## Feature Request

**Short Description**

KubeArmor, apart from been a policy enforcement engine also emits pod/container visibility data that can be used for observability use-cases. This observability information could in turn be used for kubearmor policy generation.
The aim of this feature is to:
1. show observability data in context to pod/container. Observability data includes
    * process spawned in the pod/container
    * file system accesses made use of
    * capabilities accessed by the pods/containers
    * network primitives used by the pod/container
2. show the information at namespace level, pod level or at container level, across multi-node deployments

Some of the requirements/use-cases are documented in the [slides here](https://docs.google.com/presentation/d/1THIcxrZrIOqihsFG9rxmR73XkmXa10CVkU1ewzP6ToQ/edit?usp=sharing).

**Describe the solution you'd like**

A kubearmor coach service is deployed in the cluster. This service connects to the kubearmor relay and gets the events from the daemonsets. The events contain all the information required to show the observability information.
<img src="https://user-images.githubusercontent.com/9133227/153463383-351c5c33-8c46-43f4-a4af-466873d396aa.png" width="50%">

We would need command line tool to access observability information. [karmor (kubearmor-client) tool](https://github.com/kubearmor/kubearmor-client) could support `karmor observe` option.
We can further have a TUI tool built on top of these APIs using [bubbletea](https://github.com/charmbracelet/bubbletea).

The tasks can be divided into following phases:
* Phase 1: Design the expected sample output. KubeArmor Coach k8s-deployment+service ... keep the logs and records in the DB. Aggregate the logs and keep summarized information in the DB. Provide GRPC APIs to access the information. Extend karmor to support the `observe` option with filtering options.
* Phase 2: Work on TUI to show the output in easily consumable way.

**Comment by nthnieljson** [comment]
Hello, I have provided a design document draft regarding this feature
https://docs.google.com/document/d/177jR8CpC6OgqTA8sMyqXfaJitAvreN5XyO-NDm5UKcY/edit?usp=sharing

**Comment by Shubhf** [comment]
Hey @nyrahul Can I contribute on this issue?

**Comment by nyrahul** [comment]
Hey @Shubhf , I do not think this issue is relevant anymore since now have `karmor profile` that provides this view.
I think we can close this issue.

**Comment by Shubhf** [comment]
Thank you for your response ..Can u pls tell which issues can I work on ?
