### ISSUE TITLE
POD_NAME variable refers to wrong container instead of KubeArmor container

### ISSUE THREAD

**Issue by viveksahu26** [kubearmor/KubeArmor#615]
### Short Description
Basically all the logs stored inside KubeArmor container whenever any activity is triggered whether it's against or validating to the  applied KuberArmorPolicy in the Kubernetes cluster. Since, all logs are stored inside `/tmp/kubearmor.logs`. Therefore user need to exec inside that KubeArmor pod to see those logs. 
But in the [documentation](https://github.com/kubearmor/KubeArmor/blob/main/examples/multiubuntu.md) logs are checked inside wrong container. Where POD_NAME variable referencing to wrong pod instead of KubeArmor pod.

**Expected behavior**

Logs should be checked inside KubeArmor pod instead of other pods. For the same POD_NAME need to replace. 

**Discussion**

For more, see to [slack](https://kubearmor.slack.com/archives/C01FG4G2PEY/p1644502965753289) discussion.

**Comment by viveksahu26** [comment]
I would love to work on this issue.
/assign me.

**Comment by nyrahul** [comment]
Lets not use `/tmp/kubearmor.log` directly for alerts/telemetry purpose ... We have a [karmor](https://github.com/kubearmor/kubearmor-client) tool (`karmor log --logFilter all`) that can be used to get the alerts/telemetry. Going forward we may not use `/tmp/kubearmor.log` to store the alerts/telemetry.

**Comment by viveksahu26** [comment]
Ok. But under [Check audit logs ](https://github.com/kubearmor/KubeArmor/blob/main/examples/multiubuntu.md) section do we need to add `kubectl -n kube-system  exec -it kubearmor-7tjlk -- bash -c  "tail  /tmp/kubearmor.log`"  command or  `karmor log --logFilter all` for checking logs.

**Comment by daemon1024** [comment]
@viveksahu26 I believe we should update to something like https://github.com/kubearmor/KubeArmor/blob/main/getting-started/kubearmor_vm.md#get-alerts-for-policies-and-telemetry

**Comment by nam-jaehyun** [comment]
the purpose of /tmp/kubearmor.log is for debugging and quickly checking if KubeArmor works as we expected.
As Rahul and Barun mentioned, we need to use a proper way (e.g., karmor) for alerts and telemetry.

**Comment by viveksahu26** [comment]
Ok, got it. Basically, we have to use standard way to see the logs and i.e. `karmor log --json`. And this also seems much convenient.
