### ISSUE TITLE
using random kubearmor GRPC server port

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#623]
## Feature Request

**Short Description**

Currently, the GRPC server port [[is a configuration](https://github.com/kubearmor/KubeArmor/blob/bf39613c0c01e986d3e77d2f46a59c526cbf5907/KubeArmor/config/config.go#L79)](https://github.com/kubearmor/KubeArmor/blob/bf39613c0c01e986d3e77d2f46a59c526cbf5907/KubeArmor/config/config.go#L79) and the default value is 32767.
This works fine on kubearmor in k8s mode where kubearmor is operating as a pod and the listen ports are deterministic within the pod.

However, in case of [systemd/host-process mode of operation](https://github.com/kubearmor/KubeArmor/blob/main/getting-started/kubearmor_vm.md), it is possible that port 32767 might have been in use by some other process on the host and if it is in use, the kubearmor startup will fail.

Requirement of this task:
- [ ] Ability to specify 0 as the GRPC port configuration in which case the bind should happen on the random port.
- [ ] This port information should be kept in a pid file.
- [ ] `karmor` [cli tool](https://github.com/kubearmor/kubearmor-client) will check for this pid file in case of k8s=false env and pick the port information from there to connect.

**Is your feature request related to a problem? Please describe the use case.**

It is possible that in systemd mode of invocation the port 32767 on the host is already in use. In such cases, kubearmor fails to start because of "address already in use" error.

**Describe the solution you'd like**

1. Ability to specify 0 as the GRPC port configuration in which case the bind should happen on the random port.
2. This port information should be kept in a pid file.
3. `karmor` [cli tool](https://github.com/kubearmor/kubearmor-client) will check for this pid file in case of k8s=false env and pick the port information from there to connect.

**Describe alternatives you've considered**

For pid file, check what is the appropriate location to keep the pid file.

**Comment by nam-jaehyun** [comment]
@nyrahul is it better to use a user-defined port rather than a random port?
The port is configurable. Do we still need to support a random port too?

**Comment by nyrahul** [comment]
> @nyrahul is it better to use a user-defined port rather than a random port? The port is configurable. Do we still need to support a random port too?

For systemd/host-process mode it is problem ... I have seen kubearmor failing due to port already in use several times (yesterday it happened with @daemon1024 during office hours demo) ... The user might not be able to understand the problem. I was thinking may be we could reduce this friction.

**Comment by nthnieljson** [comment]
hello @nyrahul, I would like to try working on this issue

**Comment by nthnieljson** [comment]
> * will check for this pid file in case of k8s=false env

currently I am working on the karmor cli tool, I am not really sure where can I get this env or variables, should I add another flag for k8s env on the `karmor log` command? or where can I find this?

**Comment by daemon1024** [comment]
@nthnieljson Maybe we should just add this to the existing check without adding another flag.

https://github.com/kubearmor/kubearmor-client/blob/main/log/log.go#L48-L54

We should add another check to check for the pid file in `opt/kubearmor/` directory, since that's where the files exist when KubeArmor runs in systemd mode ( Ref https://github.com/kubearmor/KubeArmor/blob/main/getting-started/kubearmor_vm.md )

**Comment by nthnieljson** [comment]
okay, thanks for the guide!

**Comment by nthnieljson** [comment]
I have submitted pull requests regarding this issue, please kindly review. Thanks
