### ISSUE TITLE
kubearmor support matrix for k8s/VM env

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#659]
# KubeArmor support matrix

| Provider  |                 Distro                  |  k8s   |
|:---------:|:---------------------------------------:|:------:|
|  Google   |     GKE-COS (Rapid/Regular Release)     |  Full  |
|  Google   |   GKE-Ubuntu (Rapid/Regular Release)    |  Full  |
|    AWS    |        EKS-Amazon Linux 2 (5.10)        | No[^1] |
|    AWS    |        EKS-Amazon Linux 2 (4.14)        | No[^1] |
|    AWS    |            EKS-Bottlerocket             | No[^1] |
|    AWS    |                EKS-RHEL8                | No[^1] |
|    AWS    | EKS-SUSE Linux Enterprise Server 15 SP3 |  TBD   |
|    AWS    |       EKS-Ubuntu Server 20.04 LTS       |  TBD   |
|    AWS    |       EKS-Ubuntu Server 18.04 LTS       |  TBD   |
|    AWS    |              EKS-Debian 10              |  TBD   |
|  Kinvolk  |                 Flatcar                 |  TBD   |
|  Redhat   |                OpenShift                |  TBD   |
|  RedHat   |                 RHEL8.4                 |   No   |
|  VMWare   |                  Tanzu                  |  TBD   |
| Canonical |              Ubuntu 20.04               |  Full  |
| Canonical |              Ubuntu 18.04               |  Full  |
| Canonical |              Microk8s[^4]               |  TBD   |
|  Debian   |             Debian (Buster)             |  TBD   |
|   SUSE    |           SUSE Enterprise 12            |  TBD   |
|   SUSE    |           SUSE Enterprise 15            |  TBD   |
| Microsoft |                   AKS                   |  TBD   |
|  Rancher  |            K3s on Ubuntu[^2]            |  Full  |
|  Rancher  |                  [RKE]                  |  TBD   |
|    k8s    |              Minikube[^3]               |  TBD   |

[^1]: Ability to do visibility, audit. Enforcement is not supported.
[^2]: K3s runs directly on the host OS. Thus any hostOS (such as Ubuntu, Debian, ...) supporting AppArmor should be ok. We have tested with Ubuntu 20.04
[^3]: Instructions noted [here](https://github.com/kubearmor/KubeArmor/tree/main/contribution/minikube) are required to be used for Minikube.
[^4]: Instructions noted [here](https://github.com/kubearmor/KubeArmor/tree/main/contribution/microk8s) are required to be used for Microk8s.

[RKE]: https://rancher.com/products/rke

**Comment by SujithKasireddy** [comment]
**Rancher Kubernetes Engine (RKE)**
@nyrahul when I try to install kubearmor on **RKE** env, kubearmor pod is failing due to the following error 
`MountVolume.SetUp failed for volume "lib-modules-path" : hostPath type check failed: /lib/modules is not a directory`
![image](https://user-images.githubusercontent.com/60265529/159451706-b9b80e85-026a-4145-b42b-886e7cce6219.png)

**Comment by nyrahul** [comment]
KubeArmor support matrix is maintained [here](https://github.com/kubearmor/KubeArmor/blob/main/getting-started/support_matrix.md) and will be updated henceforth.
