### ISSUE TITLE
`DefaultPosture` for Host Security Policies

### ISSUE THREAD

**Issue by daemon1024** [kubearmor/KubeArmor#660]
We recently added `DefaultPosture` for our security policies, we need to support it for Host Security Policies as well.

We should also leverage viper.ConfigWatcher and support changing the global default posture at runtime.

**Comment by nam-jaehyun** [comment]
May need to consider the fact that KubeArmor does not support ALLOW policies that do not have fromSource,
which means that all ALLOW policies will have fromSource.

**Comment by nyrahul** [comment]
@daemon1024 , @nam-jaehyun , can we mark this as done?
