### ISSUE TITLE
Bug in policyMatcher w.r.t. to HSP

### ISSUE THREAD

**Issue by daemon1024** [kubearmor/KubeArmor#661]
## Bug Report

**General Information**

- Environment description (GKE, VM-Kubeadm, vagrant-dev-env, minikube, microk8s, ...) *
- Kernel version (run `uname -a`) *
- Orchestration system version in use (e.g. `kubectl version`, ...)
- Link to relevant artifacts (policies, deployments scripts, ...)
- Target containers/pods

**To Reproduce**

1. Apply a host security policy https://github.com/kubearmor/KubeArmor/blob/main/examples/host-security-policies/hsp-kubearmor-dev-proc-path-block.yaml

3. Run a separate command and pass the resource name in policy as argument.
	` grep /usr/bin/diff * `

**Expected behavior**

No Alert

**Screenshots**

![image](https://user-images.githubusercontent.com/47106543/160850077-93ea5d0e-ae2f-4810-9d6d-19dfd280809d.png)

**Comment by nam-jaehyun** [comment]
[Fixes related to this issue](https://github.com/nam-jaehyun/KubeArmor/blob/530be40a05976b7a057ee7b46de3da52c70c503d/KubeArmor/feeder/policyMatcher.go#L841)
