### ISSUE TITLE
logs not generating in karmor log for the applied policies when try to access relative path

### ISSUE THREAD

**Issue by thennarasud** [kubearmor/KubeArmor#728]
ksp-mysql-audit-dir.yaml:
https://github.com/kubearmor/KubeArmor/blob/main/examples/wordpress-mysql/security-policies/ksp-mysql-audit-dir.yaml
As per above policy, we will get the logs when we access the full path – for absolute path getting logs
i.e #/var/lib/mysql> touch /var/lib/mysql/test
 
 

However, no logs are getting generated for the below use case – For relative path no logs
#/var/lib/mysql> touch test
No Logs;
 

Policy: https://github.com/kubearmor/KubeArmor/blob/main/examples/wordpress-mysql/security-policies/ksp-wordpress-block-sa.yaml
As per this policy, we should get the Audit/Block logs when we tried accessing the service account tokens from Absolue path;
We are getting logs for Block permissions when we use relative path;

In Absolute path , we are getting logs:
 

In relative path, no logs for Audit policy
when we enable Audit for this path and tried accessing the service account token information using relative path, there is no logs generated in karmor log.
 
Also, no logs are getting generated when we use rm, mv commands on this path, is this possible to include with audit policy of directories.
[kubearmor Policy testing outcome.docx](https://github.com/kubearmor/KubeArmor/files/8845327/kubearmor.Policy.testing.outcome.docx)

**Comment by nyrahul** [comment]
This problem is fixed in latest stable version (v0.4.4) released today. I did a quick tests and all seems fine with the relative paths.
To try the fix, you can do `karmor uninstall` and `karmor install` again and that would install the latest stable.
Another option is to simply delete all kubearmor pods and they will restart with the new stable release.
