### ISSUE TITLE
using configmap and grpc for configuration handling

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#754]
## Feature Request

**Short Description**

Kubearmor is provided with the [configuration at invoke time](https://github.com/kubearmor/KubeArmor/blob/8e74a245981a1ad53f4bba014705a331f578efe4/deployments/generic/kubearmor.yaml#L82). This means changing the default configuration is not possible without updating the container image.
Most of [the configuration options](https://github.com/kubearmor/KubeArmor/blob/8e74a245981a1ad53f4bba014705a331f578efe4/KubeArmor/config/config.go#L18) are currently using default values but some may need to be changed depending upon deployment basis.

Similarly in systemd mode, the only way for the user to change the configuration is to edit `/opt/kubearmor/kubearmor.yaml` file.

**Is your feature request related to a problem? Please describe the use case.**

A lot of times it is required that the `defaultPosture` of Kubearmor be changed between `Audit/Deny`. Currently, it is not possible to change it in the context of k8s deployment unless the user changes the deployment yamls manually.

**Describe the solution you'd like**

Use grpc endpoint to save/update the configuration setting.
Use k8s `configmap` for saving the configuration. Observe changes to configmap and invoke the corresponding grpc handler.

For e.g., `watchConfigMap() -> updateDefaultPosture() -> grpcUpdateDefaultPosture() -> updateDefaultPosture()`

**Comment by kaiquerass** [comment]
Hi @nyrahul, I'm using these configurations to change the defaultPosture to audit, but I'm still receiving events with defaultPosture policy and block action. 

My configuration: 
```
    spec:
      containers:
      - args:
        - -defaultFilePosture=audit
        - -hostDefaultFilePosture=audit
```
Pod's logs:
```
2022-08-11 19:18:47.523563	INFO	Configuration [{Cluster:default Host:xxxxx GRPC:32767 LogPath:/tmp/kubearmor.log SELinuxProfileDir:/tmp/kubearmor.selinux CRISocket: Visibility:process,file,network,capabilities HostVisibility:default Policy:true HostPolicy:false KVMAgent:false K8sEnv:true DefaultFilePosture:audit DefaultNetworkPosture:block DefaultCapabilitiesPosture:block HostDefaultFilePosture:audit HostDefaultNetworkPosture:block HostDefaultCapabilitiesPosture:block CoverageTest:false}]
2022-08-11 19:18:47.523585	INFO	Final Configuration [{Cluster:default Host:xxxxxxxxxxx GRPC:32767 LogPath:/tmp/kubearmor.log SELinuxProfileDir:/tmp/kubearmor.selinux CRISocket: Visibility:process,file,network,capabilities HostVisibility:none Policy:true HostPolicy:false KVMAgent:false K8sEnv:true DefaultFilePosture:audit DefaultNetworkPosture:block DefaultCapabilitiesPosture:block HostDefaultFilePosture:audit HostDefaultNetworkPosture:block HostDefaultCapabilitiesPosture:block CoverageTest:false}
```

Event:
```
== Alert / 2022-08-11 19:31:47.544754 ==
ClusterName: default
HostName: XXXXX
NamespaceName: XXXX
PodName: XXXXX
Labels: XXXXX
ContainerName: XXXX
ContainerID: XXXXX
ContainerImage: XXXXX
Type: MatchedPolicy
PolicyName: DefaultPosture
Source: /usr/local/bin/python
Resource: /usr/local/lib/python/XXXXXXXX
Operation: File
Action: Block
Data: syscall=SYS_OPENAT fd=-100 flags=O_WRONLY|O_CREAT|O_EXCL|O_CLOEXEC
Enforcer: AppArmor
Result: Permission denied
HostPID: XXX
HostPPID: XXX
PID: XXX
PPID: XXX
ParentProcessName: /usr/local/bin/python
ProcessName: /usr/local/bin/python
UID: XXXX
```

Using that configuration shouldn't just audit these events?

**Comment by AllMight2099** [comment]
Hey there!
I'd like to work on this issue

**Comment by nyrahul** [comment]
> Hey there! I'd like to work on this issue

Thank you for the interest. Any questions, we are on [slack](https://github.com/kubearmor/KubeArmor/#slack).

[UPDATE]: Rescinding since you have already selected another issue.

**Comment by s1ntaxe770r** [comment]
@nyrahul  I would like to work on this

**Comment by rksharma95** [comment]
Lets consider a scenario,
- Current global config default posture for file, network and capability is `audit`.
- There is a namespace `temp` and it's annotated with `kubearmor-network-posture=block`.
therefore default posture for namespace temp will be:
```
{
  defaultFilePosture:         audit,
  defaultCapabilitiesPosture: audit,
  defaultNetworkPosture:      block,
}
```

Let global default posture is changed to `block` now.

Now defaultPosture for namespace `temp` can be

either
1. Considered namespace `temp` to be annotated completely and using existing posture without any change
```
{
  defaultFilePosture:         audit,
  defaultCapabilitiesPosture: audit,
  defaultNetworkPosture:      block,
}
```

or

2. If we consider namespace posture/annotations to some extent and changed posture which are not defined yet with namespace annotations.
```
{
	defaultFilePosture:         block,    # changed because previously not defined
	defaultCapabilitiesPosture: block,    # changed because previously not defined
	defaultNetworkPosture:      block,
}
```
**What should be the preferred case?**

I've built the solution locally considering the case 1. In first look, i don't think it will add too much complexity to go with  case 2. but we need to discuss the applicability first.

**Comment by daemon1024** [comment]
I think it makes sense to consider the case 2.

**Comment by rksharma95** [comment]
pushed the changes to WIP PR #832
I've refactored the entire logic, added tests, ignore over-commenting/logging for now :grin: 
PTAL  @daemon1024 , @nyrahul
