### ISSUE TITLE
Add health check endpoints for hostpolicy and policy controllers

### ISSUE THREAD

**Issue by achrefbensaad** [kubearmor/KubeArmor#764]
## Feature Request

**Short Description**

hostpolicy and policy controllers should expose a health check endpoint.

**Is your feature request related to a problem? Please describe the use case.**

fixes point 13 in https://github.com/kubearmor/KubeArmor/issues/733

**Comment by daemon1024** [comment]
I would like to defer this until we handle https://github.com/kubearmor/KubeArmor/issues/241 i.e. Consolidate all controllers to single deployment,

What do you think?
