### ISSUE TITLE
Invalid resource detected in logs/telemetry

### ISSUE THREAD

**Issue by seswarrajan** [kubearmor/KubeArmor#770]
## Invalid resource

**General Information**

- Environment description (GKE, minikube)
- Google microservices

**To Reproduce**

1. Run any cluster
2. Deploy kubearmor
3. Run karmor log --logFilter all to listen on logs
4. Deploy Google microservices demo deployment
https://raw.githubusercontent.com/GoogleCloudPlatform/microservices-demo/main/release/kubernetes-manifests.yaml

**Expected behavior**
Logs will be normal

**Screenshots**
Seeing some logs which seems like **/cpu,cpuacct/** which doesn't seem valid

```
Operation: File
Resource: /cpu,cpuacct/cpu.cfs_quota_us
Data: syscall=SYS_OPENAT fd=-100 flags=O_RDONLY
```

**Comment by seswarrajan** [comment]
Log file

**Comment by daemon1024** [comment]
As inferred from our discussion the log event is valid.
