### ISSUE TITLE
Update KubeArmor peripheral images in CI

### ISSUE THREAD

**Issue by daemon1024** [kubearmor/KubeArmor#782]
## Feature Request

We only update the `kubearmor/kubearmor` image as part of our CI. But we have other images such as

- [x] kubearmor/kubearmor-annotation-manager
- [x] kubearmor/kubearmor-host-policy-manager
- [x] kubearmor/policy-manager
- [ ] kubearmor/kubearmor-init

Currently we manually build and push these images when an update are needed.

**Describe the solution you'd like**

Add CI to update these images which is conditionally triggered whenever there are any changes in the concerned files.

**Comment by achrefbensaad** [comment]
@daemon1024  kubearmor/kubearmor-init already included in kubearmor/kubearmor ci.
