### ISSUE TITLE
Debian 11 - `linux-headers` package does not have kconfig file

### ISSUE THREAD

**Issue by wazir-ahmed** [kubearmor/KubeArmor#803]
**Environment** - Self-managed k8s with Debain 11 (Bullseye)

**Kernel Version**
```
root@k8s-master:~# uname -a
Linux k8s-master 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux
```

**Problem**
The code ([KubeArmor/BPF](https://github.com/kubearmor/KubeArmor/tree/main/KubeArmor/BPF)) depends on files like `Kconfig` and `kconfig.h` which we get from the `linux-headers` package. Without the presence of these `kconfig` files, the `kubearmor-init` container will fail. 

**Issue** - The `kconfig` files are removed from the `linux-headers` package in the [upstream kernel](https://github.com/torvalds/linux/commit/9945722afdc3443eab826b2da1122509a13a50a5). In some distros (which uses same script as upstream kernel to building their `linux-headers` package) you won't find the `kconfig` files. In Debain 11, even if the `linux-headers` package are installed, the init containers are failing because the `kconfig` files are not present in the kernel header directory.

**Comment by wazir-ahmed** [comment]
@daemon1024 @nyrahul Is it possible to use the `linux-headers` package from the Ubuntu repository in Debain OS? The Ubuntu version of the package has the `kconfig` files.

**Comment by daemon1024** [comment]
@wazir-ahmed Is this issue relevant to KubeArmor stable image as well? In the deployment where we use BCC and no init container?
