### ISSUE TITLE
insufficient allocation for ebpf perf buffers to handle event burst

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#809]
## Feature Request

**Short Description**

Currently, we see a loss of perf buffer events even with modest workloads. Currently, we use a ebpf perf buffer size of 1024 * 4 ([ref](https://github.com/kubearmor/KubeArmor/blob/64635aca1105ab85ea63cd167e85cee21cbfcf20/KubeArmor/BPF/system_monitor.c#L164)).

In the case of event burst, the perf buffer is fully utilized before any of the events are consumed in the userspace (regardless of how fast the events are consumed).

**Describe the solution you'd like**

Increase the buffer allocation to a respectable size. Recommended is 1MB.
Note that the event drop problem has to be reproduced consistently using a scenario before making this change so that we can verify the impact of this change.

- [ ] define a scenario which will consistently cause event losses
- [ ] increase the buffer size and verify the impact on the same scenario
- [ ] define an appropriate buffer size considering real production workloads

**Comment by achrefbensaad** [comment]
Fixed
Related PR's:
- https://github.com/kubearmor/KubeArmor/pull/816 @DelusionalOptimist 
- https://github.com/kubearmor/KubeArmor/pull/818 @daemon1024
