### ISSUE TITLE
Containers restart after Kuberarmor install

### ISSUE THREAD

**Issue by r0binak** [kubearmor/KubeArmor#826]
## Bug Report

**General Information**

As far as I know, prior to version 0.5, deployments were edited manually to apply the required annotation for KubeArmor. But this method is not applicable, for example, when using a database inside a container. The data was frayed, as a result, the database was corrupted. After version 0.5, annotations were added using the admission controller, which in fact should not lead to restarting the pod and corrupting the database in the future. Until some time, everything worked for me as it should, but after updating 0.5.5, the containers began to restart again, which entailed the destruction of the database.

**Comment by nyrahul** [comment]
@achrefbensaad , can you please look into this? Thanks

**Comment by r0binak** [comment]
its look like mutating webhook not worked

**Comment by achrefbensaad** [comment]
@r0binak , can you further explain ?
did the mutation webhook add the required annotation ?

**Comment by r0binak** [comment]
> @r0binak , can you further explain ?
> did the mutation webhook add the required annotation ?

yes, added. but at the same time the pods restarted

**Comment by achrefbensaad** [comment]
a restart just after a pod is just created is an expected behavior. is that your case, or the pod get retarted after a long period of time ?

**Comment by r0binak** [comment]
> a restart just after a pod is just created is an expected behavior. is that your case, or the pod get retarted after a long period of time ?

hmm, strange .. I thought after updating 0.5 the pods will not be restarted. in my case, the pods restart immediately after installing KubeArmor. in this case, KubeArmor cannot be used when running databases in containers - the database schema is frayed and collapses. what to do in this case?

**Comment by achrefbensaad** [comment]
Ill try to reproduce it and get back to you.

**Comment by r0binak** [comment]
> 

i am using postgres as database. my application communicates with postgres

**Comment by achrefbensaad** [comment]
@r0binak , I was able to re-create the issue. Let me bring this issue to the community and get back to you with a concreate answer.

**Comment by achrefbensaad** [comment]
@r0binak we have identified the root cause of the probem and we have opened the following issue to fix it https://github.com/kubearmor/KubeArmor/issues/840

**Comment by r0binak** [comment]
> @r0binak we have identified the root cause of the probem and we have opened the following issue to fix it #840

thanks. I will wait for the fix

**Comment by achrefbensaad** [comment]
@r0binak, The fix will go live in v0.6.

**Comment by r0binak** [comment]
> @r0binak, The fix will go live in v0.6.

thanks!

**Comment by achrefbensaad** [comment]
@r0binak , V0.6 is stable now. can you check if the problem persists.
