### ISSUE TITLE
Support for Host based policies

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#83]
KubeArmor currently supports pod-specific policies i.e, one needs to specify the pod selector labels and optionally namespace for policy enforcement. However, there are rules that are applicable at the host level and thus need handling using NodeSelector labels alone. There is no notion of namespaces for host-based rules.

Check [Cilium's host-policies](https://docs.cilium.io/en/v1.9/policy/language/#hostpolicies) to refer host-based policies.

**Comment by nam-jaehyun** [comment]
the enforcement part for host security is handled, but the logging part is still missing.
Thus, I'd like to keep it open until all parts are addressed.
