### ISSUE TITLE
KubeArmor Telemetry Monitoring and Dashboards

### ISSUE THREAD

**Issue by daemon1024** [kubearmor/KubeArmor#836]
## Feature Request

KubeArmor emits a lot of telemetry events with Logs and Alerts. But consuming and making sense out of these telemetry events might be hard. There's a need for parsing these telemetry, generate relevant metrics, allow filtering the data and create graphs and visualise it i.e. create an entire dashboard which makes the kubearmor telemetry data easy to consume.

We recently added syslog support to relay service - https://github.com/kubearmor/kubearmor-relay-server/pull/19.
We should now be able to directly feed the Relay stdout to Logstash or Fluentd to capture logs and further analyze and visualize it. But we need to verify it and check if any other changes are required to readily consume the data.

**Describe the solution you'd like**

Explore one of the following stacks
- E(F/L)K (Elasticsearch, Fluentd/Logstash and Kibana)
- Loki + Grafana ( We already have a [sample integration](https://github.com/kubearmor/kubearmor-prometheus-exporter) with prometheus + grafana but Prometheus is for metrics, we need to visualise logs as a whole )

**Comment by kranurag7** [comment]
@daemon1024 I would love to work on this issue.

**Comment by nyrahul** [comment]
> @daemon1024 I would love to work on this issue.

Awesome!

**Comment by mdsahiloss** [comment]
@daemon1024 I'm new to kubeArmor, This enhancement looks interesting to me, so I would love to be a LFX mentee for this project, So Do you have any idea? about some good issues that will help me in understanding about telemetry events with Logs and Alerts and make me better for this project.

**Comment by smilingprogrammer** [comment]
Hi @daemon1024 . Seems this issues is language agnostic. Its mainly observability. Am i Right?

**Comment by rahulk789** [comment]
> @daemon1024 I'm new to kubeArmor, This enhancement looks interesting to me, so I would love to be a LFX mentee for this project, So Do you have any idea? about some good issues that will help me in understanding about telemetry events with Logs and Alerts and make me better for this project.

You could try working on issues labeled [good-first-issue](https://github.com/kubearmor/KubeArmor/labels/good%20first%20issue) to get familiar with the code base.
[This link](https://github.com/kubearmor/KubeArmor/blob/main/getting-started/kubearmor_vm.md) briefly explains how to generate basic logs on a bare-metal along with other stuff. Hope this was helpful.

**Comment by mdsahiloss** [comment]
Thanks @rahulk789 for letting me know.

**Comment by TheRealSibasishBehera** [comment]
Hi @daemon1024 could be assign me this issue
