### ISSUE TITLE
CI Test Coverage Calculation

### ISSUE THREAD

**Issue by daemon1024** [kubearmor/KubeArmor#845]
## Feature Request

We should calculate test coverage for tests across all the CI test suites we run. 

**Is your feature request related to a problem? Please describe the use case.**

Currently each coverage calculation is overwritten by the new coverage data in subsequent test suites in a PR.

**Describe the solution you'd like**

Uploading coverage data to codecov in a seperate job extractiong information from each test suite.
https://about.codecov.io/blog/uploading-code-coverage-in-a-separate-job-on-github-actions/ this article should help out.

**Comment by anonymousr007** [comment]
Hello,

I am new in KubeArmor, I saw this is a `good first issue`. So this is perfect for me as a beginner. Can you please guide me more about that issue? I am also interested in this project #789. 

Thanks & Regards
Rishabh

**Comment by daemon1024** [comment]
Hey @anonymousr007, This issue would require familiarity with Github Actions in general. Github has an excellent documentation about Github Actions @ https://docs.github.com/en/actions.

Our coverage calculation, sends the coverage data to codecov in the test suite here https://github.com/kubearmor/KubeArmor/blob/b38a0a59362d100bad7e8d6db36ed3c7f89a06e5/.github/workflows/ci-test-local.yml#L72-L85.

We need to move this to a seperate job so as a collective coverage can be calculated. 
As mentioned in the issue, https://about.codecov.io/blog/uploading-code-coverage-in-a-separate-job-on-github-actions/ this article should guide you about how can we achieve that.

Thanks a lot for showing interest in this. Feel free to ask questions here in this issue thread or on KubeArmor Slack, happy to help out.

**Comment by anonymousr007** [comment]
Hello @daemon1024, Thanks for assigning me this issue.
I would like to ask a question about this issue. 
- Is This YAML file code a separate job in the same file? File Name: [KubeArmor/.github/workflows/ci-test-local.yml](https://github.com/kubearmor/KubeArmor/blob/b38a0a59362d100bad7e8d6db36ed3c7f89a06e5/.github/workflows/ci-test-local.yml#L72-L85)

**Comment by daemon1024** [comment]
> This YAML file code a separate job in the same file? File Name: [KubeArmor/.github/workflows/ci-test-local.yml](https://github.com/kubearmor/KubeArmor/blob/b38a0a59362d100bad7e8d6db36ed3c7f89a06e5/.github/workflows/ci-test-local.yml#L72-L85)

This is a step of the job `build`, we want to move it to a separate job, yes.
https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions#understanding-the-workflow-file

**Comment by anonymousr007** [comment]
Hello @daemon1024, I make a WIP-PR. You guide me in it. Thanks.

**Comment by daemon1024** [comment]
Hey @anonymousr007 Can you link me the PR? I cannot seem to find it.

**Comment by anonymousr007** [comment]
Please review it

**Comment by rahulk789** [comment]
\assign

**Comment by rahulk789** [comment]
Hello! I would love to work on this issue. I have gone through the articles sent above. My understanding of the issue is that the coverage task is currently a step in [KubeArmor/.github/workflows/ci-test-local.yml](https://github.com/kubearmor/KubeArmor/blob/b38a0a59362d100bad7e8d6db36ed3c7f89a06e5/.github/workflows/ci-test-local.yml#L72-L85) and must be converted to a seperate job, is there any other file that i should be editing? I think removing codecov step from [github/workflows/ci-test-ginkgo.yml](https://github.com/kubearmor/KubeArmor/blob/e289bbc12afafe7882e5a69dc0af2c41ee91007a/.github/workflows/ci-test-ginkgo.yml) makes sense.

**Comment by daemon1024** [comment]
Thanks for picking this up @rahulk789.

> I think removing codecov step from [github/workflows/ci-test-ginkgo.yml](https://github.com/kubearmor/KubeArmor/blob/e289bbc12afafe7882e5a69dc0af2c41ee91007a/.github/workflows/ci-test-ginkgo.yml) makes sense.

From my understanding it would still need some form of codecov step that helps aggregating the coverage files across the test suite. I will check the PR and let's continue the discussion there.

**Comment by rahulk789** [comment]
Since Achref's pr (https://github.com/kubearmor/KubeArmor/pull/1029)  had removed local tests, we no longer need to combine the code coverage from two ci tests since we have only ginkgo test suit now. That being said, the issue seems no longer relevant  and should I close my pr? correct me if I am wrong. @daemon1024

**Comment by daemon1024** [comment]
Yes @rahulk789, this is still valid. 
Even if we only have a single test suite, it runs across multiple matrices like docker,container and crio which would result in different coverages (once generated) which is needed to be aggregated. 

Also we would need a way to generate coverage in Ginkgo test suite itself too. So the work item is still relevant imo. WDYT?

**Comment by pushkarm029** [comment]
Working on this one. Please assign.

**Comment by mohammad-siraj** [comment]
Hello! I would love to work on this issue. @rahulk789

**Comment by rahul-cedana** [comment]
Finally :pray:
