### ISSUE TITLE
Support enforcement for init containers

### ISSUE THREAD

**Issue by achrefbensaad** [kubearmor/KubeArmor#870]
## Feature Request

**Short Description**

KubeArmor does not enforce security policies on init containers.

**Describe the solution you'd like**

KubeArmor enforce security policies on init containers.

- [ ] Update KubeArmor
- [ ] Update Annotation Controller
- [ ] Update KubeArmor Controller
- [ ] Discuss how to automate tests for init containers

**Comment by achrefbensaad** [comment]
We decided not to enable enforcement for init containers as they are short lived

**Comment by vholer** [comment]
Well, this is big missing feature... and also could be a security issue.
One would expect that pod (matching the selector) is covered / secured **completely**.
I don't see it documented anywhere, is it?
