### ISSUE TITLE
Code refactoring: remove annotation, policy and host policy controllers from kubearmor code base

### ISSUE THREAD

**Issue by achrefbensaad** [kubearmor/KubeArmor#875]
## Feature Request

In v0.6 we have merged all the controllers into one controller called `KubeArmorController`.

In v0.7 we aim to completely remove the controller form kubearmor and all related projects. 

- [x] Create Clientset for `KubeArmorController`
- [ ] Identify controllers dependency (deploygen, kubearmor-client, discovery engine, ...)
- [ ] Update the dependent projects with the required changes
- [ ] Remove the controllers from the code base

**Comment by aishwarya25252** [comment]
Can I look into this issue ?

**Comment by achrefbensaad** [comment]
Sure.
