### ISSUE TITLE
Improve CRI Socket detection and mounting

### ISSUE THREAD

**Issue by daemon1024** [kubearmor/KubeArmor#876]
## Feature Request

Currently we detect the various env configuration on the kArmor client side and mount the CRI Sockets accordingly. But these detections are not always right.  Suppose if it's a k3s or gke cluster we set a particular socket. But it's possible that they are configured with a different socket. And kubearmor would fail to run in this case.

**Describe the solution you'd like**
Mount entire `/var` directory and let KubeArmor decide the socket. 

**Describe alternatives you've considered**

Make client side env detection more intelligent by taking container runtime and k8s version into consideration. Like if it's a k3s cluster and has containerd runtime, the CRI Version has k3s mentioned in it, if not then we mount standard containerd path. But we might still miss edge cases here.

**Comment by Shreyas220** [comment]
Hey I would like to work on this

**Comment by daemon1024** [comment]
Will be handled as part of https://github.com/kubearmor/KubeArmor/issues/914
