### ISSUE TITLE
Support KubeArmor on M1  

### ISSUE THREAD

**Issue by s1ntaxe770r** [kubearmor/KubeArmor#880]
## Feature Request
Support KubeArmor on M1 Macs 

**Short Description**
With #802 we should be able to bring KubeArmor to the following environments on Mac 

**Describe the solution you'd like**

With #802 we should be able to bring KubeArmor to the following environments on Mac 

- Test ARM based VM's on Mac 
- Minikube on M1 

Additionally relevant documentation should be updated once KubeArmor is able to run on the above platforms

**Comment by s1ntaxe770r** [comment]
@nyrahul  issue related to #614

**Comment by Ankurk99** [comment]
Completed as part of v0.7
