### ISSUE TITLE
go vulnerability scan

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#889]
[Golang has announced](https://go.dev/blog/vuln) new support for vulnerability management that will help developers learn about the known vulnerabilities that may affect them.

Intent of this issue is to integrate kubearmor CI with such vulnerability scanning engine using GH actions.

Tasks involved:
- [x] vulnerability detection using `govulncheck` ([ref](https://go.dev/blog/vuln#:~:text=Vulnerability%20detection%20using%20govulncheck))
- [x] Update makefile to support `make scan` that will scan for vulnerabilities
- [ ] Update GH actions to support scanning of vulnerabilities in CI env. Fail the CI if a vulnerability is found in a PR.

**Comment by rakshitgondwal** [comment]
Hey @nyrahul !! 
I would like to work on this issue. Can you tell me the prerequisites to solve this issue?

**Comment by nyrahul** [comment]
> Hey @nyrahul !! I would like to work on this issue. Can you tell me the prerequisites to solve this issue?

I think the issue is fairly straightforward to handle. The issue description provides enough context/reference. It would help if you have:
* golang background
* understand how to update GH action

But both of these are not must haves to begin with i.e., one can easily have a look at the context and understand it.

**Comment by Shivansh-yadav13** [comment]
Hello, I would like to contribute if no one is already working on this.

**Comment by rakshitgondwal** [comment]
Hey @Shivansh-yadav13 
I am working on this issue right now, I am still figuring it out. I would love to work with you. What say?

**Comment by nyrahul** [comment]
Folks, thank you for the interest. Please let us know on the slack channel if you have any specific questions. Best is to raise the PR and get the ball rolling.

**Comment by kranurag7** [comment]
I have looked into the issue and I think for the issue we need to check all the directories where we are using any external dependencies. 

```bash
find . -name 'go.mod' -printf "%h\n" | sort -u  
./deployments
./KubeArmor
./KubeArmor/BPF/tests
./pkg/KubeArmorAnnotation
./pkg/KubeArmorController
./pkg/KubeArmorHostPolicy
./pkg/KubeArmorPolicy
./protobuf
./tests
```

- After trying locally, I found for `govulncheck` to work, you will need a `go.mod`, `go.sum` and go files in a directory. These are the directories which are passing on these three parameters.  

- [x] ./deployments 
- [x] ./KubeArmor 
- [x] ./KubeArmor/BPF/tests 
- [x] ./pkg/KubeArmorAnnotation 
- [x] ./pkg/KubeArmorController 
- [x] ./pkg/KubeArmorHostPolicy 
- [x] ./pkg/KubeArmorPolicy 
- [ ] ./protobuf (Error: missing go.sum file)
- [ ] ./tests (Error: no Go files)

- The PR should cover these directories which are passing on the `govulncheck` parameters.

**Comment by sheharyaar** [comment]
I have update the PR, kindly review it

**Comment by ggold7046** [comment]
Is anyone still working on this issue ?

**Comment by kranurag7** [comment]
@ggold7046 This was fixed via this PR. https://github.com/kubearmor/KubeArmor/pull/899

**Comment by daemon1024** [comment]
Pending Action Item.
We still need github actions to carry this check.

**Comment by kranurag7** [comment]
I just created a patch to trigger the vuln scan in CI. 
https://github.com/kubearmor/KubeArmor/pull/1585
