### ISSUE TITLE
[VM] KubeArmor failing on Amazon Linux 2

### ISSUE THREAD

**Issue by rohitrishim** [kubearmor/KubeArmor#919]
## Bug Report

Not able to get KubeArmor running on Amazon Linux 2 kernal version 5.10

General Information

- Environment description: Amazon Linux 2
- Kernal version: 5.10

These are the problems:

issue: KubeArmor not running
```
[ec2-user@ip-172-31-11-103 ~]$ systemctl status kubearmor.service
● kubearmor.service - KubeArmor
   Loaded: loaded (/usr/lib/systemd/system/kubearmor.service; enabled; vendor preset: disabled)
   Active: inactive (dead)

Sep 27 10:05:29 ip-172-31-11-103.us-west-1.compute.internal kubearmor[21203]: github.com/kubearmor/KubeArmor/KubeArmor/core.KubeArmor
Sep 27 10:05:29 ip-172-31-11-103.us-west-1.compute.internal kubearmor[21203]: /home/runner/work/KubeArmor/KubeArmor/KubeArmor/core/kubeArmor.go:419
Sep 27 10:05:29 ip-172-31-11-103.us-west-1.compute.internal kubearmor[21203]: main.main
Sep 27 10:05:29 ip-172-31-11-103.us-west-1.compute.internal kubearmor[21203]: /home/runner/work/KubeArmor/KubeArmor/KubeArmor/main.go:44
Sep 27 10:05:29 ip-172-31-11-103.us-west-1.compute.internal kubearmor[21203]: runtime.main
Sep 27 10:05:29 ip-172-31-11-103.us-west-1.compute.internal kubearmor[21203]: /opt/hostedtoolcache/go/1.18.5/x64/src/runtime/proc.go:250
Sep 27 10:05:29 ip-172-31-11-103.us-west-1.compute.internal kubearmor[21203]: 2022-09-27 10:05:29.823838        INFO        Stopped KubeArmor Monitor
Sep 27 10:05:29 ip-172-31-11-103.us-west-1.compute.internal kubearmor[21203]: 2022-09-27 10:05:29.823846        INFO        Terminated KubeArmor
Sep 27 10:05:31 ip-172-31-11-103.us-west-1.compute.internal kubearmor[21203]: 2022-09-27 10:05:31.824120        INFO        Stopped KubeArmor Logger
Sep 27 10:05:31 ip-172-31-11-103.us-west-1.compute.internal kubearmor[21203]: 2022-09-27 10:05:31.824181        INFO        Waiting for routine terminations
```

To Reproduce

1. Followed Step : https://help.accuknox.com/open-source/kubearmor/al2/al2/
2. Used latest release i.e., ```kubearmor_0.6.0_linux-amd64.rpm```

**Comment by HariVamsiK** [comment]
Hey @Ankurk99 Please assign this to me. I'll check it out.

**Comment by HariVamsiK** [comment]
Hey @nyrahul i was able to solve this, i ran it on my AWS instance and it worked. The daemon has to be reloaded, i checked the logs. Its better that we add a troubleshooting guide for AWS in respective README.md file. I'll add it to the README and raise the PR.

**Comment by HariVamsiK** [comment]
![1](https://user-images.githubusercontent.com/112711197/206967027-be4cff95-ed00-40b5-bdb9-7e4eb2ff7efd.jpg)
![2](https://user-images.githubusercontent.com/112711197/206967031-d37f34ee-c056-45bd-8d3a-87e6f5a9b014.jpg)

**Comment by Ankurk99** [comment]
@HariVamsiK How were you able to get this resolved? By running `systemctl daemon-reload`? 
That's already a part of KubeArmor documentation here under "For distributions other than Ubuntu/Debian": https://github.com/kubearmor/KubeArmor/blob/main/getting-started/kubearmor_vm.md

**Comment by HariVamsiK** [comment]
I resolved it by installing previous version of kubearmor first, removing it and installing a new version, doing a daemon reload.

**Comment by Ankurk99** [comment]
As per https://github.com/kubearmor/KubeArmor/pull/1016#discussion_r1046015730, this issue is fixed. @rohitrishim Can you please confirm this?

**Comment by HariVamsiK** [comment]
Its working for latest version of kubearmor(v 0.7.2) on Amazon Linux 2 Kernel Version 5.10

**Comment by rohitrishim** [comment]
> 

@Ankurk99 yes, will check and confirm with you

**Comment by rohitrishim** [comment]
Hey @Ankurk99 I have checked kubearmor on Amazon Linux 2 Kernel Version 5.10 it's working fine now, I think we can close this issue.
![kube aws linux vm](https://user-images.githubusercontent.com/88204255/207232497-a98eac0f-9b0f-433e-8123-11f71a663919.png)
cc: @ravkishu

**Comment by Ankurk99** [comment]
@rohitrishim Thanks for the confirmation
