### ISSUE TITLE
Karmor Log(Alert), TAG field changes from string to string array

### ISSUE THREAD

**Issue by AbhinavCSY** [kubearmor/KubeArmor#961]
## Feature Request

In policies there are multiple tags in a single array, due to a single policy can be linked to different use cases, changing it to a string array will send the partitioned Tags in output, which will be easy to handle in different SIEM integration and further representation.

Currently, in the output, the Tags are coming in this format combined as a single string 

```
Tags: MITRE, MITRE_T1552_unsecured_credentials
```
Changing the output to the below output will automatically portion the tags.
```

"Tags": [
            "MITRE",
            "MITRE_T1552_unsecured_credentials"
        ],

```

- [ ] Create new protobuf entry
- [ ] Add a task to deprecate "tags" field in v0.10.

**Comment by nyrahul** [comment]
@vishnusomank, would you be able to handle this change? Let us know if any discussion needed. Thanks

**Comment by nyrahul** [comment]
we cannot change existing field and convert it to Array of strings..

As discussed we will add a new field "ATags" (Array of tags) .. and leave existing field as it is.

```
"ATags": [
            "MITRE",
            "MITRE_T1552_unsecured_credentials"
        ],
```
