### ISSUE TITLE
Kubearmor logs/alerts are not generated in latest image 

### ISSUE THREAD

**Issue by seswarrajan** [kubearmor/KubeArmor#964]
## Kubearmor logs are not getting generated with the latest image when performing a stress test on kubearmor

**General Information**

- Environment description (GKE, k3s)
- Kernel version (5.15.0-52-generic)
- Orchestration system version in use (1.22 kubectl version)
- Install kubearmor latest image
- Any pod/deployment. Using test nginx deployment

**To Reproduce**

1. Install kubearmor latest using `karmor install --image kubearmor/kubearmor:latest`
2. Open new tab and run `karmor log --logFilter all --json | jq .`
3. Now deploy nginx or wordpress-mysql
4. Exec into the pod
5. Run this command in the pod bash/sh : `while [ 1 ]; do apt update && sleep 1; done`
6. After certain time interval(approx 5 mins), the logs are interrupted and not displayed in karmor log.

**Expected behavior**

Logs to be displayed without any interruption

[karmor-sysdump-Thu Nov  3 09_09_35 IST 2022.zip](https://github.com/kubearmor/KubeArmor/files/9926915/karmor-sysdump-Thu.Nov.3.09_09_35.IST.2022.zip)

**Comment by nyrahul** [comment]
We are not facing this issue anymore .. Tried reproducing. We will keep it open for some more time to observe.

**Comment by seswarrajan** [comment]
Not observing this now. Hence closing the same.
