### ISSUE TITLE
KubeArmor pods failing on WLAN disconnection

### ISSUE THREAD

**Issue by Ankurk99** [kubearmor/KubeArmor#966]
## Bug Report
KubeArmor pods: kubearmor-annotation manager and kubearmor-policy-manager are going to ErrImagePull when wlan is turned off.

**General Information**

- Environment description: k3s (running directly on host), latest KubeArmor image
- Kernel version (run `uname -a`): 5.15.74
- Target containers/pods: kubearmor-annotation-manager and kubearmor-policy-manager

**To Reproduce**

1. Run `karmor install` and wait for the deployment to run
2. Once `KubeArmor` is running switch of the wifi connectivity

**Buggy behavior**
The above mentioned pods are going to CrashLoopBackOff when disconnected from the internet

```
  Warning  Failed          7m55s                  kubelet  Failed to pull image "kubearmor/kubearmor-annotation-manager:latest": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/kubearmor/kubearmor-annotation-manager:latest": failed to resolve reference "docker.io/kubearmor/kubearmor-annotation-manager:latest": failed to do request: Head "https://registry-1.docker.io/v2/kubearmor/kubearmor-annotation-manager/manifests/latest": dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:44854->[::1]:53: read: connection refused
  Warning  Failed          7m55s (x2 over 8m10s)  kubelet  Error: ErrImagePull
```

**Expected behavior**

KubeArmor deployment shouldn't be dependent on wifi connectivity

Edit: It is WLAN disconnectivity and not related to internet

**Comment by rksharma95** [comment]
i'm not able to reproduce the issue, tested on ubuntu 20.04 with k3s, kubearmor is working fine after disconnecting from the internet.

**Comment by Ankurk99** [comment]
@rksharma95 Can you check with the edited issue?
