### ISSUE TITLE
Inconsistent Behaviour with Symlinks Execution

### ISSUE THREAD

**Issue by daemon1024** [kubearmor/KubeArmor#984]
## Bug Report

We read for actual execution path and not symlinked path while enforcing rules. Like `/bin/sleep` symlinked to `/bin/busybox` will be read as `/bin/busybox` by the enforcer.

But our monitor outputs the Resource as `/bin/sleep`. This is an incosistent behaviour. We should ideally observe what we enforce.

**General Information**

- Environment description *
- Kernel version *
- Orchestration system version in use *
- Target containers/pods
    - https://hub.docker.com/r/nicolaka/netshoot

**To Reproduce**

1. Create a deployment with above image
2. Apply a policy to block a `/bin/sleep`
3. Observe telemetry
4. Execute `sleep`

**Expected behavior**

Either Block `sleep` or show `busybox` in Telemetry event.

**Actual Behaviour**

Neither blocked `sleep` or but passes sleep in Telemetry event.

**Screenshots**

`/bin/sleep` in telemetry log
![image](https://user-images.githubusercontent.com/47106543/201489956-2d5ea2b1-8c32-4353-87d9-6fb920e6d311.png)

symlinked to `busybox`
![image](https://user-images.githubusercontent.com/47106543/201489989-5df86413-141e-4246-8952-4e6dd3ce6d16.png)

We see `/bin/busybox` in BPFLSM debug logs. (Policy was changed to block /bin/ dir)
![image](https://user-images.githubusercontent.com/47106543/201489901-1dfc6969-4af3-4095-a160-338ddf5f545e.png)

**Comment by daemon1024** [comment]
Noting `busybox` images can have standalone or symlink setup. This is not an issue with standalone version i.e. the official `busybox` docker image.

**Comment by mdsahiloss** [comment]
@daemon1024 I would like to work on it.

**Comment by rksharma95** [comment]
great @MdSahil-oss :+1:

**Comment by nyrahul** [comment]
As discussed today, we can use kprobes at LSM hooks so that we get the final resolved binary name in place symlinks. This would result in telemetry events containing the final binary name in place of symlink.
